### ISSUE TITLE
Login with a Gnosis Safe app doesnt work

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1007]
- When i try to login on Snapshot within Gnosis Safe apps UI it fail to resolve here is the error i see
![image](https://user-images.githubusercontent.com/16245250/140415326-d36a833c-b24a-4644-8a47-1db157b7858d.png)

- Also, the connector "Gnosis Safe" should appear in top on the login modal

**Comment by yanik-ai** [comment]
Same issue here. After pressing connect wallet -> gnosis safe : 

Failed to load resource: the server responded with a status of 403 (Forbidden)
gnosis-safe-token-logos.s3.amazonaws.com/0x9719d867A500Ef117cC201206B8ab51e794d3F82.png:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
worker.snapshot.org/mirror?img=https%3A%2F%2Fraw.githubusercontent.com%2Fsnapshot-labs%2Fsnapshot-spaces%2Fmaster%2Fspaces%2Folympusdao.eth%2Fspace.png:1 Failed to load resource: the server responded with a status of 404 ()
worker.snapshot.org/mirror?img=https%3A%2F%2Fraw.githubusercontent.com%2Fsnapshot-labs%2Fsnapshot-spaces%2Fmaster%2Fspaces%2Ftheheaddao.eth%2Fspace.png:1 Failed to load resource: the server responded with a status of 404 ()
vendor.84d12e60.js:9 TypeError: r is not a constructor
    at dhe.connect (vendor.84d12e60.js:9)
    at async Object.o [as login] (vendor.84d12e60.js:9)
    at async e (index.87d3e32f.js:2367)
    at async w (index.87d3e32f.js:2546)
connect @ vendor.84d12e60.js:9
vendor.84d12e60.js:9 TypeError: Cannot set properties of undefined (setting 'connectorName')
    at dhe.connect (vendor.84d12e60.js:9)
    at async Object.o [as login] (vendor.84d12e60.js:9)
    at async e (index.87d3e32f.js:2367)
    at async w (index.87d3e32f.js:2546)

**Comment by ChaituVR** [comment]
Not fixed on #1106

**Comment by bonustrack** [comment]
@ChaituVR login doesnt work?

**Comment by bonustrack** [comment]
Or voting doesnt work?

**Comment by ChaituVR** [comment]
@bonustrack Same issue as above, error while login

**Comment by bonustrack** [comment]
@midgerate Can you reproduce?
