### ISSUE TITLE
Add alerts upon proposal publishing

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1010]
**Describe the bug**
In the proposal creation page, if for instance the "Question ?" placeholder is not filled or the choices not populated the publish button is greyed out. This is not intuitive. It's a recurring support issue.

**Expected behavior**
An alert should enumerate the missing fields upon clicking on Publish.

**Screenshots**
<img width="1048" alt="Capture d’écran 2021-11-05 à 23 07 57" src="https://user-images.githubusercontent.com/55286013/140543991-058833b6-a86f-4532-8541-a63d8e0de776.png">

**Comment by metrox-eth** [comment]
More and more recurring in support, @xinyi says that many ppl in Chinese channel mention this issue too.

**Comment by WUXINYIMiffy** [comment]
'Ask a question...' in Chinese version can be ' 问题... ‘.  To be specific, it also can be ' 请写下问题... ‘ means ‘ Please ask a question ...’ . Basically, ppl in Chinese get used to use ' 标题 ‘ which means ' title ' when filling out forms.

**Comment by zzuziak** [comment]
Closing as the UI has changed :pray:
