### ISSUE TITLE
Update hint link in confirm vote modal

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1012]
The hint link that appear when a voter has 0 voting power is still pointing to GitBook, it should be changed to the "Why I can't vote" Q/A in GitHub Discussions --> https://github.com/snapshot-labs/snapshot/discussions/767

<img width="439" alt="Capture d’écran 2021-11-06 à 00 12 29" src="https://user-images.githubusercontent.com/55286013/140551362-fa148cc7-b6f4-4308-a713-799fd7530381.png">

**Comment by ChaituVR** [comment]
@bonustrack recently updated it to https://github.com/snapshot-labs/snapshot/discussions/1015#discussioncomment-1599447
we can close this issue or https://github.com/snapshot-labs/snapshot/discussions/767 is a more relevant answer??
