### ISSUE TITLE
Crowdin PR do not merge

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1013]
The last few crowdin automated PR did not get merged in the last snapshot version.

Two exemples from yesterday that are not reflecting on the UI
https://github.com/snapshot-labs/snapshot/commit/e24c91fec2fd020269cc34d55a95c42cfc88a685
https://github.com/snapshot-labs/snapshot/commit/007bafb9bfdb12b2f6b83ecaa7c63da25c06da57

**Comment by midgerate** [comment]
@metrox-eth I am not sure what you mean. There is an open PR which is not merged, so the changes wont reflect https://github.com/snapshot-labs/snapshot/pull/1046/files

Unless this PR is merged, the changes wont show.

**Comment by metrox-eth** [comment]
Gotcha thx
