### ISSUE TITLE
Use available space in modal

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1019]
On large/desktop screens modals could be a lot higher to reduce scrolling, in some cases avoiding it completely.

![image](https://user-images.githubusercontent.com/6792578/140785395-d68f4cfb-ee56-459c-8060-664b3b481707.png)

![image](https://user-images.githubusercontent.com/6792578/140786241-cd432083-331e-41ee-9bf4-333ad26a0eba.png)

**Comment by bonustrack** [comment]
It's not ideal it will change height depending on the content, when you do a search the heigh will move a lot

**Comment by mktcode** [comment]
There are other modals where it still makes some sense I think, e.g. json configs of plugins.

**Comment by samuveth** [comment]
I think it's mostly fine like it is now.
