### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by gokaiorg** [snapshot-labs/snapshot#102]

**Comment by bonustrack** [comment]
Or redirect to homepage

**Comment by mktcode** [comment]
https://github.com/snapshot-labs/snapshot/issues/1211 is fixed. Also redirects to home now.

Need design for proper 404 page.

**Comment by zzuziak** [comment]
Shall we pick this one up to make sure all edge cases are covered? :pray: @samuveth

**Comment by samuveth** [comment]
@zzuziak need design for this.

**Comment by zzuziak** [comment]
We can also use the redirect to home for now, one option would be to display an alert of what happened after the redirection (URL you are looking for doesn't exist). Wdyt?

**Comment by Todmy** [comment]
The solution should be in configuring DO. We need to set `catchall_document` to `index.html`:

1. Using Cloud panel UI: Log in and click on App > Settings >> click on component name > scroll down to Custom page > Edit Custom page and select Catchall > Enter index.html in the page name block > save
2. Using App Spec: You can the catchall_document to index.html in-app spec.

**Comment by samuveth** [comment]
> The solution should be in configuring DO. We need to set `catchall_document` to `index.html`:
> 
> 1. Using Cloud panel UI: Log in and click on App > Settings >> click on component name > scroll down to Custom page > Edit Custom page and select Catchall > Enter index.html in the page name block > save
> 2. Using App Spec: You can the catchall_document to index.html in-app spec.

@Todmy What you are referring to I think is handling 404 pages on server level. But since we're hosting the frontend on Fleek, which serves static files and doesn't provide server-side configurations, the best approach would be to handle 404 pages directly within the application using Vue Router.

**Comment by Todmy** [comment]
@samuveth it cannot be done with the Vue router (only if we change it's type to `history`). This will require some changes to the hosting provider. After an investigation, I have found a way how to do it https://github.com/snapshot-labs/snapshot/pull/4100. I agree that it's not perfect, but better than nothing.
