### ISSUE TITLE
ENS domains aren't showing up for users on first page of votes

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1036]
When I load a proposal, in the "Votes" sections I can't see the ENS domains for the first 10 voters displayed, I only see it once I click "See more", for some reason

![bug](https://user-images.githubusercontent.com/16245250/141453625-438bb54d-6e21-4bfb-b98b-20f8c5fef85f.gif)

Used this proposal: https://snapshot.org/#/superraredao.eth/proposal/0xc9fa170547b53f870e12127440603b6f67bab905653b99735d869cd3fcfbb40f

**Comment by midgerate** [comment]
@gbonumore @bonustrack It happens because the watch handler in the useProfiles.ts is getting registered twice, the other one is in SpaceProposal.vue

I am not sure how to solve this. @mktcode ideas?

**Comment by mktcode** [comment]
I'll take a look.
