### ISSUE TITLE
Update ENS snapshot text record name on screenshot

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1049]
On the "Create space" page on GitBook, ENS snapshot text record name need to be entered in lowercase, but it's on uppercase on the screenshot, this lead to confusion and a user complained he lost gasfee.

![uppercase](https://user-images.githubusercontent.com/55286013/141670406-98126bb6-1459-4e5b-a9a5-46aa34381c5b.png)

**Comment by fxl9922** [comment]
Follow the text instructions
