### ISSUE TITLE
Integrate login.xyz 

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1074]
https://github.com/spruceid/siwe

**Comment by rootial** [comment]
Hi @bonustrack , i could help on this task and want to ask some question about it before i start. Is this task going to add login.xyz as an option in this modal? 
![image](https://user-images.githubusercontent.com/3824034/144715462-8c1f001f-06f9-4ddd-9be3-b3d81b10c137.png)

**Comment by bonustrack** [comment]
@rootial This task is in standby we need some change and guide from login.xyz to integrate it.
