### ISSUE TITLE
Update Vue and Vite to latest beta version

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1082]
Vue is on 3.2.24 https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md
Vite has 2.7.0 https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md
We should test that voting is working fine on the different connectors (Metamask, WalletConnect, Coinbase...etc)

**Comment by bigint** [comment]
I just migrated vue to `3.2.26` and tested all functionalities and it works fine as it is

Next I tried to migrate vite version by version, but it got failed in the next `2.6.0-beta.3` itself 😞 

<img width="949" alt="Screenshot 2021-12-12 at 8 33 31 PM" src="https://user-images.githubusercontent.com/69431456/145717652-f8bea940-1a85-4bbf-9466-fbfecf74da63.png">

**Comment by bonustrack** [comment]
@bigint How about Vite v2.7.0?

**Comment by mktcode** [comment]
I jumped right to vite 2.7.2 and I'm running into this:

```
[vite] Internal server error: Custom directive is missing corresponding SSR transform and will be ignored.
  Plugin: vite:vue
  File: /home/mkt/Projects/snapshot-labs/snapshot/src/views/SpaceProposal.vue
  337|                <span v-for="(symbol, symbolIndex) of symbols" :key="symbol">
  338|                  <span
  339|                    v-tippy="{
     |                     ^
  340|                      content: symbol
  341|                    }"
```

Since we are not using SSR, I'm not sure why this is even an issue.

https://github.com/vuejs/vitepress/issues/92
