### ISSUE TITLE
Homepage space links should be work with mouse wheel click

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1083]
Wheel click should be working when clicking on a space on the homepage
![image](https://user-images.githubusercontent.com/16245250/142655147-0d7ea416-95a7-4f1d-879c-237a788e7dc4.png)

**Comment by rootial** [comment]
Hi @bonustrack, just want to ask what's a wheel click?

**Comment by bonustrack** [comment]
@rootial ![image](https://user-images.githubusercontent.com/16245250/142669194-9a06ad74-86c2-46e1-bf49-3b61ce1c713e.png)
