### ISSUE TITLE
feature: show voting power in one  snapshot space

### ISSUE THREAD

**Issue by bobjiang** [snapshot-labs/snapshot#1113]
**Is your feature request related to a problem? Please describe.**

I would like to know my own voting power in one space (no matter if I vote or not).

**Describe the solution you'd like**
here is my proposal as following screenshot:
![image](https://user-images.githubusercontent.com/1224604/143233265-61b3b818-0509-4b94-afc0-c2b41c26a770.png)

**Describe alternatives you've considered**
I believe it is cool for list the latest voting power, 

**Additional context**

**Comment by zzuziak** [comment]
I think it might be confusing to some users, as users can have different voting power for each proposal. We could do it with a clear indication that it's the voting power valid mainly for proposals created after the time of fetching the voting power. 

We could possibly handle that with a daily worker and data caching which can be cleared whenever user casts a vote (when we check their holdings).

Wdyt @bonustrack ?
