### ISSUE TITLE
Charts plugin broken for "Voting power per day" tab

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1123]
The line in the charts create impossible see spike 
![image](https://user-images.githubusercontent.com/16245250/143484373-6fd2a37f-ee73-4048-b360-48ebebed3126.png)
From this proposal:
https://snapshot.org/#/paraswap-dao.eth/proposal/0xfbb6caaf5e4c297ab8119ead0be97d88b17a35ad130b397582c9d2b9db3ff871

**Comment by sarmatdev** [comment]
It looks like this bug is gone. Maybe there is any way to reproduce it?
