### ISSUE TITLE
Improve setup space page

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#1132]
Related to #989 

- Go to `/#/setup`
- Once the space name is entered into input, Check if space exist on snapshot
- If space exists - Redirect to space on click of submit button
- If space doesn't exist: 
  - Check if the name is registered
  - If the name belong to user - Redirect to space on click of submit button 
  - If the name is already registered by someone else - Show not available message
  - If the name is available:
    - Change button text to "Register" and on click redirect to register page with the name input
    - Register page (`https://app.ens.domains/name/<ENS NAME>/register`) - Change this to `/register?name=example.eth` when register page is available

**Comment by ChaituVR** [comment]
Waiting for #1029 to be merged

**Comment by bonustrack** [comment]
We should do like this https://github.com/snapshot-labs/snapshot/pull/1029#issuecomment-987837437
