### ISSUE TITLE
Create a voting strategy for Juicebox

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1143]
Currently you need to use "contract-call" strategy to get voting power for a project on Juicebox https://juicebox.money , see this guide: https://juicebox.notion.site/How-to-use-Juicebox-tokens-in-a-Snapshot-strategy-4f7ea3518c31409dad8a4d649021a972
We need to create a custom strategy "juicebox" that make this easier, where you only have to add the symbol and the project id.
More context: https://twitter.com/erik_udahl/status/1465521855289344004

**Comment by drgorillamd** [comment]
Hi, just submitted a PR here https://github.com/snapshot-labs/snapshot-strategies/pull/206 (as new contributor)

**Comment by bonustrack** [comment]
Worked in by @drgorillamd here: https://github.com/snapshot-labs/snapshot-strategies/pull/206

**Comment by bonustrack** [comment]
@drgorillamd You contact me or Laurent in our Discord https://discord.snapshot.org/
