### ISSUE TITLE
Update page title and add social media meta tags.

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1148]
Some solution to update the page title dynamically should be implemented and at least the pages that can be expected to be bookmarked and shared a lot should have their individual titles.

![ezgif-2-2ce73d17990c](https://user-images.githubusercontent.com/6792578/144148484-d1edeb4e-2d3a-4e5b-8653-a4a29b20eb2e.gif)

This

![image](https://user-images.githubusercontent.com/6792578/144149183-3d2af26e-7044-4344-9ada-7c70a45dfd51.png)

could also look much better by adding some [meta tags](https://css-tricks.com/essential-meta-tags-social-media/).

**Comment by samuveth** [comment]
Very much needed! Thanks for making the issue

**Comment by zzuziak** [comment]
Will take it on :pray:

**Comment by zzuziak** [comment]
Will be tackled in #1395 which is also extended to SEO of Snapshot.
