### ISSUE TITLE
Error: Patch file found for package lock which is not present at node_modules/@snapshot-labs/lock

### ISSUE THREAD

**Issue by zhouhanseng** [snapshot-labs/snapshot#1153]
```
$ yarn
```

![image](https://user-images.githubusercontent.com/63733714/144212281-9c48de48-17af-41db-9705-840168126325.png)

**Comment by zhouhanseng** [comment]
@samuveth Unable to install the dependencies from the beginning, would you like to help to solve this?

**Comment by samuveth** [comment]
> @samuveth Unable to install the dependencies from the beginning, would you like to help to solve this?

@zhouhanseng Can you provide step to reproduce

**Comment by zhouhanseng** [comment]
@samuveth Just clone the repo, then run `yarn`.

Version of yarn: 1.22.10
system: macOS 10.15.7

**Comment by samuveth** [comment]
@ChaituVR can you reproduce this? I can't..
