### ISSUE TITLE
Improvements for fetching and displaying votes

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1162]
Current pagination with "See more" doesn't work well when there are hundreds of votes and more.

Issue:
Looking for a vote by a specific ethereum address could require the user to paginate endless times and then scroll all the way back to the top of the page when done.

Proposed solution:
When the user selects "See more" open the votes in a modal with infinite scroll pagination. Add a search at the top of the modal where the user can search for a specific vote by entering an address (can be expanded to other possible searches). Both the search and the scroll will make use of GraphQL queries for optimisation.

**Comment by bonustrack** [comment]
As an user i want to see my vote directly, I don't want to manually do a search.

**Comment by samuveth** [comment]
> As an user i want to see my vote directly, I don't want to manually do a search.

Users will still see their vote in first position of the block. The modal is only for advanced searches and pagination
