### ISSUE TITLE
Highlight users vote

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1167]
The users vote should be highlighted in the votes block

Example
![image](https://user-images.githubusercontent.com/51686767/144707852-ef22312c-a336-41c9-bd24-97efbf0ac58a.png)

**Comment by zzuziak** [comment]
I'd make it more subtle, but sounds like a quick fix. @samuveth could you possible take care of it?

**Comment by samuveth** [comment]
@zzuziak issues with a Design label are waiting for a designer.
