### ISSUE TITLE
Handle strategy config conflicts in UI

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1182]
In below example the UI has crashed, because the specified token is incompatible with the strategy. (trying to apply ERC20 strategy to ERC1155 token).

![image](https://user-images.githubusercontent.com/6792578/144917501-9b0c8eac-2e7c-44ab-8bb7-8d1f62179324.png)

Such conflicts need to be (avoided in the first place obviously but also) handled properly in the UI instead of just freezing it.

The UI could also show some alert if such a conflict is detected.

![image](https://user-images.githubusercontent.com/6792578/144919908-1780f6d5-2900-49cc-96f5-138f2fa05287.png)

Or it should get checked when changing space settings, idk.

**Comment by samuveth** [comment]
Checking on space settings would be preferable I think.

**Comment by mktcode** [comment]
> Checking on space settings would be preferable I think.

The thought I have on this is: Is there a situation where someone might actually want to configure something "invalid", like a singleton token address that is yet to be deployed.... whatever. A situation where people want to "prepare" something that is not yet valid. Then an alert would be better instead of enforcing it on settings page maybe.
