### ISSUE TITLE
Add SEO for spaces

### ISSUE THREAD

**Issue by bigint** [snapshot-labs/snapshot#1210]
**Is your feature request related to a problem? Please describe.**

Currently, snapshot is less discoverable in social media and search engines

**Describe the solution you'd like**

It would be great if snapshot have support for SEO for spaces

**Comment by samuveth** [comment]
Yes! There are some issues with SSR and IPFS that we still need to figure out. Any other suggestions than SSR?

**Comment by bigint** [comment]
@samuveth I tried lot of ways but everything needs SSR 😅 

But not sure how Twitter handles it 🤔

**Comment by samuveth** [comment]
@bigint maybe something like this https://prerender.io/ ?

**Comment by bigint** [comment]
@samuveth This is interesting, I never tried services for SEO rather than plugins 😅
