### ISSUE TITLE
Move votes into a modal

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1217]
Issue:
Looking for a vote by a specific ethereum address could require the user to paginate endless times and then scroll all the way back to the top of the page when done.

Proposed solution:
When the user selects "See more" open the votes in a modal with infinite scroll pagination. Add a search at the top of the modal where the user can search for a specific vote by entering an address (can be expanded to other possible searches).

**Comment by bigint** [comment]
Sounds good 👍🏻

**Comment by mktcode** [comment]
The search would require some backend work, I assume.

**Comment by samuveth** [comment]
@mktcode as I mentioned here we actually have the vote count already with `voteCount`.

For the search we can also already query a vote by the voter address so no backend work need.
https://hub.snapshot.org/graphql?operationName=Votes&query=query%20Votes%20%7B%0A%20%20votes%20(%0A%20%20%20%20first%3A%201000%0A%20%20%20%20skip%3A%200%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20voter%3A%20%220xF78108c9BBaF466dd96BE41be728Fe3220b37119%22%0A%20%20%20%20%20%20proposal%3A%20%22QmeRpDPXiZZXnx43J94pWyU9PbQMaBgbgy68Jk5qRueUaM%22%0A%20%20%20%20%7D%0A%20%20%20%20orderBy%3A%20%22created%22%2C%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20)%20%7B%0A%20%20%20%20id%0A%20%20%20%20%20%20ipfs%0A%20%20%20%20%20%20voter%0A%20%20%20%20%20%20created%0A%20%20%20%20%20%20choice%0A%20%20%20%20proposal%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20space%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20%20%20vp%0A%20%20%20%20%20%20vp_by_strategy%0A%20%20%7D%0A%7D%0A

**Comment by zzuziak** [comment]
Agree that it would be much more comfortable for users. @Sekhmet inspiration for SX :eyes:
