### ISSUE TITLE
Search bar colors should match categories

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1224]
![image](https://user-images.githubusercontent.com/51686767/145673963-d92d1bad-bfbf-405c-9fad-4c20c94ab061.png)

The search icon and the explore dropdown should be matching the color with the new categories component.

**Comment by rootial** [comment]
should we change the color of categories component to the same as that of search component? @samuveth

**Comment by sasicodes** [comment]
@samuveth 
![image](https://user-images.githubusercontent.com/29498872/145722735-e8b65807-b48a-49d0-90d2-ff7bb2c9af53.png)
