### ISSUE TITLE
question: Do we need same token info in tooltip for signatures?

### ISSUE THREAD

**Issue by bigint** [snapshot-labs/snapshot#1236]
<img width="176" alt="image" src="https://user-images.githubusercontent.com/69431456/145701405-9ebda150-833e-4894-a5c0-973a40ba838c.png">

**Comment by samuveth** [comment]
@bigint not sure what you mean here.

**Comment by bigint** [comment]
@samuveth If you see we display `0.01 YFI` as a label and same thing in tooltip, do we need same data to be displayed there?

**Comment by samuveth** [comment]
Oh, this isn't always the same. Maybe if it's the same we can disable the tooltip

**Comment by bigint** [comment]
Ohh ok @samuveth then it makes sense 👍🏻
