### ISSUE TITLE
Use eye icon instead of lens for preview markdown

### ISSUE THREAD

**Issue by bigint** [snapshot-labs/snapshot#1248]
<img width="180" alt="image" src="https://user-images.githubusercontent.com/69431456/145746476-39314d83-2fcf-405f-a040-19c542867cea.png">

**Comment by samuveth** [comment]
Yeah seems more intuitive.

**Comment by sasicodes** [comment]
@samuveth What icon name, I should use?

**Comment by samuveth** [comment]
@bonustrack can you find a fitting eye icon for this?

**Comment by bonustrack** [comment]
@samuveth There is a new icon for it on the iconfont project with the id "preview"

**Comment by bigint** [comment]
<img width="1390" alt="Screenshot 2021-12-15 at 5 23 19 PM" src="https://user-images.githubusercontent.com/69431456/146181873-46f75428-463a-46d6-8491-1ce1bef8ab0a.png">

@bonustrack I don't see any here 🙇🏻  https://icofont.com/icons

Can you please send the link over here?

**Comment by samuveth** [comment]
> @samuveth There is a new icon for it on the iconfont project with the id "preview"

Ok, I've sent @sasicodes the files.
