### ISSUE TITLE
Replace mixins with direct imports.

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1256]
Mixins have a lot of down sides: https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html

https://github.com/snapshot-labs/snapshot/blob/develop/src/mixins.ts

This can be replaced by normal module imports.

**Comment by cristijora** [comment]
Another option is to make some of these as global properties.
```js
app.config.globalProperties. _explorer = explorerUrl
```

This won't introduce any breaking changes, meaning the rest of the code shouldn't be changed

**Comment by mktcode** [comment]
That's incompatible with `<script setup>` and also can't be properly handled by an IDE.

https://forum.vuejs.org/t/how-to-use-globalproperties-in-vue-3-setup-method/108387/4

I think a simple import is all you need.
