### ISSUE TITLE
Image upload should accept png files

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1278]
I'm not able to upload a file with .png extension as space avatar

**Comment by bigint** [comment]
@bonustrack I can't reproduce this, am I testing it wrong?

https://user-images.githubusercontent.com/69431456/146365903-bb155b87-5011-4954-923d-ffb91c1ec624.mov

**Comment by mktcode** [comment]
Yep, PNG works perfectly fine. I think those two issues (this and #1279) can be closed. @bonustrack the issue must have been something else.
