### ISSUE TITLE
Need to show valid error messages on creating proposal

### ISSUE THREAD

**Issue by sasicodes** [snapshot-labs/snapshot#1289]
We are now blocking users from creating proposals if some input data is invalid, along with that showing valid error messages about the issue on data will be better UX. 

This helps users to know what they missed out on.
https://www.loom.com/share/25a0206b21224bdd99e2514318741927

- **We can show a red border around invalid data, to highlight it to the user**. (or)
- Disable previously selected date picker to select the right `to` date. (or)
- Showing error messages or notification toast. 

cc @bonustrack @samuveth

**Comment by samuveth** [comment]
Yes I agree this needs to be improved. First step would be to spec out how we want to do validation here, currently it's all handled by a huge `isValid` block. Maybe we want to split this up?

**Comment by samuveth** [comment]
We could also have a schema for this on snapshot.js like we do with settings.

**Comment by samuveth** [comment]
There are only a handful of cases that need to be covered here. We should make a list and create validation logic for those cases and display some information to the user.

**Comment by sasicodes** [comment]
@samuveth How can we show the error messages among mentioned different ways?

**Comment by samuveth** [comment]
We can show it like we show the space validation message here:
![image](https://user-images.githubusercontent.com/51686767/147012969-31d6a179-853c-4856-a85d-7abf96ce8474.png)

**Comment by sasicodes** [comment]
@samuveth We are blocking pointer events for Publish button now. In order to show/trigger the error, should we allow the user to click?

Validations needed for,
- Date
- Title
- Description
- Choices
Add if I missed something.

**Comment by samuveth** [comment]
@sasicodes Yes we should allow click and disable it + show validation message, if there is an error. Should work the same as settings form.

Description is optional.
