### ISSUE TITLE
Not able to read some proposals

### ISSUE THREAD

**Issue by ethedev** [snapshot-labs/snapshot#132]
# Not able to read some proposals
Only on some proposals this issue appears.

Snapshot proposal link:
https://snapshot.page/#/farm/proposal/QmQvoNCNhz5dARMgR82vFPeHAMPqMahHgsHjPYggFuAkGZ
IPFS link:
https://ipfs.io/ipfs/QmQvoNCNhz5dARMgR82vFPeHAMPqMahHgsHjPYggFuAkGZ

**This bug does not relate to https://github.com/balancer-labs/snapshot/issues/131**

<details>
  <summary>Error log</summary>

```
TypeError: Cannot read property 'proposal' of undefined
    at Proposal.vue:204
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```
</details>

**Comment by bonustrack** [comment]
Closing this issue, this is not relevant anymore.
