### ISSUE TITLE
mobile: Can't swipe down to reload page

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1344]
```
body {
  overscroll-behavior-y: none;
}
```
This is preventing swipe down refresh on mobile browsers. I think you added this to prevent over scrolling on macOS @bonustrack ?

**Comment by bonustrack** [comment]
@samuveth Yes if you scroll with trackpad on the homepage the navigation and sidebar left will move a lot if we remove this. Is it possible to remove it only on mobile? And remain the same on desktop

**Comment by samuveth** [comment]
Does someone have an iPhone to test this?

**Comment by samuveth** [comment]
> @samuveth Yes if you scroll with trackpad on the homepage the navigation and sidebar left will move a lot if we remove this. Is it possible to remove it only on mobile? And remain the same on desktop

Yes good idea, I changed that
