### ISSUE TITLE
Add notifications UI

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1351]
We should create a new page "Notification". This page would be accessible from the sidebar left like this:
![image](https://user-images.githubusercontent.com/16245250/146990840-489d11f1-278f-491d-a120-f55aa621d793.png)

This would be similar than Twitter, for the first integration what we need on this page is to load proposals from the joined spaces of the connected wallet (similar than Timeline), but only load the proposals with a start date not more than 1 week ago. Once we've loaded these proposals, we should parse these proposal and separate them in 2 "events", the first event is the start date, and the second event is the end date. This should give us an array of events like this:

```
[
 { time: 12312546, event: 'proposal/end', title: "Proposal 123 to accept grant XYZ" }
 { time: 12311546, event: 'proposal/start', title: "Proposal 748 to do ABC" }
 { time: 12310546, event: 'proposal/start', title: "Proposal 123 to accept grant XYZ" }
]
```
This list of event should be sorted by event time with the most recent in top.

On the page we should display this list showing

- Proposal 123 to accept grant XYZ ended
- Proposal 748 to do ABC started
- Proposal 123 to accept grant XYZ started

**Comment by bigint** [comment]
I'll take this, is figma ready or I need to make my own design?

**Comment by bonustrack** [comment]
@bigint There isn't any design yet, if you want to implement this you can work on the code and not spend time on design, we figure out the design later.
