### ISSUE TITLE
can't vote 

### ISSUE THREAD

**Issue by Qsnh** [snapshot-labs/snapshot#1352]
**Describe the bug**
can't vote

**To Reproduce**
[https://snapshot.org/#/thefilmmakerdao.eth/proposal/0xeae530fea4e6aa7522497ddcf35bdce50818e35d0f6fb11e88925bd61cec181f](https://snapshot.org/#/thefilmmakerdao.eth/proposal/0xeae530fea4e6aa7522497ddcf35bdce50818e35d0f6fb11e88925bd61cec181f)

![image](https://user-images.githubusercontent.com/12671205/147042853-60061b98-0826-4e9d-8350-f4b6875216c4.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome 
 - Version 96.0.4664.110

**Comment by bigint** [comment]
I can reproduce this 👍🏻 

Errors from my console

<img width="1536" alt="Screenshot 2021-12-22 at 11 31 45 AM" src="https://user-images.githubusercontent.com/69431456/147043410-82a4c0d6-3950-4886-a5c7-6ebcd2173f1e.png">

**Comment by samuveth** [comment]
This proposal no longer seems to exist. Feel free to reopen if you are still experiencing this issue!
