### ISSUE TITLE
MetaMask Message Signature: Error: Not supported on this device

### ISSUE THREAD

**Issue by FortisFortuna** [snapshot-labs/snapshot#1360]
**Describe the bug**
Cannot vote with Trezor One hardware wallet.

**To Reproduce**
1. Go to https://snapshot.org/#/frax.eth/proposal/0x8dbda75a6539182e2daef15265b7ecfd06226fed34e2658da9f03e29c20e65be
2. Click on vote
3. Metamask signature prompt pops up
4. Accept the signature
5. Nothing happens, get "Oops, something went wrong" error

**Expected behavior**
The vote goes through

**Screenshots**
![Screenshot from 2021-12-22 13-43-12](https://user-images.githubusercontent.com/33413876/147158862-7d919c40-4fda-4624-856c-178271425cd4.png)

**Desktop (please complete the following information):**
Brave, Metamask 10.8.1, Trezor One 1.10.4

**Comment by ChaituVR** [comment]
Hi @FortisFortuna Try logging out and login again with  "Trezor with metamask" option
https://github.com/snapshot-labs/snapshot/discussions/1189#discussioncomment-1767124

**Comment by defifunk** [comment]
> Hi @FortisFortuna Try logging out and login again with "Trezor with metamask" option [#1189 (comment)](https://github.com/snapshot-labs/snapshot/discussions/1189#discussioncomment-1767124)

I have tried the "Trezor with metamask" option and still faced with the error of "MetaMask - RPC Error: MetaMask Message Signature: Error: Not supported on this device "

**Comment by ChaituVR** [comment]
@defifunk Which version of Trezor are you using? did you try removing cache in your browser?

**Comment by defifunk** [comment]
> @defifunk Which version of Trezor are you using? did you try removing cache in your browser?

hi, thanks for responding. I have cleared cache and still the same. 
here are the 2 browsers that i have tried with "trezor with metamask" option:

trezor firmware: 2.4.3
# test 1
metamask: 10.8.1
chrome: Version 96.0.4664.110 (Official Build) (64-bit)

# test 2
metamask: 10.8.1
firefox: 95.0.2 (64-bit)

**Comment by jasonhuan** [comment]
> Hi @FortisFortuna Try logging out and login again with "Trezor with metamask" option [#1189 (comment)](https://github.com/snapshot-labs/snapshot/discussions/1189#discussioncomment-1767124)

Was able to vote after logging in with "Trezor on metamask".

Info:
– Metamask version 9.8.4 (last version compatible with EIP-1559)
– Firefox 95.0.2 (64-bit)
– Trezor 1.10.4

Had to update my Trezor firmware from 1.10.3 to 1.10.4 to get it working

**Comment by FortisFortuna** [comment]
Worked using "Trezor with Metamask"
