### ISSUE TITLE
Delegation doesn't work on BSC

### ISSUE THREAD

**Issue by sudo-xu** [snapshot-labs/snapshot#1375]
**Describe the bug**
In this contract:
https://bscscan.com/address/0x469788fE6E9E9681C6ebF3bF78e7Fd26Fc015446
the [transaction](https://bscscan.com/tx/0x5cdb42e3f33495eeeffa6f3e9ad5dd1d63a9fd5a96dcf903d1d3c6dbd7ff5138) was successful, but the delegation itself is not valid in space. Not displayed in the list, does not count towards voting

**To Reproduce**
1. Go to https://snapshot.org/#/delegate/snaptest.dexe.network
2. Switch to BSC network
3. Enter address
4. See successful delegation
5. When trying to vote shows the power of the vote 0

**Additional context**
I tried to delegate to BSC earlier, and the result was the same. Only that was another space on the Ethereum mainnet in this [transaction](https://bscscan.com/tx/0xbd25ed504edd1f1dde445d7200f1c691db4dd4fd7334f9a38855a447931f3040)
with included strategy multichain delegation, it worked fine on the Ethereum network.

**Comment by ChaituVR** [comment]
Hi @sudo-xu There was an issue with the BSC subgraph until a few days ago, https://github.com/snapshot-labs/snapshot.js/pull/589 can you reproduce it now?
