### ISSUE TITLE
Autofill the proposal fields from URL query like GitHub

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#1376]
Autofill the proposal fields from URL query like GitHub - will be useful for the communities having a proposal template 

Github example: 
https://github.com/snapshot-labs/snapshot/issues/new?title=Snapshot%20proposal&body=I%20would%20like%20to%20propose%20...

Fields that can be auto-filled based on query params in URL:
- Title
- Description
- Choices
- Voting type
- Voting delay
- Voting period
- Quorum 
- hideAbstain

**Comment by samuveth** [comment]
> * Voting delay
> * Voting period
> * Quorum
> * hideAbstain

We don't have these field on proposal creation.

**Comment by zzuziak** [comment]
Hey @ChaituVR, were there many request for this feature? :thinking: 

Sounds like a great enhancement but we will need to make sure we communicate it to spaces properly. Otherwise we will end up with a great feature which will never be used.
