### ISSUE TITLE
Fix format on subgraph for message hash signed with a Safe

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1381]
On the Snapshot subgraph we store events that come from Safe that use signMessage function (SignMsg event), this is how Safe can sign messages to do vote or create a proposal for example (it require an transaction to be executed). This is the contract being used for sign message https://github.com/gnosis/safe-contracts/blob/main/contracts/libraries/SignMessage.sol 

Here is my PR to add signed messages on the subgraph: 
https://github.com/snapshot-labs/snapshot-subgraph/pull/1

There is an issue currently, the `msgHash` field here: https://github.com/snapshot-labs/snapshot-subgraph/blob/e3fd4d1f6b392973176a9e22423145dd34ce98fa/src/factory.ts#L16

This seem to use a wrong format, when we sync the subgraph it doesn't return the correct hash, I've tested with the Safe 
`0x78E1F985e36A2F5CF3b15a9d7214E71eCaEADFB0` to sign a message, the hash of the message is:

`0xec1297ad2571e580c237f9adba21ab392f522d44468c0604dd06dd787825a54c`

You can see the hash here on the tx 25 https://gnosis-safe.io/app/eth:0x78E1F985e36A2F5CF3b15a9d7214E71eCaEADFB0/transactions/history

But on the subgraph it give different one, you can check it here:
https://thegraph.com/hosted-service/subgraph/snapshot-labs/snapshot?query=Query%20signatures%20for%20a%20Gnosis%20Safe

**Comment by atharva3010** [comment]
Can someone explain to me in https://github.com/snapshot-labs/snapshot-subgraph/blob/e3fd4d1f6b392973176a9e22423145dd34ce98fa/src/factory.ts#L16 why `toHex()` is being used?

**Comment by bonustrack** [comment]
@atharva3010 This issue is solved already, toHex is used to change byte hash to string
