### ISSUE TITLE
Add different requirements (Quorum, Approval Threshold, etc) to different types of proposal on the same SnapShot

### ISSUE THREAD

**Issue by phbrgnomo** [snapshot-labs/snapshot#1383]
**Is your feature request related to a problem? Please describe.**

Each snapshot page allows only one set of parameters (quorum, min amount to create proposals, approval threshold, "authors only") for all the proposals created.

If i wanted to have different settings (i.e. One type of proposal requiring 10k tokens as quorum, and another type of proposal requiring 100k tokens) i would need a different snapshot page, wich would also require another ENS domain cost

**Describe the solution you'd like**

Allow creating different types of proposals inside the same snapshot page.

For example:

Budget Proposal:
- Min Quorum: 100k Tokens
- Time for Voting: 30 days

Small change proposal:
- Min Quorum: 1k Tokens
- Time for Voting: 10 days

That way, when a user wanted to create a new proposal, he would select with type of proposal he want to create, and the requirements would be dependent of that type.

**Describe alternatives you've considered**

Pay a second ENS domain to create a new snapshot page (Extra costs)

**Additional context**

**Comment by zzuziak** [comment]
@bonustrack, what are your thoughts on this?
