### ISSUE TITLE
Custom domain problems

### ISSUE THREAD

**Issue by shunkakinoki** [snapshot-labs/snapshot#1398]
**Describe the bug**

**To Reproduce**
1. Go to https://gov.wagumi.xyz
2. It doesn't to Wagumi dao snapshot page (https://snapshot.org/#/wagumi.eth/)

**Expected behavior**

1. Redirect to wagumi dao snapshot page (https://snapshot.org/#/wagumi.eth/)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shunkakinoki** [comment]
Followed all the steps in https://docs.snapshot.org/spaces/add-custom-domain

**Comment by ChaituVR** [comment]
There is one more PR that needs to be merged, which was merged - should work fine now
