### ISSUE TITLE
SafeSnap transactions not loading

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1402]
https://snapshot.org/#/fabien.eth/proposal/QmV2TVKZmgXHuzT36ockuJ3hwCY31weotgirYTsA18SBDB

![image](https://user-images.githubusercontent.com/6792578/148064180-5e21974e-266d-4fa8-a292-f8808f3affa1.png)

**Comment by carlosfebres** [comment]
I think we can close this issue @mktcode

**Comment by mktcode** [comment]
Sure? It's still not loading. But you are working on this?
