### ISSUE TITLE
IPNS record address is confusing

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#1403]
The address in the ENS text record  (see screenshot) updates to whichever wallet that is connected, one user reported it to be confusing as they are the admin of the space and see their address in the record instead of original address

**To Reproduce**
Try going to https://snapshot.org/#/gitcoindao.eth/settings

**Expected behavior**
Maybe we should hide this section to other people if the space is already having a text record on ENS or should show the correct instructions than "See on ENS"

**Screenshots**
![image](https://user-images.githubusercontent.com/15967809/148181637-cdba6296-0076-4328-b89c-74d8895d72e1.png)
Admin view:
![image](https://user-images.githubusercontent.com/15967809/148181869-a34dd98a-2f42-4e44-86a0-e770e98bac43.png)

**Comment by samuveth** [comment]
Yes, if no wallet or a wrong wallet is connected the `space settings` and the `ENS block` should be hidden if the ENS has a valid text-record. For both cases we might want to show individual messages.

### Wrong wallet connected
Should show a message
`[i] The connected wallet does not appear to be an admin of this space`
### No wallet connected
Currently looks like this
![image](https://user-images.githubusercontent.com/51686767/148186333-e00b863e-29c0-4e82-bc92-42cd7c0bd881.png)
Should show a message and a button
`[i] Please connect your wallet to edit spaces settings` and a connect wallet button below.

**Comment by ChaituVR** [comment]
Space creation flow changed
