### ISSUE TITLE
Remove charts plugin

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1427]
The chart plugin should be removed, the plugin rely on the full list of votes which is only available during the voting period of the proposal. The chart is misleading when proposal ended. It should be made another way.

**Comment by samuveth** [comment]
This can also be closed then https://github.com/snapshot-labs/snapshot/pull/1419

**Comment by mktcode** [comment]
It'll be removed in [`mkt/plugins`](https://github.com/snapshot-labs/snapshot/pull/1469) branch, same as Aragon. (Git history ftw for future reference.)

**Comment by samuveth** [comment]
Was removed in https://github.com/snapshot-labs/snapshot/pull/1469
