### ISSUE TITLE
Remove setTitle from nav

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1438]
We no longer need `setTitle` in the `Topnav` component. This is now handled by `setPageTitle`.

**Comment by RishiKumarRay** [comment]
I would like to solve this , can you guide me

**Comment by samuveth** [comment]
> I would like to solve this , can you guide me

Sure, how can I help?

**Comment by curelycue** [comment]
Hi!
https://github.com/snapshot-labs/snapshot/pull/1449
