### ISSUE TITLE
Cannot vote , ENS all good 

### ISSUE THREAD

**Issue by izkillaz** [snapshot-labs/snapshot#1447]
Deposited 1.5 ENS , ENS still 0 ! 

Voting for FOR! 

izzyfrkz.eth

**Comment by ChaituVR** [comment]
@izkillaz You should have some tokens in your wallet before the snapshot. and should you should delegate your self before the snapshot block to be able to vote on ENS proposals, more details here: https://github.com/snapshot-labs/snapshot/discussions/1015

closing this, feel free to reopen if needed. Thanks

**Comment by izkillaz** [comment]
Ok will do that next time.
