### ISSUE TITLE
Reduce and improve CSS 

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1452]
We should reduce our CSS to Tailwind CSS and make improvements where possible.

Possible improvements:
- We should use flex instead of float in 99% of the cased https://www.quora.com/Should-I-use-Flexbox-floats-or-anything-else-for-my-CSS-layout
- Create and use classed for repeating patterns
- Move to tailwind v3

**Comment by bonustrack** [comment]
We can move to tailwind v3 on the way too
