### ISSUE TITLE
Confusion when connecting with the same wallet but different connector

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1466]
I use the same account on metamask and coinbase wallet, after I connect there is no way for me to see if I'm connected through metamask or my coinbase wallet. I think it would be helpful to show the connector name inside the account modal.
![image](https://user-images.githubusercontent.com/51686767/149724096-acb7027a-b745-49ef-b5b7-6a1590b6fcfb.png)

**Comment by zzuziak** [comment]
@samuveth  Could you show an example of other dapps that display the connected wallet provider? :thinking:

**Comment by samuveth** [comment]
This doesn't seem relevant anymore
