### ISSUE TITLE
Change vue components to use typescript 

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1483]
Add `lang="ts"` to each vue component and fix the errors/warnings that appear.

**Comment by RishiKumarRay** [comment]
Where in code do we have to update that?

**Comment by samuveth** [comment]
> Where in code do we have to update that?

Everywhere, you can start components and then views.

**Comment by jbeBan** [comment]
Hello! I would like to help out with this issue since it looks like your components still haven't been updated to TypeScript yet. Is that good with you?

**Comment by samuveth** [comment]
> Hello! I would like to help out with this issue since it looks like your components still haven't been updated to TypeScript yet. Is that good with you?

Yes, I have assigned you!

**Comment by jbeBan** [comment]
> > Hello! I would like to help out with this issue since it looks like your components still haven't been updated to TypeScript yet. Is that good with you?
> 
> Yes, I have assigned you!

Hey, I'm sorry, but I'm actually not going to be able to help out with this :/ Best of luck.

**Comment by bigint** [comment]
I'll take care of this making a folder wise fixes 🤗
