### ISSUE TITLE
Fix text written in template instead of defaults.json

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1484]
There are some places, like in `Setup.vue` where text has been written in the template instead of added to the defaults.json and then used in the template with `$t('')`.

![image](https://user-images.githubusercontent.com/51686767/150361865-1f762e5f-5fee-4711-b197-4001212ca88c.png)

**Comment by richardsaseun14** [comment]
hello @samuveth can i pick up this Issue?

**Comment by richardsaseun14** [comment]
@samuveth has this been done?

**Comment by samuveth** [comment]
The one in the screenshot yes, but there should be some others if you each file.

**Comment by richardsaseun14** [comment]
@samuveth went through all the files and every possible text has been fixed. couldn't find any.

**Comment by mktcode** [comment]
> every possible text has been fixed.

That's a LIIIIEEE!!! 🤪 😉 

I found some in plugins and by searching for `title="`:

https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/Hal/CustomBlock.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/Form/ContractInteraction.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/Form/ImportTransactionsButton.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/Modal/OptionApproval.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/SafeTransactions.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/Tooltip.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/Aragon/CustomBlock.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/POAP/CustomBlock.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/Quorum/CustomBlock.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/S/DefaultArray.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/TimelineProposalPreview.vue
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Block/Votes.vue

**Comment by richardsaseun14** [comment]
> Challenge accepted!
> 
> > every possible text has been fixed.
> 
> That's a LIIIIEEE!!! 🤪 😉
> 
> I found some in plugins and by searching for `title="` and `label="`:
> 
> https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/Hal/CustomBlock.vue#L31 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/Form/ContractInteraction.vue#L214 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/Form/ImportTransactionsButton.vue#L155-L199 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/Modal/OptionApproval.vue#L90-L93 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/SafeTransactions.vue#L210 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/SafeSnap/Tooltip.vue#L68-L78 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/Aragon/CustomBlock.vue#L63 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/Aragon/Govern.vue#L17 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/POAP/CustomBlock.vue#L160 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Plugin/Quorum/CustomBlock.vue#L47 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/S/DefaultArray.vue#L27 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/TimelineProposalPreview.vue#L131 https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Block/Votes.vue#L141
> 
> Maybe not all of them really need a translation and the Aragon plugin will be removed anyway but that's all I could find.

wow, @mktcode thanks a lot. I was only looking in the snapshot folder, I didn't look in the plugins folder. Thanks and I will look into it.

**Comment by mktcode** [comment]
@richardsaseun14 No problem. Sunday. Had time. :D

**Comment by samuveth** [comment]
@richardsaseun14 also I found `days` and `hours` in `spaceSettings.vue`

**Comment by samuveth** [comment]
Btw @richardsaseun14 please only add it to the defaults.json file and not the other translations files, crowdin will handle the rest.

**Comment by samuveth** [comment]
Also here https://github.com/snapshot-labs/snapshot/blob/1903efe043c28b97f974846a459f9effc050c27e/src/views/Strategy.vue#L34

**Comment by richardsaseun14** [comment]
how I do I get to these pages to preview the changes I have made. I don't seem to know how to navigate to the pages on development

**Comment by mktcode** [comment]
You mean the preview deployments? 

![image](https://user-images.githubusercontent.com/6792578/152364366-851041f9-6776-4d27-a9a7-c0832bb4d422.png)

**Comment by richardsaseun14** [comment]
no i mean when i run the development server:

for example where do i see the contents of 
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Block/Votes.vue on development?

**Comment by mktcode** [comment]
Btw... for PRs you are still working on, you can use the draft feature.

https://github.blog/2019-02-14-introducing-draft-pull-requests/

![image](https://user-images.githubusercontent.com/6792578/152365156-dd1993d0-a148-4826-84dd-9cb6ef7e4a12.png)

**Comment by mktcode** [comment]
> no i mean when i run the development server:
> 
> for example where do i see the contents of https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Block/Votes.vue on development?

Hmm well, I guess that will get better and better over time. :D But maybe the Vue devtools can help with that. I haven't used them in a while but they can be quite helpful.

**Comment by richardsaseun14** [comment]
okay thanks i will use that to debug better. I have also converted the pull request to a draft

**Comment by mktcode** [comment]
Sry, I was a bit confused. I know now what pain you mean. Working on something from a pure code perspective and then you don't know where to look for the changes. Not sure how dev tools should help with that. xD That's actually a documentation issue. Each component should have some comment heade giving a brief summary of its purpose and location in the UI.

**Comment by richardsaseun14** [comment]
okay i will. thanks
