### ISSUE TITLE
Workspace admins can edit user comments 

### ISSUE THREAD

**Issue by RickVM** [snapshot-labs/snapshot#1500]
**Describe the bug**
Workspace admins can edit the comments of other users, this should not be possible. 
I was able to add a second exclamation mark to a comment which was made [here](https://snapshot.org/#/dcip.eth/proposal/0xd1fcfa6f7d0b855c454bbd06ba220f658da38f42263b625ed344f122f9f24fc7)

**To Reproduce**
1. Go to a workspace in which you are an admin and commenting is enabled
2. Have a random user create a comment
3. As an admin scroll to the comment, and edit it as you prefer
4. See the edit

**Expected behavior**
User comments should not be editable by anyone except for the user that made it.
Being able to do this goes against web3 principles, and allows gives room for unwanted behavior

**Screenshots**

**Desktop (please complete the following information):**
macOS Chrome

**Comment by metrox-eth** [comment]
@spiritbro1 Hey mate, hope you're doing good, can you look into this ?

**Comment by spiritbro1** [comment]
@metrox-eth sorry im a little bit busy up until 10 february, but let me check a little bit if it's not possible for me to fix then im sorry

**Comment by metrox-eth** [comment]
@spiritbro1 Sure, just let me know. Thx bro

**Comment by mktcode** [comment]
See also: https://github.com/snapshot-labs/snapshot/issues/1550

**Comment by zzuziak** [comment]
As this plugin will be deprecated, I'm closing the issue :pray:
