### ISSUE TITLE
Add image upload in the editor

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1504]
We can add a footer with "Add image(s)", and when you click on it you are triggered to upload an image similar than space avatar, then add the image within the post body. The url should be in this format: ipfs://QmeZAvVPKZ... and we should turn this url to a https:// ipfs gateway url
![image](https://user-images.githubusercontent.com/16245250/150796297-d8d035b8-d733-4fe8-b857-47d420feee5d.png)

Also we can add a markdown icon similar than GitHub with a tooltip "Styling with Markdown is supported" with this link https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by midgerate** [comment]
Two more things needed

1. Add ability to drag and drop image to upload
2. Add ability to copy paste the image to upload.
