### ISSUE TITLE
Approval voting - can send vote without choice selected

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1537]

**Comment by mktcode** [comment]
This behavior is intentional: https://github.com/snapshot-labs/snapshot/commit/dac29e60b142218c896bb8d7c9a084892110924e

@bonustrack is it still?

cc @bigint

**Comment by samuveth** [comment]
Oh yes, it seems to be intentional thanks @mktcode and sorry @bigint

**Comment by samuveth** [comment]
@bonustrack could you briefly explain why we want to allow this? I can barely remember anything regarding this 😅

**Comment by bonustrack** [comment]
@samuveth This was for some ENS constitution proposal to allow person to vote but for none of the choice

**Comment by mktcode** [comment]
So that's technically an abstain option, right? Could we make this a bit clearer maybe?
