### ISSUE TITLE
Transaction indicator not removed when navigating

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1549]
After executing a SafeSnap transaction and then navigating away from that proposal page, the loading indicator stays there forever, defying the main purpose of this indicator. Not sure if that only applies to safesnap (then it would be my personal fault :D) or in general.

![image](https://user-images.githubusercontent.com/6792578/151599608-0ba6c7cd-0ba7-4d20-9ec4-a2a5f7beca0a.png)

**Comment by samuveth** [comment]
@mktcode I just tested it on the Delegation page and I switched to the Home page while it was loading. When the transaction was confirmed the loading bar also disappeared
