### ISSUE TITLE
Unable to vote with Ledger through Brave wallet

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1575]
**Describe the bug**
A user reported he is unable to vote with Ledger through Brave wallet

**To Reproduce**
Vote with Ledger through Brave wallet

**Expected behavior**
I've tested with my Ledger and Metamask, no issue, should be related to Brave.

**Comment by samuveth** [comment]
This seems to be an issue with Brave, on our side I don't see any errors
