### ISSUE TITLE
Settings menu item not accessible without adding admin address in settings

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1576]
Current behavior
A recurring support issue is that space controllers can't find their settings, now they need to know the setting page URL.
Adding the controller address to the settings admin field is needed to be able to see the settings menu item in the space.

Proposed behavior:
Upon space creation the controller address is added automatically.

Context:
The proposed behavior does not entirely solve the problem, some users are distracted, postpone the registration of their ENS waiting for lower gas fees or any other reason, when they finalize the registration later they have no idea how to get back to the settings URL.

**Comment by mktcode** [comment]
Maybe we can utilize localStorage to show a "Continue space setup" link somewhere.

**Comment by metrox-eth** [comment]
> Yep. I'd just pre-fill the form field.

Great ! Thx

> For the second scenario maybe we can utilize localStorage to show a "Continue space setup" link somewhere.

It will do the trick until we polish the entire space creation process

**Comment by mktcode** [comment]
> Great ! Thx

Did you maybe confuse "I'd" with "I'll". Was just a suggestion but if you want I can take care of it. 🤪

**Comment by metrox-eth** [comment]
> Did you maybe confuse "I'd" with "I'll". Was just a suggestion but if you want I can take care of it. 🤪
haha yes
