### ISSUE TITLE
Infinite loading on delegation page with Polygon network

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1582]
Steps:
- Go to balancer.eth space and connect to polygon network on metamask
- Click delegate in sidebar
- See page stuck on infinite loading

Ui Version: `0.1.4#1903efe`

Console error:
![image](https://user-images.githubusercontent.com/51686767/151947656-a6083b04-b3ec-4749-8221-baeddec040ac.png)

**Comment by mktcode** [comment]
Can't reproduce. Is this fixed already?

**Comment by midgerate** [comment]
@samuveth you working on it?

**Comment by samuveth** [comment]
> @samuveth you working on it?

No, working on other issues
