### ISSUE TITLE
Space About page should display social links if configured in the settings.

### ISSUE THREAD

**Issue by midgerate** [snapshot-labs/snapshot#1595]
UI 
![image](https://user-images.githubusercontent.com/91108642/152128242-c0567806-3454-4d7a-9ad9-5cd67fedd944.png)

@bonustrack to approve the design

Social Links to allow
Twitter - Take user name
Github - Take username / organization 
Discord- Take discord id (the one after discord.gg/)

**Comment by mktcode** [comment]
Suggestion:

![image](https://user-images.githubusercontent.com/6792578/152132494-78517111-d093-4bc1-b5b4-c1f7bbdaa8e9.png)

**Comment by bigint** [comment]
I'll take care of this 🤗

**Comment by bigint** [comment]
Please assign this to me, so i'll pick when the design is ready 🙇🏻

**Comment by mktcode** [comment]
I'm not too sure about my suggested design/location. It should look somewhat good even with only one icon. I think the about page might be the better place, less prominent of course though. Would still like to hear an opinion from @bonustrack.

We also had a website property in the settings once (according to some relics in the code at least). Maybe that's actually worth being added back, having up to four icons then.

![image](https://user-images.githubusercontent.com/6792578/154931369-4ba7324a-0796-4211-a7c2-0ad976e98bb5.png)
With those not set grayed out maybe.
![image](https://user-images.githubusercontent.com/6792578/154931663-ae8b2b88-99db-494d-bb2c-c95f70a0787c.png)

Or... simply:
![image](https://user-images.githubusercontent.com/6792578/154932431-c3391fe1-55c6-4415-8135-c5ae7607b55f.png)
Or maybe:
![image](https://user-images.githubusercontent.com/6792578/154933128-654f9846-d40c-4ded-98ba-6e88213d30d1.png)

**Comment by mktcode** [comment]
@mykcryptodev I just realized that this issue was already assigned to @bigint. It's really better to not start putting time into something that's already assigned, without commenting first to clarify things. Also your PR at first was pretty much the same as [the one we closed](https://github.com/snapshot-labs/snapshot/pull/1607) before, for the mentioned reasons.

So... even your PR now implements my last suggestion and maybe that will be what we go with (idk yet), I will close it now and give the preference to @bigint.

In the meantime I'll think about how we can improve our communication to make things more clear.

**Comment by mykcryptodev** [comment]
> @mykcryptodev I just realized that this issue was already assigned to @bigint. It's really better to not start putting time into something that's already assigned, without commenting first to clarify things. Also your PR at first was pretty much the same as [the one we closed](https://github.com/snapshot-labs/snapshot/pull/1607) before, for the mentioned reasons.
> 
> So... even your PR now implements my last suggestion and maybe that will be what we go with (idk yet), I will close it now and give the preference to @bigint.
> 
> In the meantime I'll think about how we can improve our communication to make things more clear.

That’s fine. I asked in discord what the etiquette was for working on things that have been assigned already. I had some free time and figured I’d get my feet wet with issues that looked like good first issues. Sorry for stepping on toes. I’ll keep my eye out for other opportunities

**Comment by mktcode** [comment]
So we decided for this version:

![image](https://user-images.githubusercontent.com/6792578/156537516-c3d54fc5-a3bc-4465-8cf1-0e4a1d37813e.png)

Fields for discord and website will also be added to the settings.

**Comment by midgerate** [comment]
Not adding any new social media. Just implement the design.

**Comment by midgerate** [comment]
@samuveth @mktcode demo. 

https://www.loom.com/share/39ae56876629495b8fa4e13143c9e825

**Comment by mktcode** [comment]
If we keep the icons that are not set, they should be a lot lighter I think, like almost invisible.

![image](https://user-images.githubusercontent.com/6792578/157007986-729011a2-6cd7-4ef1-afd4-e988e7790285.png)

But I'm not sure if I still like my own suggestion. :D Maybe they should just not show at all if not set and if none are set, no footer.

**Comment by samuveth** [comment]
> If we keep the icons that are not set, they should be a lot lighter I think, like almost invisible.
> 
> ![image](https://user-images.githubusercontent.com/6792578/157007986-729011a2-6cd7-4ef1-afd4-e988e7790285.png)
> 
> But I'm not sure if I still like my own suggestion. :D Maybe they should just not show at all if not set and if none are set, no footer.

Just grayed out is fine for me, but could be lighter yes 😸
