### ISSUE TITLE
Able to add duplicate authors in settings

### ISSUE THREAD

**Issue by bigint** [snapshot-labs/snapshot#1609]
**Describe the bug**

Able to add duplicate authors in settings

**To Reproduce**
1. Go to settings and add the same address multiple times in authors
2. Click save

**Expected behavior**

Remove duplicates

**Screenshots**

<img width="634" alt="image" src="https://user-images.githubusercontent.com/69431456/152181748-543e03f1-a807-4daa-b845-140ad1e1f63f.png">

![image](https://user-images.githubusercontent.com/69431456/152183256-76310ede-2a19-489f-b36d-38e2440ead20.png)

**Comment by bigint** [comment]
cc @samuveth @bonustrack 

I'll take care of this

**Comment by bigint** [comment]
Also this should be taken care in backend, anyone can intercept data directly to backend

**Comment by mktcode** [comment]
good catch!
