### ISSUE TITLE
Future must be in plural for years in date

### ISSUE THREAD

**Issue by bigint** [snapshot-labs/snapshot#1611]
**Describe the bug**

Future must be in plural for years in date

**To Reproduce**
1. Create a proposal and set date to 2024
2. Check the proposal date
3. It will show in singular for years that is more than one

**Expected behavior**

It could display `4 yrs`

**Screenshots**

![image](https://user-images.githubusercontent.com/69431456/152189005-f3ba4405-97df-464a-8907-caa0de806645.png)

![Screenshot 2022-02-02 at 9 25 16 PM](https://user-images.githubusercontent.com/69431456/152189278-c458241a-0d0d-4b05-8ad3-b33021242eb2.png)

![image](https://user-images.githubusercontent.com/69431456/152190329-f04725e0-896c-421d-b731-bd2c481dcdac.png)

**Comment by mktcode** [comment]
That's all handled by the Intl API: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat

Should be fine.
