### ISSUE TITLE
Handle 500 errors if the user don't have ens avatar

### ISSUE THREAD

**Issue by bigint** [snapshot-labs/snapshot#1613]
![image](https://user-images.githubusercontent.com/69431456/152190053-649b27aa-beab-4d24-9808-3bae5d1213cc.png)

**Comment by samuveth** [comment]
There doesn't seem to be a way to handle this. Anyway I've made an improvement to how the component is loading the images here https://github.com/snapshot-labs/snapshot/pull/1616
