### ISSUE TITLE
Snapshot spaces doesn't load in Vietnamese language

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1614]
**Describe the bug**
Vietnamese language break the UI
**To Reproduce**
Change language to Vietnamese

**Comment by samuveth** [comment]
![image](https://user-images.githubusercontent.com/51686767/152278515-681fca7e-4470-4a8f-b30a-3e7252c0a24d.png)
Works for me. Any more steps to reproduce?

**Comment by metrox-eth** [comment]
Does the spaces load for you ?
<img width="1399" alt="Capture d’écran 2022-02-03 à 10 54 12" src="https://user-images.githubusercontent.com/55286013/152278719-d2cf0f3e-b30a-426e-8faa-ee80d00c02ed.png">

**Comment by samuveth** [comment]
I think I found the issue you where having. ☝️ PR opened
