### ISSUE TITLE
Bring back the feature to download all votes as an CSV file

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1626]

**Comment by samuveth** [comment]
Anything blocking this @bonustrack

**Comment by rootial** [comment]
Does this feature exist previously? @samuveth

**Comment by bonustrack** [comment]
@samuveth What is blocking here is that it require loading all the votes, for some proposal with lot of votes it take too long to resolve and fail, it need to be loaded on demand with some kind of pagination (not all at once), probably better if it's done by an external server instead of having this logic on the UI.

@rootial Yes

**Comment by samuveth** [comment]
@bonustrack got it.

@rootial not sure when it was removed. I couldn't find the code anymore. Basically what we need is a button below the results the allows the user to download all the votes with voting power to an CSV file. What might be a bit difficult is (like Bonustrack mentioned) we need a way to on demand and not all in one single request.

**Comment by mktcode** [comment]
But what's the issue with that? They can be loaded chunks, like in the votes block. (maybe more than 10 per chunk though :D)
Can take a while until everything is fetched but so what? If we have the total number of votes it could show a progress bar.

Btw: https://github.com/snapshot-labs/snapshot/commit/b7ec107658e74361b951304f709f152fefdc75b1

**Comment by samuveth** [comment]
Yes, was also thinking something like a progress bar.

**Comment by zzuziak** [comment]
Hey @bonustrack, do you think we can implement this for Snapshot and SX? We had some requests recently mentioning that the votes were cut at 6K.

**Comment by samuveth** [comment]
@zzuziak cut at 6k when downloading?

**Comment by ChaituVR** [comment]
Yes, this is because we now have a limit for the `skip` param. it is limited to 5k
So users can download only 6k votes

But we can use this technique to get all votes https://discord.com/channels/707079246388133940/1061540232769577061/1061540232769577061

**Comment by wa0x6e** [comment]
I'll take this on
