### ISSUE TITLE
Misaligned tooltips in votes list

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1632]
![ezgif-6-87aece837b](https://user-images.githubusercontent.com/6792578/152370819-10ebd671-dfb6-46e4-bcc2-4d64ec70badb.gif)

**Comment by bigint** [comment]
<img width="417" alt="Screenshot 2022-02-03 at 8 48 31 PM" src="https://user-images.githubusercontent.com/69431456/152371581-ea0e4365-0bc3-4a45-99fd-5f009d6bf291.png">

this seems like causing because of truncate

**Comment by bigint** [comment]
@mktcode I've created a PR here https://github.com/snapshot-labs/snapshot/pull/1633
