### ISSUE TITLE
Vote amounts shown are rounded

### ISSUE THREAD

**Issue by john-light** [snapshot-labs/snapshot#165]
**Is your feature request related to a problem? Please describe.**
The vote amounts shown are rounded.

**Describe the solution you'd like**
Show the exact vote amounts.

**Describe alternatives you've considered**
If you hover over the rounded number (or press on the rounded number if on mobile) it can show the exact vote amount in a tooltip.

**Additional context**

![Screenshot_2020-11-20 Aragon](https://user-images.githubusercontent.com/9424721/99830813-3a346600-2b2c-11eb-8a6d-87ffebd205f4.png)

![Screenshot_2020-11-20 Aragon(1)](https://user-images.githubusercontent.com/9424721/99830831-3f91b080-2b2c-11eb-9ee9-00fce944a130.png)

**Comment by samuveth** [comment]
@bonustrack We could show the exact amount in the receipt modal, what do you think? 
![image](https://user-images.githubusercontent.com/51686767/111907757-54a23000-8a89-11eb-891b-f48ba8c609fb.png)
