### ISSUE TITLE
Voting popup vanish without alert when VP calculation fail

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1662]
**Describe the bug**
Voting popup vanish without alert when VP calculation fail

**To Reproduce**
Vote here:
https://snapshot.org/#/superumans.eth/proposal/0x7b5671ec730ee4a88102f9d727785fc8e08ca563013a26dc68e86b23854c0581

**Expected behavior**
An alert should be displayed

**Additional context**
The behavior also happened a few days ago on another proposal.

**Comment by samuveth** [comment]
Can't reproduce. The proposal you linked doesn't load at all for me.

**Comment by metrox-eth** [comment]
> Can't reproduce. The proposal you linked doesn't load at all for me.

I think I have captured a video of the issue, does it help if I share it ?

**Comment by metrox-eth** [comment]
@samuveth 
https://youtu.be/ix-Jz_CPUjg

**Comment by samuveth** [comment]
Hmm, not really :)

**Comment by mktcode** [comment]
Probably the same as here: https://github.com/snapshot-labs/snapshot/pull/1671

I'll take care of handling it properly.
