### ISSUE TITLE
Wrong strategy is added to proposal, not present in settings nor IPFS

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1670]
**Describe the bug**
Wrong strategy is added to proposal, not present in settings nor IPFS. Erc20-balance-of should no be added to new proposal since it's not present in the settings or IPFS 
https://cloudflare-ipfs.com/ipfs/QmQF7hCbtmcwrw8k77Q5YxxQRdY9q4hcXALixsazVRuaJQ:
<img width="672" alt="Capture d’écran 2022-02-09 à 07 01 30" src="https://user-images.githubusercontent.com/55286013/153096320-a5fa8e8f-2976-4980-a487-883c39811723.png">
<img width="342" alt="Capture d’écran 2022-02-09 à 07 03 07" src="https://user-images.githubusercontent.com/55286013/153096367-3e617b57-d37d-41a1-a456-91cb274c248f.png">

**To Reproduce**
Here is the space concerned:
https://snapshot.org/#/metabrands.eth/

**Comment by samuveth** [comment]
Open the multichain strategy and see params ;)

**Comment by bonustrack** [comment]
What you mean @samuveth ?

**Comment by bonustrack** [comment]
The strategies used on a proposal are the ones from the space settings when the proposal is creates, its not the strategies from the proposal payload you see on IPFS (this feature was deprecated). Maybe settings was changed after proposal creation that would explain the difference.

**Comment by metrox-eth** [comment]
I have tried with the user to solve this without success, we tried to create multiple new proposals, and this ghost ERC20 strategy is still applied.

**Comment by metrox-eth** [comment]
New case today here:
https://snapshot.org/#/blu3dao.eth/proposal/0xd74766fee7064be71dedc4514aa49d703f43820ad5bd09da706f1d104d71f92b
![](https://cdn.discordapp.com/attachments/747049240022482974/941170470458380298/unknown.png)

![](https://cdn.discordapp.com/attachments/747049240022482974/941170564666654771/unknown.png)

**Comment by ChaituVR** [comment]
This should be fixed as we are using space strategies now
