### ISSUE TITLE
info icon about voting power is dead link

### ISSUE THREAD

**Issue by goblinscash** [snapshot-labs/snapshot#1727]
The info icon relative to voting power on the voting submission page leads to a deleted discussion on github. This shows when connected to a wallet with 0 voting power. Currently links to https://github.com/snapshot-labs/snapshot/discussions/1015#discussioncomment-1599447 

![image](https://user-images.githubusercontent.com/95008586/154108588-c6ad4735-72f8-41fd-8edd-210673398c2e.png)

**Comment by mktcode** [comment]
Good catch! Thanks!
