### ISSUE TITLE
Add tooltips to settings

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1743]
**Is your feature request related to a problem? Please describe.**
Many users are confused in the settings, we should add tooltips for at least:
- Strategies (limitations and that Vp is cumulative)
- Admins (say that you should add the controller as admin to see settings menu and delete a proposal)
- Threshold
- Quorum
- Skin (say that it require custom domain)

**Describe the solution you'd like**
Adding tooltip with a brief hint onhover

**Describe alternatives you've considered**
The tooltip can also be a link to the doc with an anchor to right section, but a real tooltip is more strait forward.

**Additional context**
This suggestion is based on recurring question and feedback on helpdesk

**Comment by zzuziak** [comment]
Majority of these is solved, a bigger rework is coming when it comes to the error messages and tooltips :pray:
