### ISSUE TITLE
Request sent to null

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1751]
When you are on snapshot logged, on the network tab i can see request being sent to load image at this url snapshot.org/null
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/16245250/154490891-aa1d52f6-a06d-4aa7-9510-b0c660ad4fbc.png">

**Comment by mykcryptodev** [comment]
@samuveth can you assign to me please

**Comment by mykcryptodev** [comment]
are we sure this issue can still be reproduced? I'm having difficulty doing so

**Comment by bonustrack** [comment]
@mykcryptodev Are you trying while being logged?

**Comment by samuveth** [comment]
@bonustrack @mykcryptodev this is a bit tricky because I don't think anyone is able to reproduce this locally.

**Comment by mktcode** [comment]
Can't even find it in production anymore.
