### ISSUE TITLE
[Bug - Mobile] Missing duplicate proposal button and share button is partially displayed

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#1752]
**Describe the bug**
Missing duplicate proposal button and share button is partially displayed on mobile (refer screenshot) when screen size less than 420px

**To Reproduce**
1. On your mobile go to [a proposal](https://snapshot.org/#/ens.eth/proposal/0x42605fa85d059459f7072aeaeea4cd14ada78e15d9aa1998fe99634a75f9f5a6)

**Expected behavior**
Should be responsive and these buttons should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/15967809/154497562-fc3a1097-499d-4c46-a198-649020f84ab1.png)

**Comment by ChaituVR** [comment]
> Since we don't prioritize mobile support for the web UI, maybe we should add some note.

But why? 😅 everything else works great on mobile (except a few things) we should have a fix until there is an App available, we can ignore but only this part doesn't look nice when someone wants to see a proposal on mobile (everything else in this page is responsive)

**Comment by mktcode** [comment]
I personally am a friend of mobile first design anyway, and using all the modern stuff, progressive web app and these nice buzzwords.. offline first, etc.. I was simply told the web app isn't supposed to support mobile/small screens. And if that is the case, imho it would be better to support nothing (and telling the user) instead of "this and that". If that's not the case... I need to do some testing on my phone.

**Comment by samuveth** [comment]
It is the case for a lot of things. Voting and proposal page not being one of them IMO 😺

**Comment by mktcode** [comment]
Then I suppose "duplicate proposal" should not be visible?

**Comment by ramprakashram** [comment]
Can i take up this issue ??

**Comment by ramprakashram** [comment]
@samuveth Will this UI work ???
![image](https://user-images.githubusercontent.com/31797738/154913348-a6630b3d-34d3-4e7b-be68-68fee31023da.png)

**Comment by mktcode** [comment]
Ok, I got enlightened now. Full support is actually the goal. Sorry for my saltiness. 🙈 But then this should be a bit better aligned.

I suggest moving the dropdown menus to the top and and truncating the author name if needed. Also I think there's a more common share icon we could use.

![image](https://user-images.githubusercontent.com/6792578/154975352-fd847ed3-f00c-472e-a56b-75ea960f3eea.png)

**Comment by ramprakashram** [comment]
@mktcode Got it, will update accordingly. Thanks.

**Comment by mktcode** [comment]
@ramprakashram I think you should wait a bit still. This is still just a suggestion. I'm now thinking about moving that violet proposal state label somewhere else now. Maybe that will be better.

**Comment by ramprakashram** [comment]
@mktcode Sure, let me know once you are finalised on the design. 😀

**Comment by mktcode** [comment]
Btw @bonustrack @ChaituVR [This one](https://github.com/snapshot-labs/snapshot/issues/1752#issuecomment-1043011357) was of course not meant to solve this issue but as an additional information for users, that mobile support is currently not at 100% and some features might be missing/inaccessible. I still think that's a good idea. Some dismissable note that's only shown once.

**Comment by mktcode** [comment]
Or...
![image](https://user-images.githubusercontent.com/6792578/154981792-56b83b02-2b98-4160-a516-e1fd9aa1c7f3.png)

![image](https://user-images.githubusercontent.com/6792578/154982525-d3e41df9-ed3b-4d17-842c-89a942062a47.png)

I think that's the best and simplest.

**Comment by samuveth** [comment]
@mktcode Yes, looks like the best solution to me

**Comment by mktcode** [comment]
@ramprakashram

![makeitso](https://user-images.githubusercontent.com/6792578/155118777-b36dcb09-7bd7-413f-a6da-7ffd3a869a68.gif)

**Comment by ramprakashram** [comment]
@mktcode 
![Yes](https://media.giphy.com/media/l4KhU4ummixvPZlcs/giphy.gif)

**Comment by ramprakashram** [comment]
@mktcode Can I hide the Avatar, as if i keep the Avatar in Mobile view, the UI Looks very crowded ?
![image](https://user-images.githubusercontent.com/31797738/155275081-85812aff-2323-4fb7-801c-67499ab2959d.png)

**Comment by mktcode** [comment]
I was thinking about that too you'll have to use truncate (tailwind class) for the username anyway. I think it's ok then.

**Comment by samuveth** [comment]
Yes, I also think the space avatar is more important.

**Comment by ramprakashram** [comment]
@mktcode The name is already truncated being truncated by the `shortenAddress` utiity function.

**Comment by mktcode** [comment]
Hmmm yea with actual addresses it's a bit tricky. Usually you don't want hardcoded lengths but css based truncating because it's more flexible. But if you combine it with this utility function you'll end up with something like `0x123...78...` which doesn't look nice.
Maybe it should render the address twice. Once shortened with `shortenAddress` for desktop, and one shortened with css on smaller screens.

**Comment by ramprakashram** [comment]
@mktcode I have updated the UI as you suggested and raised a PR.
![image](https://user-images.githubusercontent.com/31797738/155331236-261969b1-9a0e-4384-b1f1-2a4f9a6a212b.png)
