### ISSUE TITLE
Treasury plugin idea

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1795]
Make a plugin where you can define a list of address like Safes as plugin params and display a page treasury with the balance for each of these address on differents tokens, see example:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/16245250/154970850-1455d2dc-1078-4532-95bc-8d0b88178c71.png">
You can use Multicaller for this example:
```
import { onMounted, ref } from 'vue';
import { formatUnits } from '@ethersproject/units';
import snapshot from '@snapshot-labs/snapshot.js';
import networks from '@snapshot-labs/snapshot.js/src/networks.json';

const balances = ref({});
const loading = ref(false);

const { getProvider, Multicaller } = snapshot.utils;
const network = '1';
const provider = getProvider(network);
const abi = [
  'function getEthBalance(address addr) public view returns (uint256 balance)',
  'function balanceOf(address account) view returns (uint256)',
  'function decimals() view returns (uint8)',
  'function name() view returns (string)',
  'function symbol() view returns (string)'
];

const tokens = [
  '0xba100000625a3754423978a60c9317c58a424e3D',
  '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
  '0xDe30da39c46104798bB5aA3fe8B9e0e1F348163F',
  '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
];

const treasury = '0x10A19e7eE7d7F8a52822f6817de8ea18204F2e4f';

onMounted(async () => {
  loading.value = true;
  const multi = new Multicaller(network, provider, abi);
  const base = {
    ether: {
      name: 'Ether',
      symbol: 'ETH',
      address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    }
  };
  multi.call('ether.balance', networks[network].multicall, 'getEthBalance', [
    treasury
  ]);
  tokens.forEach(token => {
    multi.call(`${token}.balance`, token, 'balanceOf', [treasury]);
    multi.call(`${token}.name`, token, 'name');
    multi.call(`${token}.symbol`, token, 'symbol');
    multi.call(`${token}.decimals`, token, 'decimals');
  });
  balances.value = await multi.execute(base);
  loading.value = false;
});
```

**Comment by samuveth** [comment]
@bonustrack Nice idea, but how do we know what tokens to check for?

**Comment by bonustrack** [comment]
@samuveth We can take a list from here https://tokenlists.org

**Comment by ChaituVR** [comment]
and also, we can add input fields in plugin settings to get the custom token's balance?

**Comment by mktcode** [comment]
The plan is to add a menu item to the space sidebar.

![image](https://user-images.githubusercontent.com/6792578/155110491-13b14ef5-8047-4ec2-ab49-2c14c3b5951c.png)

The plugin system currently doesn't support that and there's a [bit of work to do](https://github.com/snapshot-labs/snapshot/pull/1717) prior to that. And then, such a functionality would require a few things like additional routes and so on.

I'm a little bit concerned about the differentiation of what's a plugin and what's core. In the end, many of snapshot's features are optional, which is kind of what plugins are too. You could think of each strategy as a "plugin". You know what I mean? So far, plugins have been extending only the proposal page. I'd love to extend that to other places to. But I also see a distant future where like everything is a plugin and we just successfully rebuilt existing Vue features.

**Comment by sherodtaylor** [comment]
^ @mktcode the custom space pages is a great idea. I was just looking to see if it's supported there is a lot you can do with it

**Comment by bonustrack** [comment]
Closing this issue, this was integrated as a core feature.
