### ISSUE TITLE
Add option to add sub-space(s) on space settings

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1797]
We should have a way to define sub-spaces on the space settings, then when opening a space page it should load proposals from all the defined sub-spaces too, giving a view of all proposals. We should have also link to subspace on top of the space page

**Comment by mktcode** [comment]
Maybe also a filter similar to proposal state?

**Comment by bonustrack** [comment]
@mktcode Yes but maybe we can make it look different, we could use the sub space image and add it on top similar to instagram 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/16245250/155008179-28d0f919-1477-4232-bee2-8e4f7604705f.png">

**Comment by bonustrack** [comment]
We could also add a way to set a single parent space, when set a space would like to his parent space so you can navigate within the org spaces back and forth

**Comment by mktcode** [comment]
What about ENS ownership? Will that be the limiting factor? Child/parent-spaces need to belong to the same account or something like that?

**Comment by midgerate** [comment]
Requires Specs - Excalidraw

**Comment by mktcode** [comment]
I'll start working on this now.

What is an expected number of sub-spaces on average? I assume mostly just 1, sometimes 2-3, maybe up to 5 in some rare cases? Can the UI be planned with these numbers in mind (let's say 5 max) or should there be a solution that works regardless of the number of sub-spaces?

What about sub-sub-spaces/deeper nesting? Shall we support that or can the UI just assume to show _either_ a child _or_ a parent but never a space that is both at the same time?

**Comment by samuveth** [comment]
> @samuveth can you write down and explain the signing logic you suggested?

I suggest we think about this more after we have refactored settings page and space creation.
