### ISSUE TITLE
Loading Error: /apy.eth

### ISSUE THREAD

**Issue by CodeSlip** [snapshot-labs/snapshot#1806]
**Describe the bug**
Our snapshot page is not opening up

**To Reproduce**
1. Go to 'https://snapshot.org/#/apy.eth)'
2. The page opens, but the proposals are not loading

**Expected behavior**
The page loaded, with a list of proposals

**Screenshots**
![image](https://user-images.githubusercontent.com/14955011/155167563-38fc5517-0772-4312-8177-7d0ccba39d8f.png)

**Desktop (please complete the following information):**
 - OS: OSX Big sur
 - Browser Chrome
- Version: 98.0.4758.102 (Official Build) (x86_64)

**Additional context**
It was working fine into the end of last week.

**Comment by mktcode** [comment]
Interesting.... For me it shows up after some time but with this error:

![image](https://user-images.githubusercontent.com/6792578/155187182-93b1cfa9-fc5c-41d1-9650-d21af78b20b6.png)

I'll have a look.

**Comment by mktcode** [comment]
Seems to be a bug in one of our dependencies: https://github.com/stiang/remove-markdown/issues/52
I'll submit a workaround.
