### ISSUE TITLE
Add filter to timeline for spaces that the user follows and hasn't voted on yet

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1863]

**Comment by zzuziak** [comment]
We already display the `Voted` badge. Would you say it solves the problem?

![image](https://user-images.githubusercontent.com/39556343/217348660-9ba66f5e-cdd9-4cda-ba02-f108fdfd62f7.png)

**Comment by samuveth** [comment]
Yes and no, but using notifications can help with this too. Closing this as we don't have a clear idea for timeline yet.
