### ISSUE TITLE
Default avatar not showing correctly in Brave

### ISSUE THREAD

**Issue by noahliechti** [snapshot-labs/snapshot#1864]
**Describe the bug**
Default avatars are not show correctly in Brave. If a space has set its own avatar the image is shown. In Safari everything worked fine.
Page reloading, clearing cache and restarting the browser didn't help.
After a few hours the avatars were displayed correctly in Brave.

**To Reproduce**
1. Go to Brave
2. Open snapshot.org

**Expected behavior**
Images for all avatars should be shown correctly

**Screenshots**
Safari:
<img width="1262" alt="Screenshot 2022-02-28 at 19 46 17" src="https://user-images.githubusercontent.com/38284563/156479790-7ecf9632-57ab-4943-85f0-d0a0e632c86f.png">

Brave:
<img width="1440" alt="Screenshot 2022-02-28 at 19 42 49" src="https://user-images.githubusercontent.com/38284563/156479802-b8b0b704-1b14-4fba-96f9-cde46055ecb9.png">

**Desktop (please complete the following information):**
 - OS macOS Big Sur Version 11.6
 - Browser brave
 - Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)

**Comment by samuveth** [comment]
Works fine for me on Brave.

Desktop:
macOS Monterey Version 12.1
Brave Browser Version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (arm64)

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/51686767/156499165-f8532146-9691-4420-875d-b87e62fabd55.png">

**Comment by noahliechti** [comment]
could it be a problem of stamp.fyi?

**Comment by bonustrack** [comment]
Stamp use webp image, maybe related? You can try open this and see if that works

**Comment by noahliechti** [comment]
I get: `This site can’t provide a secure connection`
