### ISSUE TITLE
Using Snapshot voting for contract balance release

### ISSUE THREAD

**Issue by kyokosdream** [snapshot-labs/snapshot#1875]
### Background

We've released a rough draft for a community governed ERC721(A) contract on our Github under the [voting](https://github.com/Candy-Labs/CandyContracts/blob/voting/README.md) branch.

It demonstrates an example of allowing token holders to vote on allowing the contract owner to release funds. It does so by preventing token transfer and minting during the voting period. It uses the first 8-bits of the ERC721A uint64 aux variable to track the last proposal voted on by the user (for preventing double-voting) and uses the last 56-bits for the whitelist mint slots.

The first 8 bits allow encoding up to 0-255 proposals but we only allow a maximum of 100 in the current implementation. We use the decimal value 101 as a special case to track whether the refund has been claimed.

README
https://github.com/Candy-Labs/CandyContracts/blob/voting/README.md

We want to integrate with Snapshot for gasless voting which will lead to greater voter participation and ease the ability to reach a quorum. 

### Question

How can we make contract functions (on-chain) dependent on the voting results of a Snapshot proposal? We only see a way for requesting the voting results via Snapshot.js or GraphQL API. Do we need something like an oracle? How can this be achieved?

**Comment by mktcode** [comment]
There's SafeSnap, which uses the [Reality.eth oracle](https://reality.eth.link) with a gnosis safe.
https://docs.snapshot.org/plugins/safesnap

For the future we plan to implement a more generalized core feature, so you don't have to use a plugin.

For now the only other option is to write our own implementation. I was thinking about adding a Chainlink plugin for example.
https://docs.snapshot.org/plugins/create

**Comment by kyokosdream** [comment]
We've moved our implementation to on-chain voting but we'll try to integrate this solution soon.

**Comment by mktcode** [comment]
I'll close this issue then. Feel free to reopen or open a new one when needed. :)
