### ISSUE TITLE
Refactor button component

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1882]
Problem:
Currently we have 3 different input and button height: `42, 44 and 46px`and we also have icon buttons that are about 30px in height. Also there is a lot of logic for buttons spread out across our code which increases difficulty of adding new features and components.

Solution:
We should have a base button that includes all of the base logic and styling of all our buttons. For very specific buttons we should create separate button components that are based on base button.

**Comment by samuveth** [comment]
@mktcode feel free to pick this one up too :)

**Comment by samuveth** [comment]
Sidebarbutton component also seems to deserve a better name, it's used in so many places outside of the sidebar

**Comment by mktcode** [comment]
![image](https://user-images.githubusercontent.com/6792578/157456888-440e8a40-244e-4615-b6fa-87155103f0f1.png)

Already on it.

:D
