### ISSUE TITLE
Modal should not have minimum height

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1884]
Currently if you open the modal where there isn't much information it create a large empty space like this:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/16245250/156917726-85b838b9-2eca-45d6-aca4-82f39bf6d239.png">
We shouldn't have this min height on the modal to remove this empty space

**Comment by samuveth** [comment]
> Currently if you open the modal where there isn't much information it create a large empty space like this: <img alt="image" width="619" src="https://user-images.githubusercontent.com/16245250/156917726-85b838b9-2eca-45d6-aca4-82f39bf6d239.png"> We shouldn't have this min height on the modal to remove this empty space

@bonustrack This would create a second scroll when the network selector dropdown is open. We should instead increase the default size of the Textarea inside this modal.

**Comment by samuveth** [comment]
I think we should make some wireframes and try some things out before we make a decision here.
