### ISSUE TITLE
Network dropdown selector border

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1885]
These borders
<img width="494" alt="image" src="https://user-images.githubusercontent.com/16245250/156917819-b8bbda14-c0fe-4138-adb1-a05c14dd118a.png">
Should look like this
<img width="440" alt="image" src="https://user-images.githubusercontent.com/16245250/156917898-7a0839e2-755b-4993-adf7-66e8f7404b93.png">

**Comment by Qsnh** [comment]
what page path?
