### ISSUE TITLE
Safesnap amounts setting not consistent with UI input

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1906]
A user report TX amounts not consistent with UI input
![image](https://user-images.githubusercontent.com/55286013/157258966-ffb13aeb-57ee-4afb-831b-35e44dd50a1a.png)
![image](https://user-images.githubusercontent.com/55286013/157259000-2e45c09c-78e0-46ff-ae4f-eeb50b06685e.png)

**Comment by ChaituVR** [comment]
Link to the proposal: https://snapshot.org/#/kittyparty.eth/proposal/0x3d004a387cb9e777eaa87694a00a914fcd3e7741e462fdf9f134f1e1daf15a57

Discord:
https://discord.com/channels/707079246388133940/747049240022482974/950642754092949536

My notes:
Something is wrong with transaction data and its hashes, the hash is null
https://cloudflare-ipfs.com/ipfs/Qmcsw9P3RXJdTSMxpiNbhvoRpMdoiepq7w7JeF5GJYCAPf
User says they were using snapshot UI only

**Comment by mktcode** [comment]
cc @carlosfebres

**Comment by carlosfebres** [comment]
I'll take a look at this, thanks for reporting

**Comment by mktcode** [comment]
I remember there was some change in how values are displayed in Safesnap recently but can't find the pull request.

**Comment by metrox-eth** [comment]
![image](https://user-images.githubusercontent.com/55286013/157583728-5c855999-c36c-426e-8c54-321346b4a802.png)
I think Matic USDT is 6 decimals

**Comment by ndtvkp** [comment]
https://github.com/snapshot-labs/snapshot/blob/develop/src/plugins/safeSnap/utils/coins.ts
 need to update at line 13 18 -> 6

**Comment by metrox-eth** [comment]
PR here: https://github.com/snapshot-labs/snapshot/pull/1920

**Comment by metrox-eth** [comment]
> https://github.com/snapshot-labs/snapshot/blob/develop/src/plugins/safeSnap/utils/coins.ts need to update at line 13 18 -> 6

Thanks good catch

**Comment by carlosfebres** [comment]
@metrox-eth I created [this PR](https://discord.com/channels/707079246388133940/747049240022482974/950642754092949536) to fix this issue.
Unfortunately, another proposal with these transactions will need to be created.

**Comment by ndtvkp** [comment]
> @metrox-eth I created [this PR](https://discord.com/channels/707079246388133940/747049240022482974/950642754092949536) to fix this issue. Unfortunately, another proposal with these transactions will need to be created.

yeah. I will create another proposal. let me know when it deployed
