### ISSUE TITLE
Unsubscribing using the notification bell doesn't remove the items in the notification dropdown

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1907]
Unsubscribing using the notification bell doesn't remove the items in the notification dropdown
![image](https://user-images.githubusercontent.com/55286013/157267530-3f8db7d9-9e6f-42fe-be8b-10a35358b3e2.png)

**Comment by samuveth** [comment]
We will add settings to the notifications in the future. Will probably be around the time we introduce user profiles :)
