### ISSUE TITLE
[Feature] Symbol field for strategy settings

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#1909]
As discussed here https://github.com/snapshot-labs/snapshot-strategies/pull/431#issuecomment-1060377135

We need a way to input strategy symbols like the new network field in strategy settings, which will send strategy like this:
```
{
  "name": "ticket",
  "symbol": "ABC",
  "network": "1",
  "params": {}
}
```

**Comment by zzuziak** [comment]
Hey @ChaituVR what's the status on this issue?
