### ISSUE TITLE
Set Outcome fails silently if you don't have enough to cover the bond

### ISSUE THREAD

**Issue by auryn-macmillan** [snapshot-labs/snapshot#1914]
### Expected behavior
If you have insufficient balance to cover the bond, the "yes" and "no" buttons should be disabled with a hover tooltip that says "insufficient {token} to set outcome".

### Actual behavior
You can press either button and it fails silently with a browser console log about a gas estimation error.

### Steps to reproduce the behavior
Try to set the outcome in a space where you have insufficient balance to cover the minimum bond.

**Comment by bonustrack** [comment]
Closing this issue, it was transferred on snapshot-labs/snapshot

**Comment by samuveth** [comment]
@mktcode can we close this?
