### ISSUE TITLE
Failed to cast Votes 

### ISSUE THREAD

**Issue by Githugutech** [snapshot-labs/snapshot#1959]
The votes do not tally. Some of the users have votes but they don't have any points.

**Comment by metrox-eth** [comment]
Please provide context:
What's the space
Which is the proposal concerned
Who are the users, how they sign messages (Wallet, hardwallet, browser, ...)

**Comment by Githugutech** [comment]
> 

There are 4 participants ( BrodaGreen, Hellen Musyoka
, Irene, and Yvonne Kagondu) but only the 1st 2 participants have points Currently there are 39 votes but only 36 have been counted.

**Comment by samuveth** [comment]
We can't help if proper context isn't provided. Feel free to reopen if needed.
