### ISSUE TITLE
Can not set snapshot block number

### ISSUE THREAD

**Issue by running-swap** [snapshot-labs/snapshot#1977]
**Describe the bug**
When creating a new proposal, the snapshot block number cannot be modified.

**To Reproduce**
1. Go to [https://snapshot.org/#/developer-kcc.eth/create](url)
2. Click on 'continue'
3. No **snapshot** option
<img width="1217" alt="result" src="https://user-images.githubusercontent.com/88641386/159500484-2af803b4-adfc-4150-99bd-ec2c01c43560.png">

**Expected behavior**

Hope the snapshot block number can be modified like the [https://bafybeigwl42c5h2rnjd4ek5okmm3wtrbtntriwfbm4jsndfqcs3rawkaiq.on.fleek.co/#/developer-kcc.eth/create](url)

**Screenshots**
<img width="1217" alt="expect" src="https://user-images.githubusercontent.com/88641386/159500397-0c519640-41c6-4659-98aa-cc4801d096b9.png">

**Comment by samuveth** [comment]
@bonustrack aren't we always using the timestamp now with `blockfinder`, will changing the snapshot even have an effect anymorea?

**Comment by bonustrack** [comment]
@running-swap Are you looking to set a block number in future? Can you describe what is your use case?

@samuveth Changing snapshot has effect, we aren't using timestamp yet
