### ISSUE TITLE
Make sidebar take less space on mobile

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1978]
To save space on mobile while still making the sidebar accessible we can it horizontal (idea credits: @bonustrack).

Here's a first suggestion:

![image](https://user-images.githubusercontent.com/6792578/159506252-9edc27f0-d973-4859-af69-f3e76a366b3f.png)

Maybe this can be collapsible or only show on timeline page?

**Comment by samuveth** [comment]
Seems like a good idea at first, but to have a collapsible sidebar would give us more options and flexibility in the long term. On mobile we can replace the "snapshot" with a burger menu on the left side of the navbar.

**Comment by mktcode** [comment]
What do you mean with more options and flexibility? Because there's more space vertically than horizontally?

**Comment by samuveth** [comment]
This will always be visible so we will always want to keep as small and possible. But with a collapsible sidebar there is a lot more available space. Like now you added the timeline to the navbar (which is already questionable) what if we have other features like search we want to add.

**Comment by samuveth** [comment]
I think the sidebar menu will eventually have a size like this 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/51686767/159644504-2844c205-1940-474d-8110-63bf590f1b63.png">

**Comment by mktcode** [comment]
Hm... yea. I agree actually.

btw... can't we ask our database what's the average number of followed spaces?

**Comment by samuveth** [comment]
I don't think so, would definitely be interesting although as more things become a DAO users will join/follow more DAO's over time.
