### ISSUE TITLE
Strategies in proposal should display network information

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#1980]
If a strategy has a network,
- Strategies in the proposal should display network info 
  Go to https://snapshot.org/#/lyra.eth/proposal/0x7240756548266a71c0c59fb86801c791ae9ff151e2c2a3da195fd562ab7e9174
  the strategies modal should contain network information 
![image](https://user-images.githubusercontent.com/15967809/159535405-636c92f3-1de9-427f-8874-37b249cc08af.png)

- On click of playground link, the playground should select strategy's network instead of space's network

**Comment by rootial** [comment]
do you mean we should display the network if network id of strategy exist? @samuveth 
```
{
    "name": "cake",
    "network": "56",
    "params": {
        "symbol": "CAKE",
        "address": "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82",
        "decimals": 18
    }
}
```

**Comment by bonustrack** [comment]
@rootial Yes, and if the strategy does not include a network we should show the space network

**Comment by rootial** [comment]
i notice some strategy with params which contain nested strategies in it.
Should we dig into the params and use the network in it? @bonustrack   
```
{
    "name": "multichain",
    "network": "1",
    "params": {
        "symbol": "avaxAAVE+avAAVE",
        "strategies": [
            {
                "name": "erc20-balance-of",
                "params": {
                    "address": "0x63a72806098bd3d9520cc43356dd78afe5d386d9",
                    "decimals": 18
                },
                "network": "43114"
            },
            {
                "name": "erc20-balance-of",
                "params": {
                    "address": "0xd45b7c061016102f9fa220502908f2c0f1add1d7",
                    "decimals": 18
                },
                "network": "43114"
            }
        ]
    }
}
```

**Comment by bonustrack** [comment]
@rootial No, here you should only show network 1
