### ISSUE TITLE
Show network in strategies modal on proposal page

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#1991]
We should show the network here and use it for the exploreUrl (not it take the network for the space and fail)

![image](https://user-images.githubusercontent.com/6792578/159873952-54107da5-b55a-443a-b481-387d3ca734df.png)

**Comment by mktcode** [comment]
@bonustrack copied this from the other issue... I don't understand: "(not it take the network for the space and fail)". You can edit above and delete this comment.

**Comment by ChaituVR** [comment]
@mktcode Refer this https://github.com/snapshot-labs/snapshot/issues/1980
