### ISSUE TITLE
Sidebar improvements

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#2006]
Suggestions:
- auto-collapse on click on space
- darken content when sidebar expanded
- fix menu/close icon position
- maybe even remove "snapshot" from navbar

**Comment by mktcode** [comment]
Currently there's also the logo in the sidebar, doing the same. The functionality to go back to the homepage should of course stay. But the design can be improved.

**Comment by hjjlxm** [comment]
Oh right! just checked twice, the navbar!  I will withdraw my statement. What I was referring to is not removing the ⚡ logo
Yes, since the logo and “snapshot” doing the same, that's a fair point if we don't need a showing of word form "snapshot"
