### ISSUE TITLE
“Internal Server Error” when coming to last step of configuring DNS

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#2034]
**Describe the bug**

As instructed in https://docs.snapshot.org/spaces/add-custom-domain, the user has finished setting CNAME and get his PR merged,

There'll be an error taking place frequently in the last activation process when user hits :https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=example.com

Showing a msg of "Internal Server Error", with the custom domain directing to the homepage of snapshot, rather than the specific space

This cannot be solved by hard refreshing the activation page, while the resolution status shows normal at DNS provider side.

**Expected behavior**
Should we add a line in the official doc if this issue is typically dependent on snapshot's side to do some other merging job.

Current doc indicates after merging and activation, the user can access their space with their custom domain immediately.
![error msg](https://user-images.githubusercontent.com/31681895/160638959-caeaf95d-6f94-4de1-a638-af4dc745d651.jpg)

**Comment by bonustrack** [comment]
@hjjlxm Are you using CloudFlare? If yes, can you try remove the orange cloud and hit the url again?

**Comment by hjjlxm** [comment]
Nope. And checked that my provider doesn't have a proxy setting. @bonustrack 
Maybe it has something to do with my dns not fully resolved? I'm not certain cuz the resolution status shows normal
(Or I can just wait another 24hr to see if it works)

**Comment by hjjlxm** [comment]
update: still not working up to now.

**Comment by hjjlxm** [comment]
The issue is under improvements, will close it and expect refactor. https://github.com/snapshot-labs/snapshot/issues/2203
