### ISSUE TITLE
Custom Domain Not working

### ISSUE THREAD

**Issue by singularityhacker** [snapshot-labs/snapshot#2087]
**Describe the bug**
I have stepped through the steps to set up a custom domain and it is not working. 
Instructions: https://docs.snapshot.org/spaces/add-custom-domain

**To Reproduce**
Navigate to "vote.ParticleDAO.xyz"

**Expected behavior**
I should see this page when navigating to "vote.ParticleDAO.xyz": https://snapshot.org/#/particledao.eth

**Screenshots**
1. Domain set in snapshot settings: https://imgur.com/ja7mAYA
2. Domain added to json: https://imgur.com/ReTtBvC
3. DNS set: https://imgur.com/apQETZV

**Additional context**
Navigating to vote.ParticleDAO.xyz takes me to the main snapshot landing page and not my individual DAO page.

**Comment by ChaituVR** [comment]
Issues with snapshot build
