### ISSUE TITLE
ENS domain loading not working for all domains

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#2088]
Seems the solution implemented here: https://github.com/snapshot-labs/snapshot/pull/2010 doesn't work for all domains.

In this case (owner: 0x76eCe6825602294b87A40d783982D83bB8EBcAf7) the second query does not return anything.

![image](https://user-images.githubusercontent.com/6792578/161586257-58cab077-b2c6-41c7-8512-683a95aaeb03.png)

Therefore the hashes are displayed and the next step doesn't work:

![image](https://user-images.githubusercontent.com/6792578/161585684-3e7f3288-4f74-4f9c-9c8a-0f30cf6bf503.png)

**Comment by mktcode** [comment]
Re-opening since we should find a solution for this.

**Comment by ChaituVR** [comment]
But I can't reproduce this anymore with guest?? 🤔 Is the owner wallet correct? `0x76eCe6825602294b87A40d783982D83bB8EBcAf7`
![image](https://user-images.githubusercontent.com/15967809/174233566-8ecea9f3-f453-4a29-ab17-9174d6196d52.png)

I tried the ENS subgraph too, with the ENS hash and it works fine there too

![image](https://user-images.githubusercontent.com/15967809/174233653-c14d3ca1-a63a-4b0e-a302-183fc4d7380c.png)

Maybe it is just a temporary issue?

**Comment by ChaituVR** [comment]
I am able to reproduce it with this address 

https://app.ens.domains/address/0xa2e81c205e38324bf7432aecbd2c7e20c717e1d3/controller

But the even ENS app is showing `This name is invalid.` so there is not much we can do in this case

**Comment by mktcode** [comment]
Maybe we can at least show a note and ask the user to enter the domain manually.

**Comment by zzuziak** [comment]
Hey @samuveth what's your take on this issue, shall we display the note with a hint?

**Comment by samuveth** [comment]
@ChaituVR is this still an issue that comes up lately?

**Comment by ChaituVR** [comment]
Most of time when ever this happens, ENS APP shows `This name is invalid.` So I think there is nothing we can do. Maybe we can add some message that says an invalid name or something, instead of an unknown string like in the above screenshot

**Comment by zzuziak** [comment]
Good idea @ChaituVR, let's also display a hint on our side that there is an issue with the ENS name :pray:

**Comment by ChaituVR** [comment]
@samuveth Can take care of this?

**Comment by samuveth** [comment]
@ChaituVR yes, will work on it
