### ISSUE TITLE
Vote disappeared after proposal is closed

### ISSUE THREAD

**Issue by michjun** [snapshot-labs/snapshot#2096]
**Describe the bug**
When the proposal was active, my wallet had voting power and I casted the vote successfully. I can see my vote and it was reflected in the "current result" section. However, after the proposal is closed, my vote disappeared in the end result. At the "votes" section for the ended proposal, I can see the wallet has casted vote, but the voting power became 0. I can see I definitely have voting power at the snapshot block from the voting strategy playground (it is using erc20-balance-of-delegation).

**Expected behavior**
My vote shouldn't have disappeared.

**Screenshots**
Before proposal closed:
<img width="388" alt="Screen Shot 2022-03-28 at 7 08 07 PM" src="https://user-images.githubusercontent.com/378771/161864008-6b9c6118-9d09-4404-863b-904440958e1e.png">

After proposal closed:
<img width="321" alt="image (38)" src="https://user-images.githubusercontent.com/378771/161864127-ca960b4c-c9d7-4811-ae60-e1cc2ce2fb57.png">
<img width="630" alt="Screen Shot 2022-04-05 at 2 01 03 PM" src="https://user-images.githubusercontent.com/378771/161864050-655dc187-9c23-47ae-ad86-6bc75aa80bd6.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome
 - Version 99.0.4844.84

**Additional context**
The voting power was delegated from another wallet and the proposal was using weighted voting, I voted across several different options with percentage.

**Comment by ChaituVR** [comment]
Hi @michjun For `erc20-balance-of-delegation` your delegators can take back their voting power if they vote on the proposal, https://snapshot.org/#/strategy/delegation

So if you think your delegators didn't vote, let us know your address and proposal you are trying to vote, (can send in discord too) will take a look

**Comment by mktcode** [comment]
If that's the case, we should still think about how to better reflect this in the UI. I'd be confused too.
