### ISSUE TITLE
Custom domain bugs

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#2115]
1. Three dot menu doesn't work and should not show on custom domains. 

2. Notifications button doesn't work and should not show on custom domains.

<img width="226" alt="image" src="https://user-images.githubusercontent.com/51686767/162354769-058cfa39-7598-4bb0-9263-7ba99fa3873a.png">

**Comment by mktcode** [comment]
Assigned myself just so that it's in someones issue list and actually... maybe I'm gonna fix it in lunch break. :D
