### ISSUE TITLE
Add a hint about UI needs a few minutes to reflect the delegation status

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#2121]
The UI needs a few minutes to reflect the delegation status should we add a hint about this delay ?

Context:
RabbitHole added a new task that involve delegation and they have complaints that snapshot delegations doesn't work, although it's just a delay for the delegation to appear in the UI. Adding a hint could solve the problem and prevent question at both Snapshot and RabbitHole support.

**Comment by hjjlxm** [comment]
What's the standard of showing addresses under the "Top Delegation" section? @samuveth 
![123](https://user-images.githubusercontent.com/31681895/162413649-d52b2a69-bb81-483d-b5c8-d97f04f429f3.jpg)

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/issues/2743
