### ISSUE TITLE
Web UI errors

### ISSUE THREAD

**Issue by e-zine** [snapshot-labs/snapshot#2122]
This error (in the screenshot) occurred when you click the Join button on the home page https://snapshot.org/#/

Joined 4 groups in a row

![16bb1c153e](https://user-images.githubusercontent.com/58560910/162422709-ee93c298-0d3c-4d7e-85e9-62f91c20367d.jpg)

**Comment by mktcode** [comment]
Thanks. This error was actually shown inside the of the UI?

**Comment by e-zine** [comment]
Yes, on front page

**Comment by mktcode** [comment]
Ok, we identified the issue. But can you tell me what browser you are using? This error message should not be visible in the UI.
