### ISSUE TITLE
Defining the space role of "admin" on proposal creation

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#2123]
**Background**
For now, only the address put in the "author" list will be defined as **core** member of the space and with the space controller who can propose without the restriction of the voting power.

How logically does this Hierarchy of Authority make sense ?
Authority: Controller ＞admin＞author

Controller decides who will be the admin, and the admin with controller can decide who will be the author.
So naturally the admin has the power to bypass the token restriction himself

**Expected behavior**
The admin can propose without the proposal threshold restriction

**Comment by samuveth** [comment]
Yes this could be better described. We have some plans for refactoring the settings, I will add this issue to the milestone. https://github.com/snapshot-labs/snapshot/milestone/3

**Comment by zzuziak** [comment]
@samuveth would you be up for scoping this issue? Is it mainly about clear communication about each role?

**Comment by samuveth** [comment]
@zzuziak we do this already, 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/51686767/217824631-950e86b6-193f-4ba1-9372-d30a1bb6f948.png">

**Comment by ChaituVR** [comment]
This is not completed. what @hjjlxm means here is the Hierarchy of the roles we have, Right now admin/controller can't create proposals if they are not the author,

To reproduce, go to space settings, add an address only in admins and not authors, Then enable "Allow only authors to create proposals" in proposal validation, then try to create a proposal with this admin address, It will display:
![Untitled](https://user-images.githubusercontent.com/15967809/218089956-680ecef6-8057-4612-a841-a007046b3311.png)

What @hjjlxm mean is admins and controllers should have that access to create proposals based on Hierarchy

**Comment by samuveth** [comment]
I vaguely remember that @bonustrack told us why it should be like this. Not sure if it was this exact case though.

**Comment by bonustrack** [comment]
@samuveth Not remember this, I think we can give admin the ability to post same as author permission. Ideally instead of having 2 sections admin and authors (and later 3 with moderators) we should have a single section with a toggle to select if someone is author moderator or admin, similar as in GitHub https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh0Ks-tD-n5Y3Mhk4yoN5NBHCS2pNQUFZ0RQ&usqp=CAU

**Comment by samuveth** [comment]
@bonustrack for this can we have a format like this on the hub?

```json
"members": [
{
  "address": "0x1...",
  "roles": ["admin"]
},
{
  "address": "0x2...",
  "roles": ["admin", "author"]
},
]
```

**Comment by bonustrack** [comment]
@samuveth If admin role include author permission I'm not sure we need a way to select multiple role per member. And I think its better to not change the format for the moment
