### ISSUE TITLE
Checking if 0 VP voters qualify to vote on future proposals (if they hold)

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#2134]
**Is your feature request related to a problem? Please describe.**
"Why I can't vote ?" is the most recurring support issue, and we get so used to it that we not notice it anymore. 

**Describe the solution you'd like**
How complicated will it be to check if VP is 0 at the snapshot and non null at one of the latest block, we could have a message like: You've got the token after the proposal was posted. You can't vote on this one but will be able to vote on future proposals if you still hold that token.

**Describe alternatives you've considered**
At least users should not have to go to Github to have a hint on why they have 0 VP. 

**Additional context**
[GitHub discussion](https://github.com/snapshot-labs/snapshot/discussions/767)

**Comment by hjjlxm** [comment]
For now if a user doesn't have a voting power (0 VP), there will be 2 icons directing to the GitHub Q&A page, which is a double kill.

Suggest to keep only the exclamation icon when 0 balance detected and have a concise hovertip focusing on how "snapshot"

![0VP](https://user-images.githubusercontent.com/31681895/163439948-b3f24a4e-3287-4882-8a83-a5f438654f62.jpg)

**Comment by zzuziak** [comment]
We are already displaying a more informative error:

![image](https://user-images.githubusercontent.com/39556343/217350587-b6b893f3-e15f-4b2b-a804-544c61e0cd3b.png)


Plus this issue can be solved with #1113, updated FAQ and documentation  :pray:
