### ISSUE TITLE
Can't identify the winner of this RCV proposal cuz of shortened options labels 

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#2147]
**Describe the bug**
With the current UI on web and the way they wrote their vote options, you can't actually see which options are winning (mobile works, though)

**To Reproduce**
1. Go to (https://snapshot.org/#/shellprotocol.eth/proposal/0xfd975ce20e1884b77535c59e08c5df115379d1a774e4cecbe8728968927c9a08)
2. See error

**Expected behavior**
We could have at least a tooltip on the result label

**Screenshots**
<img width="1586" alt="Screen_Shot_2022-04-11_at_9 59 08_PM" src="https://user-images.githubusercontent.com/55286013/162890579-8dde8b7e-6aa9-4b51-8cc1-bf45a969154d.png">

 - Browser Chrome on Mac OS, resolution 2560 x 1600. Default zoom, default system text size.

**Comment by mktcode** [comment]
> We could have at least a tooltip on the result label

Not a final design but a suggestion to somehow make more room for the text as well. Values could be left aligned, or only percentage at the top, tokens at the bottom. Idk. Maybe a tooltip is enough.

![image](https://user-images.githubusercontent.com/6792578/162901894-829aab77-bfd5-4268-822e-67c431468c96.png)
