### ISSUE TITLE
Space controller loses "settings" control from the UI when eliminate himself from admin list

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#2154]
**Describe the bug**

As a successor to https://github.com/snapshot-labs/snapshot/issues/2123

By definition, 

```
Controller
The controller of space can edit the space settings including admins.

Admins
The admins can edit space settings (except the admins list) and archive proposals.

```
The controller doesn't have to be admin himself so as to edit space settings.

The same applies to space control handover, one doesn't need to add B address as admin first, just simply reset the controller to B, and B will be able to change the space settings.

**Expected behavior**

Distinguish the power btw controller and admin. The controller should be able to edit space without being in the admin list.
This should apply to a regular or a gnosis safe space in an overall meaning.

The fix will improve a lot on the community organization building. @bonustrack

**Comment by samuveth** [comment]
@hjjlxm The space controller is always able to edit the space settings. We just don't show the settings button in the sidebar because it is heavy to query the space controller from the text record each time someone visits the space page. You can manually navigate to the settings like this `https://snapshot.org/#/<space>/settings`

**Comment by samuveth** [comment]
I've also added this to the milestone.

**Comment by hjjlxm** [comment]
Thanks for your attention! @samuveth I'm clear as space controller I can still access the settings thru the above url.
Don't get it so much why if put in the admin list will alleviate the pressure while still retaining the controller's power. 
Just feel weird from an UX perspective and the role logic.  Assuming we could be better on how UI shows it.

**Comment by samuveth** [comment]
Yes agreed, we are planning on putting lots of work into the settings in the near future. Thanks for the feedback!
