### ISSUE TITLE
[Bug] ENS displayed not necessarily resolving to address of connected wallet.

### ISSUE THREAD

**Issue by bh2smith** [snapshot-labs/snapshot#217]
I noticed today what appears to be a bug with the way ENS names are displayed for connected wallets. It is my guess that the ens domain appearing for the connected wallet is the first (in alphabetical order) which appears in the connected wallet's "owned" ENS names. However, this assumes that the controller of the domain is also the account which the name resolves to (which is not always the case).

## Illustrative Example
 Address 0x1 controls two ens domains `abc.eth` and `xyz.eth`. While `xyz.eth` resolves to `0x1`, `abc.eth` resolves to a different address `0x2`. When logged into `snapshot.page` with `0x1` the displayed ens domain is `abc.eth`. 

## Concrete Example

This address controls three ENS domains https://app.ens.domains/address/0x7f01D9b227593E033bf8d6FC86e634d27aa85568

1. bahman.eth
2. bensmith.eth
3. bh2smith.eth

Only two of which resolve to the controller address. The first (in alphabetical order) resolves to another address, but is the one displayed in the snapshot interface when connected with the controller address.

<img width="208" alt="Screenshot 2021-01-22 at 13 37 43" src="https://user-images.githubusercontent.com/11778116/105491700-03f39e00-5cb7-11eb-9908-bd0ab27d3640.png">

**To Reproduce**
1. Get an EOA with two ENS domains
2. Resolve the first (in alphabetical order) to a different account
3. Resolve the second to controller account
4. Go to snapshot.page and connect with wallet from step 1
5. See the weirdness.

**Expected behavior**
Would expect that at least one of the correct ENS domains is shown. More precisely, that the reverse record is shown:

https://etherscan.io/enslookup-search?search=0x7f01d9b227593e033bf8d6fc86e634d27aa85568

**Desktop:**
 - OS: macOS
 - Browser Firefox & Brave

**Comment by bonustrack** [comment]
Closing this issue, this has been fixed previously it should now only show reverse record, if you still experience problem with it feel free to reopen this issue.
