### ISSUE TITLE
Your voting power could not be calculated. 

### ISSUE THREAD

**Issue by sirlupinwatson** [snapshot-labs/snapshot#2182]
**Describe the bug**

While trying to cast my vote, I am getting this message:

Your voting power could not be calculated. This is often due to a misconfigured strategy or an unresponsive RPC node involved in the strategy.

**To Reproduce**
1. Go to 'Snapshot.org'
2. Click on 'Cast your vote'
3. See error

**Expected behavior**
I should be able to see my voting power and cast my vote on a proposal

**Screenshots**
![Snapshot](https://user-images.githubusercontent.com/55941045/163408066-57b53acf-41bd-473a-be24-5e7168162188.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 home 21H2 19044.1645 Windows Feature Experience Pack 120.2212.4170.0
 - Browser Firefox
 - Version 99.0.1 (64-bit)

**Comment by metrox-eth** [comment]
What's the proposal you try to vote on ?

**Comment by sirlupinwatson** [comment]
This one here: https://snapshot.org/#/gitcoindao.eth/proposal/0x77b9cfe4130db0c852394b66991248ed5305c0a495639878338ce2a6c568f8f0

**Comment by sirlupinwatson** [comment]
I just tried it again and now it worked... Pretty weird...

**Comment by metrox-eth** [comment]
Thanks for the feedback

**Comment by Parpasiholog** [comment]
I have the same problem, and not long ago I used another uptosbridge bridge and it also didn’t let the transaction pass, it didn’t let me confirm it, and in this it was a temporary bug and changed the time on my computer and it worked, but here I’m changing the time and still it doesn’t work yet I will try further

**Comment by ChaituVR** [comment]
Hi @Parpasiholog Can you provide more details? would be nice if you can create a ticket here https://discord.snapshot.org/
