### ISSUE TITLE
Add better visual indication of selected choices in approval voting

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#2198]
Currently only the border color changes. A check mark icon could be added as well.

![image](https://user-images.githubusercontent.com/6792578/163682934-a49d7f5f-b218-4c40-9049-cff0d4f15c4b.png)

**Comment by zzuziak** [comment]
Already implemented:

![image](https://user-images.githubusercontent.com/39556343/217350995-3457bfa2-209b-41c1-97d0-6fd771f503ac.png)
