### ISSUE TITLE
Add scroll to top

### ISSUE THREAD

**Issue by rootial** [snapshot-labs/snapshot#2201]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It's hard to go to the top of page right now if you scroll down multiple times. I have to refresh the page to do this.
**Describe alternatives you've considered**
A scroll to top button fixed in right bottom of the page 
or when user click the header, the page can scroll to top.

**Additional context**

**Comment by Himnashu** [comment]
@rootial  A scroll to the top button will be good. Let me know if that works I can add this. Making full header clickable will create many issues in future.
