### ISSUE TITLE
"Internal Server Error" when trying to activate domain

### ISSUE THREAD

**Issue by GamiumWorld** [snapshot-labs/snapshot#2205]
**Describe the bug**
Custom domain vote.gamium.world has been added to domain.json and approved. All steps instructed at https://docs.snapshot.org/spaces/add-custom-domain have been completed, but when calling to  https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=vote.gamium.world the server answers with {"message": "Internal server error"}

**To Reproduce**
1. Just execute https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=vote.gamium.world

**Comment by mktcode** [comment]
Hey! W are discussing [possible improvements](https://github.com/snapshot-labs/snapshot/issues/2203). I assume the issue right now is that we have an additional deployment step, so the updated domain list is not immediately "live". But not sure about this.
