### ISSUE TITLE
Implement Shutter private voting

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#2206]
This will require a new voting type that we can call "shutter". With this solution we would encrypt vote choice until a proposal is closed, here is how to encrypt and decrypto a choice using Shutter SDK:
https://github.com/shutter-network/shutter-wasm-example

**Comment by ChaituVR** [comment]
Any specific reasons to use Shutter SDK? It is just encryption with a private key right? why not use keccak256 or similar hashing? 
also, how are we going to handle private voting on GraphQL API ?

**Comment by samuveth** [comment]
@ChaituVR I think there is a bit more that shutter does. You can read more about it here https://blog.shutter.network/announcing-shutter-governance-shielded-voting-for-daos/

**Comment by mktcode** [comment]
@ChaituVR It's about encryption, not hashing. You need to be able to decrypt the vote again.
GrpahQL would just return an error message when querying still encrypted votes, right?

**Comment by bonustrack** [comment]
WIP here https://github.com/snapshot-labs/snapshot/pull/2698
