### ISSUE TITLE
Vote can be changed on 'Weighted Vote' setting

### ISSUE THREAD

**Issue by nickbax** [snapshot-labs/snapshot#2207]
**Describe the bug**
When casting a weighted vote, the user is warned, "Are you sure you want to cast this vote? This action cannot be undone". However, it is possible to vote a second time, changing the original vote. 

**To Reproduce**
1. I made a [new snapshot page](https://snapshot.org/#/ordermonopoly.eth/proposal/0x4ed143047f29cdb77c1bed84ef692f39aa384fa320d14924f2a168deff5fc28c) on Ethereum Mainnet with the `erc-balance-of` strategy, no voting delay and no plugins. 
2. Set up a new weighted vote. 
3. Vote for 'Yes'.
4. Change the vote to 'Wot???' and re-cast vote. 

**Expected behavior**
Users should not be able to change their vote after they have made their first vote

**Screenshots**
After first vote, right about to re-cast vote:
![image](https://user-images.githubusercontent.com/23515422/163889237-2f8946b4-650c-473b-bf3c-b55cc02626e6.png)
After second vote:
![image](https://user-images.githubusercontent.com/23515422/163889369-ab71879c-0931-48a0-a209-304b5b8cec22.png)

**Additional context**
I made a snapshot page and proposal where people can test this. Any mainnet account that had a WETH balance when I started the vote should be able to test it. https://snapshot.org/#/ordermonopoly.eth/proposal/0xfdeab5fa6be3c958620c1207789e512e03b67dff9c9068cb5e8ffd7cbe6eb6fd

**Comment by nickbax** [comment]
update: I was told in the snapshot Discord that this is a feature and not a bug. The prompt should be updated to tell people that votes are not final.

**Comment by hjjlxm** [comment]
>  "Are you sure you want to cast this vote? This action cannot be undone

The sentence means once you cast a vote, **you won't be able to withdraw the vote** but still be able to switch to another choice.
i.e. the vote itself cannot be undone, but literally it gives you the right to change mind until the proposal closes.

This feature applies to all voting types on snapshot. And only your last vote will be counted.

But admittedly, the sentence may create sorta ambiguity from the perspective of a new user indicating they'll only have one shot to choose a vote. @mktcode

**Comment by mktcode** [comment]
I agree. This is a bit misleading.

This can maybe be a proposal setting. It could then say:

> Are you sure you want to cast your vote? This cannot be undone.
or
> Are you sure you want to cast this vote? You can change your decision or revoke your vote until <space setting/proposal end>.

**Comment by metrox-eth** [comment]
How do you revoke a vote ?

**Comment by mktcode** [comment]
That would require some more considerations, yea... removed it.

**Comment by hjjlxm** [comment]
> Are you sure you want to cast your vote? This cannot be undone.
> or
> Are you sure you want to cast this vote? You can change your decision until <space setting/proposal end>.

I'd prefer the first modification that weakens the deterministic description of "this".

Or maybe even removing the second half of the sentence if it's formed a consensus that one cannot wipe out his (voting) activities whether it's on-chain or not once he choose to opt in.

**Comment by mktcode** [comment]
What makes this non-trivial are the different voting types. Some have just a single choice, other's have multiple. `choice` is a json field in the db with values like:

`1`
`[1,2]`
`{"1": 2, "2": 1}`

To know exactly the type it is, we'd need the proposal, which is only fetched if queried as part of the votes query.

A workaround would be to do the filtering in js and only based on whether it's an integer, array or object.

```js
if (where.choice) {
  votes.filter(v => {
    if (typeof v.choice === 'number') {
      return v.choice === where.choice;
    }
    if (typeof v.choice === 'object') {
      if (Array.isArray(v.choice)) {
        return v.choice.includes(where.choice);
      } else {
        return Object.keys(v.choice).includes(where.choice);
      }
    }
    return false;
  })
}
```
