### ISSUE TITLE
Can't download receipt files from IPFS

### ISSUE THREAD

**Issue by trkaplan** [snapshot-labs/snapshot#2234]
When I click on the Receipt of a Vote (icon in end of a Vote row under Votes section in a this Proposal page) I got timeout error.
I tried to see receipts in this proposal but no luck. 

**To Reproduce**
1. Visit https://snapshot.org/#/daocity.eth/proposal/0xc6596e12ae6391d81d73cbeee16254ebe9592fb2c47ba9bd1c2dd2861ed3c70b
2. Scroll down to Votes section and click the icon (with a label: "Receipt" when you hover it ) at the end of top row. 
3. Click the Hash next to "Author" label (https://cloudflare-ipfs.com/ipfs/Qmf8vitbUDbE8EDZfXUj3KmUZJNgmA8NumHL2uotwkLEkr)
4. You will get a Timeout error and not be able to download the file

I got 522 and 524 errors at different times for another hash (https://cloudflare-ipfs.com/ipfs/QmY3L2eT4CfWVY5U3MQ1xzXxmS1Rz851FZAs9XduMQML9K) I tried. 

Are these files pinned and stored forever or they are cached for a limited time? 

If they are pinned, why I receive timeout, 522 or 524 errors and is there an alternative way to download these files when I receive this error?

**Snapshots**
![snapshot-00-votes](https://user-images.githubusercontent.com/992897/164953197-a7b4c7b0-739f-4e67-aeee-f80d3361e3e6.png)
![snapshot-00-votes-1](https://user-images.githubusercontent.com/992897/164953230-f37f9d8f-1422-47ee-99a0-edc644021b5c.png)
![snapshot-00-votes-1-524](https://user-images.githubusercontent.com/992897/164953322-8cc4894b-7d4e-421f-8eb6-8d7cb4c07302.png)

**Comment by trkaplan** [comment]
update:
I got 
`ipfs cat /ipfs/Qmf8vitbUDbE8EDZfXUj3KmUZJNgmA8NumHL2uotwkLEkr: failed to get block for Qmf8vitbUDbE8EDZfXUj3KmUZJNgmA8NumHL2uotwkLEkr: promise channel was closed` error when I visited this link: 
https://cloudflare-ipfs.com/ipfs/Qmf8vitbUDbE8EDZfXUj3KmUZJNgmA8NumHL2uotwkLEkr

**Comment by trkaplan** [comment]
Any updates? I tried but couldn't access the file.

**Comment by samuveth** [comment]
> Any updates? I tried but couldn't access the file.

@midgerate is working on this and he will make an update here when it's done. Sorry for the delay

**Comment by midgerate** [comment]
@trkaplan The IPFS files will work properly now. Apologies that it too so long to fix it.
