### ISSUE TITLE
no response when on wrong network and then I cannot change network

### ISSUE THREAD

**Issue by SCBuergel** [snapshot-labs/snapshot#224]
**Describe the bug**
I am connected to e.g. Binance Smart Chain via Metamask when opening the page for the first time. When clicking `Connect Wallet` and choosing `Metamask` I get a turning wheel that just keeps going. When changing the network, the page tells me that I'm connected to `Fortmatic` (I never selected that) and there's no way to get out of this except for deleting local storage of the page.

**To Reproduce**
1. Connect new account in Metamask that isn't connected to the page yet
2. Change network to e.g. Binance Smart Chain
2. Click on `Connect Wallet`
3. You will see a turning wheel without any feedback why this is happening
4. Change network to main net
5. Now you will see that it chooses another choice but not Metamask and there's no way to get out here

**Expected behavior**
When being connected to a non-main net network, show "Wrong network, please connect to main net" in "Connect Wallet" button. When switching to main net, ensure that the choice of provider (e.g. Metamask) that I have made previously, persists.

**Desktop (please complete the following information):**
 - OS: Ubuntu and macOS
 - Browser: Brave
 - Version: 1.19.88

**Comment by samuveth** [comment]
@SCBuergel I haven't been able to reproduce this issue. 

- macOS 11.1 
- Brave Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (x86_64 translated)
- MetaMask 9.0.3

Are you using any older versions?

**Comment by samuveth** [comment]
![Jan-30-2021 17-17-20](https://user-images.githubusercontent.com/51686767/106353815-deead500-631f-11eb-94f7-06d41a99cec8.gif)
