### ISSUE TITLE
Feature request: Proof of Humanity as a requirement to vote

### ISSUE THREAD

**Issue by RosebuDAO** [snapshot-labs/snapshot#2263]
Any project using Snapshot should be able to require Proof of Humanity before that address is allowed to vote.

Additionally and perhaps a secondary feature, there should be a way for a project to specify that you must hold some minimum threshold of tokens before you can cast *just one* vote. Specifically, for the CityDAO Snapshot, there's a desire to move to "1 human = 1 vote, as long as you hold at least 1 Citizen NFT" (but holding more than one Citizen NFTs does not grant you more votes).

```
if(inSnapshot(address) && inPohRegistry(address) && numTokens(address, CityDAOCitizenNFT) >= 1)
{
    castVotes(proposal, selection, 1); //1 being number of votes
}
else
{
    error("You can't vote for this proposal");
}
```

**Comment by mktcode** [comment]
I think we have that already: https://snapshot.org/#/strategy/proof-of-humanity
Combine that with [the right NFT strategy](https://snapshot.org/#/strategies?q=erc721) and you're good to go.

**Comment by RosebuDAO** [comment]
Thank you! I think the [balance-of-with-thresholds](https://snapshot.org/#/strategy/balance-of-with-thresholds) is the "right NFT strategy" to use alongside PoH, but balance-of-with-thresholds doesn't specifically state that it works with erc1155 which is what the [CityDAO Citizen NFT](https://opensea.io/assets/0x7eef591a6cc0403b9652e98e88476fe1bf31ddeb/42) is. Should I open up a feature request for that or do you think balance-of-with-thresholds will work as-is?

**Comment by metrox-eth** [comment]
You can ask @ChaituVR what's the best path to do this. Snapshot's strategies are mostly a community effort. If you don't find an easy way for your use case, you can create a new strategy with your own logic, start here: https://docs.snapshot.org/strategies/create

**Comment by RosebuDAO** [comment]
[citydao-one-human-one-vote strategy](https://github.com/snapshot-labs/snapshot-strategies/pull/575)
