### ISSUE TITLE
Integrate Magic.link connector

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#227]
Magic integration require an email field, we would need first to create the connector on https://github.com/snapshot-labs/lock then update the Snapshot UI and ask user to input an email if he selected Magic.

**Comment by samuveth** [comment]
@bonustrack Will magic replace fortmatic?

**Comment by bonustrack** [comment]
I'm asking in their Telegram if it make sense to have both of them or if we can just use Magic.

**Comment by samuveth** [comment]
@bonustrack If Magic replaces Fortmatic we could write "Fortmatic" it in parentheses with the Magic.

**Comment by bigint** [comment]
If user has magic link also need to configure their wallet also right? without wallet it is difficult to do activities on snapshot 🙇🏻
