### ISSUE TITLE
Entering a space before discussion URL lead to "Oops, wrong proposal format" 

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#2274]
**Describe the bug**
Entering a space before discussion URL lead to "Oops, wrong proposal format" 
It could be quite frequent with copy pasta

**To Reproduce**
1. Enter a space before discussion URL

**Expected behavior**
The wrong format could be auto fixed.

**Comment by mktcode** [comment]
The field has no validation in the UI. Either that should be added or maybe a simple `trim()` is enough.
