### ISSUE TITLE
Show error when space does not exists

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#2275]
Currently when going to a space that doesnt exists it will show loading placeholder and nothing more:
https://snapshot.org/#/thisspacedoesntexists.eth
We should display an error similar than Twitter https://twitter.com/_22036201625

**Comment by Himnashu** [comment]
<img width="1725" alt="Screenshot 2022-05-03 at 1 52 18 AM" src="https://user-images.githubusercontent.com/53173981/166322680-84ce770f-e110-49d9-af81-dd4ae08314e0.png">

**Comment by Himnashu** [comment]
https://user-images.githubusercontent.com/53173981/166322995-d7f7bedb-fdab-4633-9be9-3ab25ca68951.mov
