### ISSUE TITLE
CORS Error When Loading Proposal

### ISSUE THREAD

**Issue by controtie** [snapshot-labs/snapshot#230]
**Describe the bug**
When attempting to load [this snapshot proposal page](https://snapshot.page/#/index/proposal/QmehWukEWUEe3NeGKQm5ZnaRsD22k4Yq9Wk6P3b8zv4uJ4) we encounter the following CORS error:
`
Access to fetch at 'https://cloudflare-ipfs.com/ipfs/QmehWukEWUEe3NeGKQm5ZnaRsD22k4Yq9Wk6P3b8zv4uJ4' from origin 'https://snapshot.page' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

**To Reproduce**
1. Go to https://snapshot.page/#/index/proposal/QmehWukEWUEe3NeGKQm5ZnaRsD22k4Yq9Wk6P3b8zv4uJ4
2. Open console
3. See error

**Expected behavior**
All other proposals for Index Coop seem to be working. Only this proposal is failing to load.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome, Metamask
 - Version: Chrome 88.0.4324.96, Metamask 9.0.3

**Comment by bonustrack** [comment]
@controtie That's weird, i also can't load that page on CloudFlare gateway https://cloudflare-ipfs.com/ipfs/QmehWukEWUEe3NeGKQm5ZnaRsD22k4Yq9Wk6P3b8zv4uJ4
I've changed the gateway does the page loading for you now?

**Comment by controtie** [comment]
Yes! Its working now. Thank you!
