### ISSUE TITLE
Binance support

### ISSUE THREAD

**Issue by ScottON** [snapshot-labs/snapshot#233]
I'd love to see support for coins held on Binance. 

Is this something that it's possible to add?

**Comment by samuveth** [comment]
Hi @ScottON, do you mean on Binance exchange website or Binance Smart Chain?

**Comment by ScottON** [comment]
Hey @samuveth ,

Thanks for getting back to me. I mean the Binance exchange website.

 Request Network is trialing snapshot and I was hoping to participate in votes without moving tokens off of the exchange.

Thanks.

**Comment by samuveth** [comment]
No that's not possible at the moment.
