### ISSUE TITLE
emojis are not rendered in proposal titles

### ISSUE THREAD

**Issue by thegostep** [snapshot-labs/snapshot#236]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/15959632/107771708-25213a80-6d09-11eb-9f15-609e5dc37df9.png">

**Comment by bigint** [comment]
@thegostep I can't reproduce this issue now 🙇🏻 

<img width="937" alt="Screenshot 2021-12-12 at 12 27 34 PM" src="https://user-images.githubusercontent.com/69431456/145703461-d1731327-1006-410d-8f61-381dd39ea34f.png">

**Comment by samuveth** [comment]
Yeah seems to be working now.
