### ISSUE TITLE
Update snapshot/src/components/DropdownAccount.vue for src/locales

### ISSUE THREAD

**Issue by rpdb-ops** [snapshot-labs/snapshot#2370]
Snapshot/src/components/DropdownAccount.vue doesn't change whith language.

I can do it for French if you explain to me how.

[https://github.com/snapshot-labs/snapshot/blob/develop/src/components/DropdownAccount.vue](url)

**Comment by samuveth** [comment]
@rpdb-ops thanks for reporting this. We have dedicated translators for french at the moment.

**Comment by rpdb-ops** [comment]
Good! I hope to be able to follow the update process to learn how it's done.
