### ISSUE TITLE
Translate the interface and connect it with Crowdin

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#238]
The first step is to add all texts in the file "src/locale/default.json", map the text with $t and $tc to translate them. Example:

default.json
```
{
  "createSpace": "Create space"
  "spaceCount": "{0} space(s)"
}
```
view
```
<template>
  {{ $t('createSpace') }} {{ $tc('spaceCount', [count]) }}
</template>
```

**Comment by samuveth** [comment]
Do we also want to translate this?
<img width="468" alt="Screen Shot 2021-03-07 at 7 01 54 PM" src="https://user-images.githubusercontent.com/51686767/110239078-b043c800-7f77-11eb-82f7-3bfeb3219ca5.png">

**Comment by samuveth** [comment]
Can we change this to "Disconnect"?
![image](https://user-images.githubusercontent.com/51686767/110239985-57c2f980-7f7c-11eb-938b-b9006ebf9773.png)

**Comment by bonustrack** [comment]
@samuveth Any specific reason? I prefer log out.

**Comment by bonustrack** [comment]
Facebook Twitter etc they all use Log out or Sign out

**Comment by bonustrack** [comment]
And yes we need to translate everything even the about modal @samuveth

**Comment by samuveth** [comment]
> Facebook Twitter etc they all use Log out or Sign out

Because it's "Connect wallet", "Disconnect" makes more sense IMO. Facebook etc use "Sign In", so "Log out" also makes sense.

**Comment by bonustrack** [comment]
That's a good point, but still, i'd prefer "Log out"

**Comment by samuveth** [comment]
> That's a good point, but still, i'd prefer "Log out"

Okay, let's leave as is
