### ISSUE TITLE
Create a webhooks request form

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#2398]
**Is your feature request related to a problem? Please describe.**
Now we have webhooks requests on a daily or weekly basis. It's not optimal to send those request to @bonustrack in DM.

**Describe the solution you'd like**
A form we can link to from the docs and people can enter a domain and the events they want to subscribe to and then the role with that task assigned get's an email.

**Comment by zzuziak** [comment]
Should be fixed via the [Webhook UI](https://github.com/snapshot-labs/webhook-ui).
