### ISSUE TITLE
Add mailchimp newsletter

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#2421]
- Add email section to footer and to settings page
- Setup testing account on substack

**Comment by midgerate** [comment]
@samuveth @bonustrack i saw that substack does not have an api and its iframe embed is not customisable. So we cannot use it on snapshot. 

Instead we can use Mailchimp. 

Mailchimp gives both the ability to embed a form in a popup using a script included in the head or allow API where we can create our own subscribe popup and use hub to add email to the Mailchimp list. 

Which option do you prefer? Is adding a script tag to head is okay? 

mailchimp does allow some bit of styling for its popup but not a lot. 

Also Mailchimp has something called groups which can allow the subscriber to choose multiple interests and we can target subscribers based on their interest. 

![image](https://user-images.githubusercontent.com/91108642/170827086-fe38f264-3809-489b-8c20-9cb44eb63906.png)

So what do you suggest? 

To keep snapshot design UI, we will have to create the popup ourselves and use the API for subscription.

**Comment by midgerate** [comment]
This is what kusama.network does and they are using this same popup

![image](https://user-images.githubusercontent.com/91108642/170827179-77ae95f0-2142-4d70-93fa-32cd47221405.png)

**Comment by samuveth** [comment]
Both sound good to me. @bonustrack I'll let you decide since one option required some addition to the hub.

**Comment by midgerate** [comment]
@samuveth I guess we are done with this?

**Comment by samuveth** [comment]
Still waiting for final design, but yeah functionality is mostly done.
