### ISSUE TITLE
Ranked choice voting 

### ISSUE THREAD

**Issue by jonathan-s** [snapshot-labs/snapshot#245]
**Is your feature request related to a problem? Please describe.**
When you've got multiple options, ie voting for a percentage burn or similar you could end up in situation where two options are diametrically opposed (without any tactical voting to influence the votes). 

A better voting mechanism would be to have ranked choice voting where you rank your preferences in a single vote and these are taken into consideration in the final tally.

Are there any plans of implementing something like that. I think that would be very nice.

**Comment by bonustrack** [comment]
@jonathan-s We've added recently ranked choice voting as voting method, you can select it when creating a proposal, give it a try. I'm closing the issue for now feel free to reopen it if you see something wrong.
