### ISSUE TITLE
Discussion image missing

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#2467]
![image](https://user-images.githubusercontent.com/51686767/170862923-9e440eed-0cee-48ed-bffd-3d08770369ba.png)
http://localhost:3000/#/arbitrum-odyssey.eth/proposal/0x44aba87414d2d7ce88218b676d9938338d7866a245f48a7829e805a99bcda6a2

**Comment by samuveth** [comment]
@bonustrack the issue seems to remain even after you upgraded

**Comment by bonustrack** [comment]
Actually the image is loading if we open on new tab, the issue I believe is that .ico doesnt work on `<img ../>` maybe it's better to show only preview image if available an not the website icon

**Comment by samuveth** [comment]
No sure how you would implement that

**Comment by mktcode** [comment]
> Actually the image is loading if we open on new tab, the issue I believe is that .ico doesnt work on `<img ../>` maybe it's better to show only preview image if available an not the website icon

Using `.ico` in `<img>` is possible. Discord just doesn't allow it. You get a 403. It's possible to download the image though.

**Comment by samuveth** [comment]
@mktcode I tried a few things without success. Solving it like this for now https://github.com/snapshot-labs/snapshot/commit/8cc80afd852435634ecbb899f0f7b6ba530fbc3b
