### ISSUE TITLE
Showing the wrong avatar image.

### ISSUE THREAD

**Issue by dr-ngubo** [snapshot-labs/snapshot#2477]
**Describe the bug**
The avatar on [our snapshot page](https://gov.aventus.io/#/) is showing the wrong image. We attempted to change it using both a URL and a direct upload. Neither worked. Last week, it showed the correct image, our company logo.

**To Reproduce**
1. Go to https://gov.aventus.io/#/
2. See weird green image

**Expected behavior**
Showing the uploaded image. 

**Screenshots**
<img width="267" alt="Screenshot 2022-05-30 at 16 59 20" src="https://user-images.githubusercontent.com/28754098/171028010-dc2e0f72-d5ff-4a77-a9c3-db6126b72175.png">

**Desktop (please complete the following information):**
 - Browser (iPhone and desktop) : chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - Browser chrome

**Additional context**

**Comment by samuveth** [comment]
Thanks for reporting this issue. We are currently working on a fix
