### ISSUE TITLE
Add support for OP delegation

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#2501]

**Comment by samuveth** [comment]
@ChaituVR No I mean that delegation page doesn't support OP network. https://snapshot.org/#/delegate

**Comment by ChaituVR** [comment]
Notes: 

Deploying delegation contract from singleton factory contract fail

Link to singleton factory contract https://optimistic.etherscan.io/address/0xce0042b868300000d44a59004da54a005ffdcf9f
Tried many times, example transaction:
https://optimistic.etherscan.io/tx/0x9718adc205ab7ad64aee7206de498761dd218d16de8eb5cbb2982daa1bd78255
It throw this error: 
> Although one or more Error Occurred [internal failure] Contract Execution Completed
 
But can't find any error here or on the transaction simulator

**Comment by samuveth** [comment]
@ChaituVR Ok great work and thanks for the update :)

**Comment by ChaituVR** [comment]
Finally able to deploy and verify here https://optimistic.etherscan.io/address/0x469788fe6e9e9681c6ebf3bf78e7fd26fc015446#code
