### ISSUE TITLE
There is also something else going on...

### ISSUE THREAD

**Issue by hoangson123456** [snapshot-labs/snapshot#2594]
There is also something else going on. I clearly had tokens at the snapshot for the DAO/proposal I'm looking at but hadn't "joined" on snapshot yet. There could be other factors as well, like the network you're wallet was connected to when joining the DAO's snapshot, or anything else I'm not aware of. But these qualifiers should be broadcasted front and center when good governance and the concept of inclusivity are central to this effort.

_Originally posted by @csggene3 in https://github.com/snapshot-labs/snapshot/discussions/767#discussioncomment-1512546_

**Comment by samuveth** [comment]
Closing for now, if you still have any issues please add additional information
