### ISSUE TITLE
Create issue flow

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#2609]

**Comment by samuveth** [comment]
@midgerate anything else comes to mind that we could add?

**Comment by midgerate** [comment]
@mktcode @samuveth btw, we seem to be using this. https://github.com/marketplace/stale

I think its good now. Our challenges were growing issue list that may be old and also keeping old issues if they are feature requests. 

The yml file @bonustrack created bug, enhancement and pinned tagged issues. 

IDK what `pinned` is used for. 

Also I see here https://github.com/snapshot-labs/snapshot/issues/labels there are some tags that are duplicate 

feature-request, enhancement
bug, bug-report

So tags, I do not understand, maybe they also need to be part of our exempt list. 

Let me know 
1. which labels are useless and what should the issues be tagged instead. I will delete those and tag the issues correctly. 
2. which labels are duplicates. I will delete those and tag the issues correctly. 
3. Let me know which labels should prevent an issue from being marked stale.

**Comment by samuveth** [comment]
Feature-request is tagged when opening a feature issue. Enhancement is for you when we confirm that this is a feature we would like to pay more attention to. Same with bug-report and bug, the latter is a bug that is confirmed by us.

The correct label are already set for preventing but yeah you can stange `wontfix` to `stale` if you think it's a good idea.
