### ISSUE TITLE
ssl3_get_record:wrong version number on snapshot.page from Brazil

### ISSUE THREAD

**Issue by Howard3** [snapshot-labs/snapshot#261]
**Describe the bug**
When loading snapshot.page from Brazil I am greeted by a SSL error in my browser. Further inspection via curl results in:

```bash
 curl https://snapshot.page/ -v
*   Trying 104.26.9.6:443...
* Connected to snapshot.page (104.26.9.6) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /Users/redacted/opt/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

Switching to a VPN, even within Brazil, seems to fix this. This is replicated across all browsers and my terminal in MacOS 11.2.2 (Big Sur).

I'm not certain which regions are impacted by this.

**To Reproduce**
1. Go to https://snapshot.page
2. Observe the SSL error

**Expected behavior**
A VPN shouldn't be required to view snapshot.page

**Screenshots**
```bash
 curl https://snapshot.page/ -v
*   Trying 104.26.9.6:443...
* Connected to snapshot.page (104.26.9.6) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /Users/redacted/opt/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
![CleanShot 2021-03-11 at 12 36 26](https://user-images.githubusercontent.com/196480/110812481-694f1e80-8266-11eb-92fd-18a554b12392.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.2 (Big Sur)
 - Browser: Microsoft Edge, Brave, Curl
 - Version 89, 1.20.110, 7.71.1

**Additional context**
It seems fairly regional and may be related to the edge node configuration.

**Comment by Howard3** [comment]
I figured this out. My router has a feature called "Malicious Content Filter" by Trend Micro. The root of the problem seems that  snapshot.page has been classified as a "scam" by trend micro. This should be rectified as other routers are bound to have similar problems. The router was trying to intercept the connection and ultimately failing to sign the page.

The classification can be found here: https://global.sitesafety.trendmicro.com/result.php?urlname=snapshot.page

As long as this is classified as a fraud while forcing https on the connection, users will never be able to load snapshot.page when their routers have this feature enabled, which would no doubt reduce participation in the voting process.

**Comment by samuveth** [comment]
Hi @Howard3, does the issue remain with the new domain snapshot.org?

**Comment by Howard3** [comment]
> Hi @Howard3, does the issue remain with the new domain snapshot.org?

Looks good however worth noting the website indicates it's not tested. It looks like the report that it was not malicious worked however for snapshot.page and it's no longer an issue, we can close this

**Comment by samuveth** [comment]
> > Hi @Howard3, does the issue remain with the new domain snapshot.org?
> 
> Looks good however worth noting the website indicates it's not tested. It looks like the report that it was not malicious worked however for snapshot.page and it's no longer an issue, we can close this

Awesome, thanks!
