### ISSUE TITLE
Handle boolean and array types in InputObject

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#2628]
Continued from #1353 
Right now if we add boolean or array types in schema, it looks like this:
![image](https://user-images.githubusercontent.com/15967809/173835851-d6ca5f1e-ad4d-4fc0-80f1-31f7028cb588.png)

For boolean - we can use InputSelect with yes or no?
For Array - DefaultObject

**Comment by ChaituVR** [comment]
The strategy that contains array type in schema.json https://snapshot.org/#/playground/recusal-list

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/commit/63f3d71c2618041b549f26300e69b7a952790fcb
