### ISSUE TITLE
Confirmation message is misleading someone cast vote with a Gnosis Safe

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#2685]
When someone cast a vote with Gnosis Safe there will be a confirmation message saying "Your vote is in!". This is misleading because vote is not really cast until the tx is confirmed on the Safe. We should instead show a message saying: Approve the pending transaction in the Safe interface to confirm your vote.

**Comment by samuveth** [comment]
Showing such a long message in a notification that is only visible for a second isn't optimal I think. I'd like to do this in a modal that shows this information after a vote is signed/cast.

Other than that this modal could include:
- Easy ways to share the proposal or how you voted on a proposal
- Ways to verify your own vote or look it up on IPFS
- Anything else that gives the user a feeling of accomplishment
- Some tips like:
  - You can change your vote
  - How to become a delegator
  - ect

**Comment by bonustrack** [comment]
Agree about a modal

**Comment by samuveth** [comment]
We need a design for this @bonustrack

**Comment by zzuziak** [comment]
Is this actually shipped and can we close the issue?
