### ISSUE TITLE
[BUG] - Proposal teaser should not display markdown

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#2696]
### Briefly describe the bug.

Proposal teaser should not display markdown

### How can we reproduce the bug?

1. Go to https://snapshot.org/#/breederdao-admin.eth
2. See markdown in teasers

### What is the expected behaviour?

Expected behavior is markdown being not displayed.  

### Can you attach screenshots?
<img width="1433" alt="Capture d’écran 2022-06-24 à 15 24 00" src="https://user-images.githubusercontent.com/55286013/175496567-c8edf7dd-5f0a-4db4-8238-2348aaa77577.png">

**Comment by mktcode** [comment]
This issue should be resolved with https://github.com/snapshot-labs/snapshot/commit/dc2c9ab214d33816de05adb375dd8d42b628df1f

Can we close this @metrox-eth ?
