### ISSUE TITLE
[BUG] - Can "vote" multiple times (multiple votes not actually counted, but in UI get approvals), wallet connect spinner keeps spinning

### ISSUE THREAD

**Issue by chaoticgoodpanda** [snapshot-labs/snapshot#2735]
### Briefly describe the bug.

[BUG] - Can "vote" multiple times (multiple votes not actually counted, but in UI get approvals), wallet connect spinner keeps spinning

### How can we reproduce the bug?

See this video: https://www.loom.com/share/67ccd27e576b42f7bafc2372f94a43a2. 

### What is the expected behaviour?

When I vote once on a proposal, Snapshot should restrict me from voting again, but it doesn't, endlessly returning with "Vote approved!" toasts.

Also when I connect my wallet using Brave get a perpetual spinner instead of the connected wallet address in upper-right-hand corner.

### Can you attach screenshots?

Video here: https://www.loom.com/share/67ccd27e576b42f7bafc2372f94a43a2

### Can you provide your device specific details below?

1. Device Type - Desktop, M1 Macbook Pro
2. Device OS - macOS
3. OS Version - Monterey 12.4
4. Browser - Brave
5. Browser Version - 1.40.107
6. Wallet - Metamask
7. Space - ENS
8. Any additional information we should know - https://www.loom.com/share/67ccd27e576b42f7bafc2372f94a43a2

**Comment by samuveth** [comment]
Voting multiple times on the same proposal is currently the intended behaviour and not a bug. This is needed for some DAO's and vote bribing, but we might make it optional in the future.

For the brave bug I will create a separate issue, thanks!
