### ISSUE TITLE
Voting percentages on snapshot.page differ from those calculated with data in downloaded report

### ISSUE THREAD

**Issue by letscrypto** [snapshot-labs/snapshot#276]
There could be a bug in the calculation of vote result percentages if the downloaded report vote data is accurate.

There appears to be a discrepancy in the calculated voting percentages presented on the snapshot.page was for the core vote https://snapshot.org/#/aavegotchi.eth/proposal/QmNqRry73rWXb9tdyHummihcK58ga83Ru15AJRF3beFJ35.  Data was provided in the available downloadable report.

The final result percentages were reported as follows:
Option
1. 2.51m GHST - 38.46%
2. 377.55k GHST - 5.78%
3. 3.54m GHST - 54.25%
4. 98.41k GHST - 1.51%
Totaling 100%

Analysis of the data in the download CSV report file, however, generated these final result percentages:
Option
1. 2510680.55326219 GHST - 37.99%
2. 377552.411966031 GHST -  9.30%
3. 3541698.81338083 GHST - 49.49%
4. 98408.5243795093 GHST -  3.22%
Totaling 100%

The raw token vote counts appear to agree but the percentages calculations differ significantly.  The CVS report file was converted to XLSX so it could be attached.  It may be that the fractional token votes less than one (1.00) in the CVS file are tallied incorrectly; there are 232 of 1657 entries meeting this criteria.

[snapshot-report-QmNqRry73rWXb9tdyHummihcK58ga83Ru15AJRF3beFJ35.xlsx](https://github.com/snapshot-labs/snapshot/files/6202403/snapshot-report-QmNqRry73rWXb9tdyHummihcK58ga83Ru15AJRF3beFJ35.xlsx)

![AGIP4_results](https://user-images.githubusercontent.com/76705239/112426794-8aa01800-8d06-11eb-89c5-32b033222224.PNG)

**Comment by samuveth** [comment]
Hi @letscrypto, the data seems to match the downloaded report now, you can see my results here: https://docs.google.com/spreadsheets/d/1Z2eVDt2MAUmyit5PmKJb2pTG4TfDT5c19bSBk6QLorM/edit?usp=sharing

**Comment by letscrypto** [comment]
I agree with samuveth's spreadsheet.  The displayed and the reported percentages are essentially the same. I must have miscalculated with the downloaded data. Sorry for the wild goose chase.
