### ISSUE TITLE
[BUG] - Settings page doesn't load properly without ENS text record

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#2768]
### Briefly describe the bug.

Not so likely to happen in the live env but on rinkeby (demo) ENS text records are being reset sometimes. If that happens, settings pages don't load properly.

### How can we reproduce the bug?

1. Go to https://demo.snapshot.org
2. Create a space / set text record
3. Go to settings page
4. Delete text record
5. Refresh settings page

### What is the expected behaviour?

There should be an message (on demo with additional info about rinkeby maybe). The user basically just needs to click on "Edit controller" and set it again.

### Can you attach screenshots?

![image](https://user-images.githubusercontent.com/6792578/177628983-ccc7e46d-6aac-4b84-8a1c-5b2a2bd56661.png)

**Comment by samuveth** [comment]
We just moved the demo to rinkeby, this will happen for most spaces on demo that were created on mainnet. In some cases the ENS for the space will not even exist yet on rinkeby.
