### ISSUE TITLE
[BUG] - UI doesn't display the "join space" action correctly

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#2771]
### Briefly describe the bug.

Unable to display joined spaces on the UI

### How can we reproduce the bug?

1. Go to https://snapshot.org/#/, with the wallet which has joined at least 20 spaces
2. Click on 'Join'
3. See error: the space avatar status remains "Join" and nothing new added on the left sidebar

**Debug:**
1. When you click on "Join", there's no error in the browser console, which means the user has actually joined the space
2. Probably has nothing to do with the alias, clearing local storage won't improve the problem at any way
3. "20" spaces is a key figure, when one quits 1 of the previously joined spaces, a new space he failed to join before will pop up on the left sidebar, and its avatar status will turn to "Joined", which shows it could be a UI error

Images of Reproduction attached below

### What is the expected behaviour?

Since there's no restriction on one's joined spaces, there should be a fix on the UI correctly showing joined ones.

### Can you attach screenshots?

![space join debug](https://user-images.githubusercontent.com/31681895/177730482-4b263533-7e30-4815-ae50-3100c5a198ca.png)

### Can you provide your device specific details below?

1. Device Type - [Desktop]
2. Device OS - [Windows]
3. OS Version - [Windows 10]
4. Browser - [chrome, firefox]
6. Wallet - [metamask]
7. Space - [All]

**Comment by samuveth** [comment]
@bonustrack somehow the space query seems to be capped on the backen. Adding the `first:200` doesn't have an effect and it only return 20 spaces. 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/51686767/178136264-9ea123a0-9c83-4f7b-b518-2c171b8693d7.png">

**Comment by samuveth** [comment]
Actually there was a limit of 20 on the followers query.

@hjjlxm This will be fixed in the next update.
