### ISSUE TITLE
I can't vote

### ISSUE THREAD

**Issue by Dukewang-cn** [snapshot-labs/snapshot#2797]
I have been holding UNI in my wallet, why does it show UNI voting power as 0 when I voted recently?

**Comment by samuveth** [comment]
@Dukewang-cn Only delegated UNI may be used to vote on proposals. You can delegate to yourself or another address here: https://app.uniswap.org/#/vote 
But you have to do this before the snapshot block number, if you do it, it will work for the next proposals
