### ISSUE TITLE
Text alignment issue in vote options

### ISSUE THREAD

**Issue by jnordberg** [snapshot-labs/snapshot#28]
<img width="994" alt="Screen Shot 2020-08-31 at 08 19 03" src="https://user-images.githubusercontent.com/95886/91671607-37e0f200-eb63-11ea-9707-7629687a21c0.png">

**Comment by bonustrack** [comment]
What's your browser? Can't reproduce atm.

**Comment by ironwebstar** [comment]
@jnordberg 
Could you please add the browser and device you were using? Otherwise, we can close it.
