### ISSUE TITLE
Add vote validation space settings

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#2817]

**Comment by bonustrack** [comment]
We need a way to add voting validation in the space settings, similar than proposal validation. The validation will have a name and params similar than proposal validation or voting strategy, and should be stored as "voteValidation" param in the space settings, here is the format: <https://github.com/snapshot-labs/snapshot.js/blob/master/src/schemas/space.json#L181>

**Comment by ChaituVR** [comment]
Marking this as complete ✅
