### ISSUE TITLE
Button overlap on homepage edito

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#2827]
On next.snapshot.org using french language the button "Learn more" become "En savoir plus" and it take 2 lines, we should use dynamic button width to avoid this
<img width="625" alt="image" src="https://user-images.githubusercontent.com/16245250/179585972-93f0f075-2f5e-4484-898d-0a2a146cdfcd.png">

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/commit/1a998dbefb7e428be9d3e74f1997985a3e863058
