### ISSUE TITLE
Vote percentage number is missing using non-English locale

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#285]
Percentage number is missing when using non-English language:

English
![image](https://user-images.githubusercontent.com/16245250/112997376-43e36f80-9197-11eb-9f7f-5d886a85fa17.png)

German
![image](https://user-images.githubusercontent.com/16245250/112997341-3cbc6180-9197-11eb-8488-4071ad072859.png)

**Comment by samuveth** [comment]
@bonustrack I can't reproduce this. On which proposal was this?

**Comment by bonustrack** [comment]
@samuveth Here https://snapshot.org/#/bancornetwork.eth/proposal/QmUag7EWMcBzacYFMfD6fYvfaX1sqoEGuLgsdnFr9QCqGq

**Comment by samuveth** [comment]
@bonustrack Also here I can't reproduce, I tried Chrome and Firefox
![image](https://user-images.githubusercontent.com/51686767/113249488-f8d97180-92e8-11eb-9725-4194340668f4.png)
