### ISSUE TITLE
ipfs resolve -r /ipns/snapshot.org/: could not resolve name: "snapshot.org" is missing a DNSLink record

### ISSUE THREAD

**Issue by ryancharleston** [snapshot-labs/snapshot#2864]
I keep getting this error in the Brave browser when trying to access any link from Snapshot.org

For example, when I try to access this link...

https://snapshot.org/#/sushigov.eth/proposal/bafkreigjjhjx2j2b526d3poeg23w2xan4rcgnzvcxinsssv7n37lu5p7s4

I get this error...

ipfs resolve -r /ipns/snapshot.org/: could not resolve name: "snapshot.org" is missing a DNSLink record (https://docs.ipfs.io/concepts/dnslink/)

Do you know why this is happening and how I can fix it?

**Comment by mktcode** [comment]
Sorry for the late response. I can't reproduce this. Could have been a temporary issue. Is everything working for you again?
