### ISSUE TITLE
Koncepted #3 UX Review - Proposal page improvements

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#2901]

**Comment by samuveth** [comment]
https://beneficial-lillipilli-60b.notion.site/Koncepted-3-UX-Proposal-page-6e223bbe8ac2408cb667d026bcfa4c6f

**Comment by samuveth** [comment]
There are a number of things related to the proposal page that we would like to tackle with this task. First step is to do a UX review for Voting and Results with the purpose of discovering additional issues and proposing solutions to them.



Some issues we have discovered so far:
- It is not clear for the user that he has already voted when on the proposal page.
- Results should have more space.
- Duplication of information between voting and results. (choices are repeated)
- Votes are taking up a lot of space.
- When a new user wants to vote it isn’t immediately clear what the voting type of the proposal is and how choices can be selected. The current indicator is in the right sidebar “Information” section, but besides the name of the voting type is doesn’t provide the user with any information.


Some rough solutions:
- There could be an indicator that the user has already voted
- and 3. “Cast you vote” and the “Results” could be merged
- ⬆️
- Votes could be moved into a modal
- Show voting types clearly when voting


Additional things to note:

- Results can also include a quorum e.g https://next.snapshot.org/#/bancornetwork.eth/proposal/0xe318e01813d1449fefd4986499619989ce39fa9a53f9df9723d19ae287565f16
- Proposals with all voting types can be found here on this testing space https://next.snapshot.org/#/pistachiodao.eth
- After you click "Vote" there is a confirmation modal that might not be needed or should be improved


Inspirations:

- https://vote.makerdao.com/polling/QmbWkTvW#vote-breakdown
   - ,+ Previous poll, Next poll buttons
   - ,+ Tabs for Vote breakdown, Poll details, and Comments
- Choice selection in dropdown will not work for all voting types on Snapshot
https://www.tally.xyz/governance/eip155:1:0xA89163F7B2D68A8fbA6Ca36BEEd32Bd4f3EeAf61/proposal/106547578420974062333790736643563905300617628952500817411921006525670751346829
   - ,+ The "status history" is neat
   - ,+ Vote is the first thing you see at the top of the page
   - ,- Voting inside inside a modal may be to limiting in terms of space for Snapshot with our many voting types
   - ,- To many graphs and main information of the proposal is at the bottom of the page
https://mirrorprotocol.app/#/gov/poll/247
   - ,+ Minimal and simple to understand
   - ,- "Vote details" look good, but will only work for basic voting
