### ISSUE TITLE
Koncepted #6 UX/Design - Admins and Authors component

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#2906]
https://beneficial-lillipilli-60b.notion.site/Koncepted-5-UX-Design-Admins-and-Authors-component-44fa1010ad2b4dba9ec2bf8a9a26f60e

**Comment by mktcode** [comment]
> A single input and a button the add users

I think there should still be a way to drop multiple addresses. Imagine orgs already having their spreadsheets and stuff, wanting to simply copy-paste a few dozen addresses instead of adding them one by one.
