### ISSUE TITLE
[BUG] - Infinite SSL Redirect + Internal Server Error

### ISSUE THREAD

**Issue by cblanquera** [snapshot-labs/snapshot#2925]
### Briefly describe the bug.

Im on the last step. Said "SSL redirect forced.". I turned off cloudflare proxy. Then infinite SSL redirect still. Then I tried to submit again. It said "Internal server error".

### How can we reproduce the bug?

1. Inspect https://dao.wearecashcows.com/ 
2. in "Networks" tab you will see the infinite redirects.
3. Go to https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=dao.wearecashcows.com

### What is the expected behaviour?

A version of https://snapshot.org/#/wearecashcows.eth should load

### Can you attach screenshots?

![image](https://user-images.githubusercontent.com/120378/182619593-5bf7164a-b460-4c84-8e29-ddd9b44b6645.png)

![image](https://user-images.githubusercontent.com/120378/182619749-074390d1-3249-497b-b1ce-94c1beda6b3f.png)

![image](https://user-images.githubusercontent.com/120378/182619882-bdc916f7-66f0-434f-a286-6cebae8bc8cc.png)

### Can you provide your device specific details below?

1. Device Type - Desktop
2. Device OS - MacOS
3. OS Version - 12.1
4. Browser - Chrome
5. Browser Version - 103.0.5060.134
6. Wallet - metamask
7. Space - ENS
8. Any additional information we should know - I love you.

**Comment by cblanquera** [comment]
https://dao.wearecashcows.com/#/ started loading, but now is going to snapshot home page.

**Comment by ChaituVR** [comment]
@cblanquera Hey yes! it takes a few days to redirect to your space, It updates once a week
