### ISSUE TITLE
vote.championfinance.io - Got "Internal Server Error"

### ISSUE THREAD

**Issue by aritasan** [snapshot-labs/snapshot#2928]
Hello,

We got the "Internal Server Error" when access on the link: 
https://ina9pk8175.execute-api.us-west-2.amazonaws.com/dev?domain=vote.championfinance.io

Please help us.

Thanks

**Comment by aritasan** [comment]
Hello,

When I try to access https://vote.championfinance.io. It displays the homepage of the snapshot. Our expected is displays the championfinance.eth detail. 


This is CNAME in my domain DNS setup: 
![image](https://user-images.githubusercontent.com/96032791/182808518-9ea14da2-c545-45b5-b0a9-818df6080778.png)

**Comment by ChaituVR** [comment]
This should be fine @aritasan , i can access snapshot from here https://vote.championfinance.io/#/

**Comment by aritasan** [comment]
Hi @ChaituVR ,

Thanks for your reply.
The https://vote.championfinance.io/#/ is displaying the homepage of https://snapshot.org/#/.
How to change it to display https://snapshot.org/#/championfinance.eth instead?
