### ISSUE TITLE
Function getProfiles fail if there is too much addresses

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#297]
It fail when there is too much addresses here: https://github.com/balancer-labs/snapshot/blob/c1f0c6aef4b884b9de4d169ce6af70b6f34bd100/src/helpers/profile.ts#L10

Here is the error from 3Box
![image](https://user-images.githubusercontent.com/16245250/114311720-0c22e300-9b1a-11eb-8d9d-b4b86af08d1e.png)

https://snapshot.org/#/fei.eth/proposal/QmWYNqr9Rcn8QFiZYyRqjQno3jXTToy3vM4bVKJkuntvoz

**Comment by ChaituVR** [comment]
@bonustrack this seems to be resolved now? maybe we can ignore for now

This size of input accepted totally depends on 3box's server, they need to configure it to a higher amount,
or 
we need to send these addresses in multiple requests
