### ISSUE TITLE
[BUG] - Text overlapping in votes modal

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#2970]
### Briefly describe the bug.

The ENS name overlaps with the choice in votes modal

### How can we reproduce the bug?

1. Go to a proposal page, when the user has an ENS name reverse record and it's long enough, it overlaps with the choice beside
Here's one of the [example](https://snapshot.org/#/dydxgov.eth/proposal/0x4baa732bacdb8e05efb482535c213c682d769dcbd2a6ef117fa070404d258dec)
2. See votes modal
3. See error

### What is the expected behaviour?

The original ETH address is shortened to a standard, while this is not applied to the ENS name.
It may cause overlapping when the ENS is long enough.

### Can you attach screenshots?

![overlap](https://user-images.githubusercontent.com/31681895/184062469-a28ad152-62d0-4320-b02e-588f2bb4c9a7.png)

### Can you provide your device specific details below?

1. Device Type - [Desktop, worse on a mobile view] 
2. Device OS - [Android, MacOS, Windows, iOS]
3. OS Version - [iOS 14, Windows 10]
4. Browser - [chrome, safari]

**Comment by samuveth** [comment]
Fixed https://github.com/snapshot-labs/snapshot/commit/c6cc0816fd4fc094482450b188dc71d99a21d3df

Will be live later today.
