### ISSUE TITLE
Show sub-space proposals on the main spaces

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#2974]

**Comment by mktcode** [comment]
This should then either be a space setting and/or the filter option we had in mind:

![image](https://user-images.githubusercontent.com/6792578/184172245-4ba59688-98c5-48a0-9818-aaf606255613.png)

![image](https://user-images.githubusercontent.com/6792578/184170978-7f93a2f7-8869-405b-ae6f-005559483945.png)

**Comment by samuveth** [comment]
This is working for snapshot.org but not for custom domains for
