### ISSUE TITLE
[BUG] - UI “Snapshot” not switching to the latest block# of the network in the playground

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#2986]
### Briefly describe the bug.

“Snapshot” not switching to the latest block# of the network in the playground

### How can we reproduce the bug?

1. Go to a [playground](https://snapshot.org/#/playground/erc20-balance-of)
2. Click on Network
3. See error: The "Snapshot" string below Network only fetches last block# from mainnet, and does not change when changing the network

### What is the expected behaviour?

The "Snapshot" should be the last block# of the default network of the strategy, and changes to the latest block number when user switched to another

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/commit/33ef9ed78d4022ea4a896d08f3e607a96e297f21
