### ISSUE TITLE
[BUG] - Error in GraphLQL data

### ISSUE THREAD

**Issue by imshashank** [snapshot-labs/snapshot#3004]
### Briefly describe the bug.

For space "xeo4.eth" , private is None and hence it results in an error when returning results

### How can we reproduce the bug?

1. Go to `https://hub.snapshot.org/graphql`
2. Run the below query:
```
query Spaces {
  spaces(
    orderBy: "followersCount",
  where:{
    id:"xeo4.eth"
  }
    orderDirection: asc
    
  ) {
    private
  }
}
```
3. see error:

```
{
  "errors": [
    {
      "message": "Boolean cannot represent a non boolean value: \"true\"",
      "locations": [
        {
          "line": 11,
          "column": 5
        }
      ],
      "path": [
        "spaces",
        0,
        "private"
      ]
    }
  ],
  "data": {
    "spaces": [
      {
        "private": null
      }
    ]
  }
}
```

### What is the expected behaviour?

There should be no error. Basically, a `default` value needs to be set.

### Can you provide your device specific details below?

GraphQL API hosted at : https://hub.snapshot.org/graphql?

**Comment by bonustrack** [comment]
@imshashank This should be `true` instead of `"true"` we've run some code to fix this error, it should work fine now.

**Comment by imshashank** [comment]
Works now, thanks for fixing.
