### ISSUE TITLE
Add PHI Network

### ISSUE THREAD

**Issue by Phinetwork** [snapshot-labs/snapshot#3006]
Hello can we please add PHI network smart chain to snapshot. Either can give instructions on how to do or can help integrate. Thank you https://chainlist.org/chain/144

Chain ID: 144
RPC: connect.phi.network
Explorer: phiscan.com

Archive node is full active.

**Comment by metrox-eth** [comment]
Hey ! Sure, you can follow the instructions here: https://docs.snapshot.org/networks
Thanks

**Comment by Phinetwork** [comment]
> Hey ! Sure, you can follow the instructions here: https://docs.snapshot.org/networks
> 
> Thanks

Have added thank you
