### ISSUE TITLE
Show delegation page

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3009]
Currently the the space page navigation only show delegation when the "delegation" strategy is set. We should make it show when any of the other delegation strategies are set or nested within a strategy like "math" strategy

**Comment by samuveth** [comment]
@bonustrack maybe the solution here is to always show `delegation` in the navigation. And if there are no delegations show a message.

**Comment by bonustrack** [comment]
@samuveth If we always show the page it might be confusing in the case of DAO using another delegation system. But we could do a JSON.stringify(strategies).includes('"delegation"'); to get to know if it exists on nested strategy
