### ISSUE TITLE
[BUG] - Demo spaces settings are not loading

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#3047]
### Briefly describe the bug.

Settings are not loading on demo

### How can we reproduce the bug?

1. Go to  https://demo.snapshot.org/#/metrox.eth/settings
2. See error

### Can you provide your device specific details below?

1. Device Type - [ex. Desktop or Mobile]
2. Device OS - [ex. Android, MacOS, Windows, iOS]
3. OS Version - [ex. iOS 11, Windows 10]
4. Browser - [ex. chrome, safari]
5. Browser Version - [ex. 101]
6. Wallet - [metamask, portis, walletconnect]
7. Space - [ex. ENS, Gitcoin]
8. Any additional information we should know -

**Comment by samuveth** [comment]
@metrox-eth demo has now been changed to Goarli testnet. To access your space settings you need to create the ENS on Goarli and set the text-record
