### ISSUE TITLE
[safesnap] - Point to chainid.org than adding new network from safesnap

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3059]
Continued from https://github.com/snapshot-labs/snapshot/pull/2819

As suggested by @mktcode better to point users to chainid.org than to maintain the RPC nodes from our side
(we are depricating RPC nodes from snapshot.js package https://github.com/snapshot-labs/snapshot.js/pull/657)

**Comment by ChaituVR** [comment]
keep this

**Comment by zzuziak** [comment]
Hey @ChaituVR , what's the situation here?

**Comment by samuveth** [comment]
@ChaituVR could you shed some light?

**Comment by ChaituVR** [comment]
We decided to keep the rpc for safesnap networks and remove others
