### ISSUE TITLE
Bug, quorum shouldn't include abstain if ignored from space settings

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3077]
When space settings to ignore abstain is enabled like this:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/16245250/188020508-5c6e5724-cc17-4a17-9354-14b2f4f27dfe.png">

We should not include the voting power of "Abstain" in the quorum calculations. You can test this issue in Bancor space here: https://snapshot.org/#/bancornetwork.eth

<img width="335" alt="image" src="https://user-images.githubusercontent.com/16245250/188020398-dc515dec-f9ab-4bce-a66c-87a1d58ac02d.png">

**Comment by samuveth** [comment]
@bonustrack when using the plugin we need to define `basicCount: [0, 1]` param to hide abstain.
