### ISSUE TITLE
[BUG] - Network in playground link is different from what it send to score API

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3081]
### Briefly describe the bug.

Network in playground link is different from what it send to score API

### How can we reproduce the bug?

1. Go to https://snapshot.org/#/playground/gysr-pending-rewards?query=eyJwYXJhbXMiOnsicG9vbCI6IjB4MzBjMGY2NWQ5YjI3ZWJlMmNjMmE0OWNiY2I0MTMzMjMwYjNmYjM4MSIsInJld2FyZFRva2VuIjoiMHhiRWE5OGMwNWVFQWUyZjNiQzhjMzU2NURiNzU1MUViNzM4YzhDQ0FiIiwic3ltYm9sIjoiR1lTUiJ9LCJuZXR3b3JrIjoxMzcsInNuYXBzaG90IjoiMTU0MTAwMDAiLCJhZGRyZXNzZXMiOlsiMHhjNTZlMzU3NTk5ZGU0NDE4YzNhMzNhZDYxMTEzMGQyYjJiMzZiMTlhIiwiMHgzYTVhNWVkNjhiM2VlYTgzZGY4MmZiZDNkMTZiMTY1NjJlMjA1ZmZiIiwiMHg2YzI0NDhjMjJhNzk0N2JkNGZkODg2YjcxOTYxOGI5MTNjZDA5NTM4IiwiMHgzMGMwZjY1ZDliMjdlYmUyY2MyYTQ5Y2JjYjQxMzMyMzBiM2ZiMzgxIl19
2. Click run and check network tab, it send `137` to score API

### What is the expected behaviour?

It should display 137 instead of mainnet or send mainnet instead of 137 to score API

### Can you attach screenshots?

![image](https://user-images.githubusercontent.com/15967809/188300936-0887b7e5-2294-4d44-bbdd-f6897616a0c4.png)

**Comment by samuveth** [comment]
Does this fix it @ChaituVR ?
https://github.com/snapshot-labs/snapshot/commit/ce95fbce7168af7e8636e445762f7b3bb033156d

**Comment by ChaituVR** [comment]
Awesome yes. It is working now on the preview.
