### ISSUE TITLE
[BUG] - Playground page doesn't scroll when we visit from a proposal

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3101]
### Briefly describe the bug.

The playground page doesn't scroll when we visit from a proposal

### How can we reproduce the bug?

1. Go to any proposal, for example, https://snapshot.org/#/ens.eth/proposal/0x5c96e490f3e28d8269e8fc7e929491fb8fa5e4bd04d3379f0c4f4bb1a42dc23e
2. Click on strategies, and click on the playground icon
3. and the scroll bar will disappear and we won't be able to scroll
4. There is no error in the console, even if we go back to the proposal we see scrolling is still disabled

### What is the expected behavior?

Ideally, the playground should open in a new window (with scroll enabled) - when there are multiple strategies It is too painful UX to check all playgrounds individually and come back to the proposal

### Can you attach screenshots?
![scroll issue](https://user-images.githubusercontent.com/15967809/188837965-e2d7ea7c-9742-4a7c-8461-e65da8797aa5.gif)

### Can you provide your device specific details below?

1. Device Type - Desktop 
2. Device OS -  Windows
3. Browser - chrome

**Comment by samuveth** [comment]
@ChaituVR does [this](https://github.com/snapshot-labs/snapshot/commit/3dd6e129c3217f6ef38ddd97e3b9a064b14e2ef0) fix the issue for you?

**Comment by ChaituVR** [comment]
Hey @samuveth, Yes, but when I click on the `Back` Button it goes to the strategy page instead,
can we make it a real link so we can open strategy playground in a new tab instead (or like before to open in a new tab by default)
because it is troublesome to debug strategies when a proposal is having multiple strategies

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/commit/c68620c71b21b8832bf81bb8289525c281dd0b6c
