### ISSUE TITLE
[BUG] - Votes do not count in Safe's batch execution situation

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#3124]
### Briefly describe the bug.

Votes are not counted in Safe's batch execution situation

### How can we reproduce the bug?

1. Use Safe's snapshot UI on mainnet
2. Vote with Safe on a series of proposals, until the last signer is ready to batch execute the txns in Safe
3. Txns executed successfully in history
4. Only the last proposal in the txn queue was counted into the Safe's vote history, reflected both in UI and graphql

### What is the expected behaviour?

Both UI and graphql should show all proposals that have been voted by Safe, there's a count error under batch execution circumstance.

Error not found if proposals are executed individually.

### Examples
The Safe address voted on [Head Chef Compensation [Signal] Part 2 - Part 6,](https://snapshot.org/#/sushigov.eth/proposal/0xa675fed66831bb587bf8a928550d2e05cb101e052297009999343e7c97a0400f) that's 5 proposals in total, with 5 individual sign message transactions batched into one execution. 
https://etherscan.io/tx/0x3c72ca292b0a9446a1314b85f177af3153a8db31e755cfe1b552b588a5979ac8

But only the last one - Part 6 is counted by Snapshot.
![safe execute snapshot issue2](https://user-images.githubusercontent.com/31681895/197308979-1cb0d801-01d0-4ce2-99df-6b860e69fe5d.png)

![safe execute snapshot issue](https://user-images.githubusercontent.com/31681895/197308497-d5681a33-b778-4b0a-bb34-f1fac1daa437.png)

**Comment by ChaituVR** [comment]
We now support batch execution 🚀 with https://github.com/snapshot-labs/snapshot-relayer/pull/62
