### ISSUE TITLE
[NEW FEATURE] - Show transaction link 

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3141]
### Briefly describe the feature.

Would be great if we have a link to open pending transaction 

### Which problem is this feature trying to solve?

Would be great if we have a link to open pending transaction 

### What is the expected solution?

![image](https://user-images.githubusercontent.com/15967809/190603178-082dfc60-e8cd-4ca4-bbea-5c0f8f3c5fdc.png)

**Comment by MyTrueWallet** [comment]
Clueless

**Comment by zzuziak** [comment]
@samuveth looks like a quick fix, could you take it on?

**Comment by j0hnfl0w** [comment]
@samuveth
We can extend useTxStatus() composable to store transactions in localStorage just like in [sx-ui](https://github.com/snapshot-labs/sx-ui/blob/master/src/stores/ui.ts#L47)
It is clear what to do with pendingCount in ModalRevokeDelegate.vue and useDelegate()
What we do with plugins?
/plugins/safeSnap/components/HandleOutcome.vue
/plugins/safeSnap/components/HandleOutcomeUma.vue
Are there transactions with ids too?

**Comment by samuveth** [comment]
No, it doesn't look like `approveBondUma` function return the transaction ID

**Comment by j0hnfl0w** [comment]
So for plugins we just pendingCount without any link anywhere

**Comment by samuveth** [comment]
@j0hnfl0w, the optimal solution might involve modifying the plugins code to return the transaction. However, since potential complications could arise, I think it's best to leave the final decision to you on how to proceed.
