### ISSUE TITLE
Add "reason" comment when cast vote

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3147]
We should add a text field on the vote confirmation modal to add allow user to add a comment when they cast a vote. 
![Image](https://user-images.githubusercontent.com/16245250/192519515-9559e798-f518-4190-995d-fea7dc2ae412.png)

**Comment by rootial** [comment]
how do we store comment via api? Where should we display it ?

**Comment by bonustrack** [comment]
@rootial The hub and Snapshot.js already support the field `reason` on vote message. You just need to add the reason param on the payload here: <https://github.com/snapshot-labs/snapshot/blob/038d5142c7412d7155ffb455c3983ab61ef654b3/src/components/ModalConfirm.vue#L44>
The comment should be visible within a tooltip in the vote list, like this: 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/16245250/192581411-cb3bdccb-da50-48ab-8cdd-2497cabaab3e.png">
You can use the icon `annotation` for this, we use https://v1.heroicons.com/

**Comment by twodam** [comment]
Has anyone take on this? I would like to working on it.

**Comment by chompu163** [comment]
just nice .

**Comment by twodam** [comment]
Discord: twodam#1024
