### ISSUE TITLE
Add button on vote confirm modal to share on Lenster

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3185]
Currently we propose only to share on Twitter when someone cast a vote, we should add Lenster too.
![Image](https://user-images.githubusercontent.com/16245250/192519287-59a8efb4-74fb-4ba6-8b41-ce002d6feea8.png)

**Comment by bigint** [comment]
💟 

Just wanna know where should I add the Lenster icon?

https://lenster.xyz/logo.svg

**Comment by bonustrack** [comment]
@bigint Should be in `src/assets/icons` folder

**Comment by bonustrack** [comment]
I think you'll have to import it like this `import lensterIcon from '@/assets/icons/lenster.svg';`

**Comment by bonustrack** [comment]
cc @samuveth

**Comment by chompu163** [comment]
I like this I have lenster.

**Comment by techtanzeel** [comment]
Hey, Is there anyone already working on this issue? seems @bigint might have started working on this but please let me know if I can still pick it up? @bonustrack

**Comment by bigint** [comment]
@techtanzeel Still I didn't picked this, hard to find bandwidth 🙈

**Comment by samuveth** [comment]
Taking this as I can't see any progress being made

**Comment by samuveth** [comment]
@bigint is there a way on Lenster to add the text to the URL so it can be prefilled like we do on Twitter sharing?

**Comment by techtanzeel** [comment]
Hey @samuveth, I'm in the middle of development. I was facing some authentication issue with lens API so reached out to them on their discord and that's why it got slightly delayed. Would you mind taking another task?

**Comment by samuveth** [comment]
@techtanzeel okay, do mind opening a draft PR so that we can follow your progress.

**Comment by eswarasai** [comment]
Would like to pick this up, thanks!

**Comment by samuveth** [comment]
@eswarasai sorry, I just opened a PR https://github.com/snapshot-labs/snapshot/pull/3290 for it. How about this issue https://github.com/snapshot-labs/snapshot/issues/3009?
