### ISSUE TITLE
BSC voting does not work for BEP20 token

### ISSUE THREAD

**Issue by incognito-inocente** [snapshot-labs/snapshot#319]
**Describe the bug**
Defining the erc20-balance-of for a BSC token leads to an error when trying to vote on a proposal for said token

**To Reproduce**
1. Go to https://snapshot.org/#/nococaine.eth/proposal/QmQigLx38s5Re2TmziBzphKJHM4m6EnkYHUknp9SJMmKkn
2. Voting is not enabled (dialog not shown when clicking on Vote)
3. Check Console
4. See error: Error: call revert exception (method="balanceOf(address)", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.10)

**Expected behavior**
Our space is configured for the Binance Smart Chain Mainnet, our token contract implements balanceOf as part of the IBEP20 interface, our strategy is set up following the examples provided:
{
  "symbol": "COCA",
  "address": "0x8B48B1941DfC1E18b98f75F1b6142d1a386f122e",
  "decimals": 18
}
Voting for holders of the token should be possible. A call to balanceOf should not fail, as the contract implements the method.

Can you please give us a hint of what we are doing wrong?

**Comment by bonustrack** [comment]
@incognito-inocente This is because the proposal use a snapshot block number that is more old than the token contract creation, you need to use a snapshot that is at least `6783335` to make it work.

**Comment by incognito-inocente** [comment]
> 
> 
> @incognito-inocente This is because the proposal use a snapshot block number that is more old than the token contract creation, you need to use a snapshot that is at least `6783335` to make it work.

Thank you for your kind help. I created a new proposal with a later block height, but the issue persist. Please see proposal:
https://snapshot.org/#/nococaine.eth/proposal/QmY2aR7FMQVaDTo2tTQB5WsbDGfaWCfAzV9WfDiT71YHEj

**Comment by incognito-inocente** [comment]
@bonustrack any suggestions?

**Comment by bonustrack** [comment]
There seem to be an issue with the BSC node we are using. Please allow us some time so we can troubleshoot this.

**Comment by incognito-inocente** [comment]
@bonustrack It seems to be working again now. Thanks so much for looking into it. I will close the ticket now.
