### ISSUE TITLE
Add templates for proposals

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3195]

**Comment by samuveth** [comment]
TODO

### Settings
- [ ] Add a new setting `guidelines` to the schema with the type 
- [ ] Add input on the Ui for the guidelines URL

### Proposal create page
- [ ] Show a block on first page of proposal creation with the link, same design as we have for the discussion link on the proposal page

Example: 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/51686767/204869285-3fda178a-d90c-4edb-bb07-be0864614ece.png">

**Comment by bonustrack** [comment]
@samuveth Guidelines and template aren't the same, for guideline I imagine this to be similar than a Space about where you can add some text and links but no markdown, it would just appear on different place like proposal creation. For template feature I imagine that you can define the default content of the proposal, quite similar than on GitHub with this: https://github.com/snapshot-labs/snapshot/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

**Comment by samuveth** [comment]
@bonustrack okay I have updated the TODO above accordingly. To me the guidelines should not a textarea and rather just a link.

**Comment by samuveth** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/51686767/205117360-573e9473-81b1-4bac-9a62-4aa056cd310c.png">

This is how I see both template and guidelines inside the settings. I've created a new block `Proposal` for them also
