### ISSUE TITLE
Why I can't vote?

### ISSUE THREAD

**Issue by jirolu16** [snapshot-labs/snapshot#3215]
### Discussed in https://github.com/snapshot-labs/snapshot/discussions/767

<div type='discussions-op-text'>

<sup>Originally posted by **metrox-eth** September 29, 2021</sup>
Suggest answers below or vote for an answer.</div>
where I can get voting power?

**Comment by metrox-eth** [comment]
It's depends on the proposal you want to vote for. Every project has different source of voting power, it can be tokens, NFTs, or whitelist, you can ask the project directly what's their token and governance flow.
