### ISSUE TITLE
Add CoinGecko id as space settings

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3225]
In the same way that we have Twitter, we should add a field "coingecko" where admin can define the CoinGecko id connected to their project. The parameter is already part of the schema here: https://github.com/snapshot-labs/snapshot.js/blob/master/src/schemas/space.json#L57 but it may require release new version of Snapshot.js for the UI and Hub (@ChaituVR can help on this).

**Edit:** We should also show the CoinGecko logo on the space page (similar than Twitter) with a link to the page.

**Comment by eswarasai** [comment]
Would like to pick this up, thanks!

**Comment by ChaituVR** [comment]
> the parameter is already part of the schema here: https://github.com/snapshot-labs/snapshot.js/blob/master/src/schemas/space.json#L57 but it may require release new version of Snapshot.js for the UI and Hub (@ChaituVR can help on this).
- [x] Updated both UI and hub with new snapshot.js version

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/pull/3238
