### ISSUE TITLE
Encrypt "reason" in shielded voting 

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#3228]
### Briefly describe the feature.

The reason comment by user should be encrypted or removed in shielded voting

### Which problem is this feature trying to solve?

The reason comment by user is visible to all during voting period, which is to say, people can intentionally use this **comment** to influence other's **voting inclination**, which undermines the nature of shielded voting.
![shielded voting audit](https://user-images.githubusercontent.com/31681895/195762467-430d529c-11f8-43d4-b3f4-db667a2b470d.png)

### What is the expected solution?

Same as "Choice" and "Current Result", the reason comment should also be encrypted during voting period.
It will only be visbile when the voting finishes.

### How do you currently handle this problem?

There's no way right now. User can comment at his own will.

### Anything else you'd like to mention?

https://github.com/snapshot-labs/snapshot/issues/3147 new designing ideas in the vote box for a new component: collapse by default to make the layout more compact

**Comment by wa0x6e** [comment]
Fixed via #3244
