### ISSUE TITLE
Quorum isn't working with shutter

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3234]
The quorum can no longer be calculated on proposals with shutter because we no longer load all the votes and `results.scoresTotal` is always zero (which is probably a bug @bonustrack). Also when using the Quorum plugin with the param `basicCount` it would not be possible to show the correct quorum as we don't know the results yet.

First we need to fix `results.scoresTotal` (on the hub) for proposals with shutter, if that is not an option then we either need to somehow load all votes on the Ui or hide quorum for these proposals while they are active.

Possible solutions for proposals with basicCount param:

1. Only show the quorum when the `basicCount` param isn't used.
2. Show a warning icon with some information that the quorum could be inaccurate until the proposal is final.
3. Something else?

**Comment by bonustrack** [comment]
@samuveth Can we hide the quorum when the proposal is active? And just show it once it closed. This would be ideal fix for now

**Comment by MyTrueWallet** [comment]
@samuveth why hiding the quorum it's supposed to be left Opened for further bug fixes ? Except theirs Is something malicious about it ????

**Comment by samuveth** [comment]
Hiding quorum doesn't seem to be the ideal fix anymore so I'm reopening the issue

**Comment by zzuziak** [comment]
Coming back to this one, @bonustrack wdyt about the previous suggestion from @samuveth ?

**Comment by ChaituVR** [comment]
Right now we are blocked because it is not possible to find valid choices for a vote because choices are encrypted

**Comment by samuveth** [comment]
@ChaituVR https://github.com/snapshot-labs/snapshot/pull/3390 this is blocked because the hub doesn't return the total voting power when choices are encrypted. Do you see a reason why the hub can't return today voting power anyway?

**Comment by ChaituVR** [comment]
@samuveth So we never know choice of a vote, if someone send a invalid choice, the quorum will be changing after proposal close

Example: 
If a proposal contains `Yes` and `No` as choices If I send an encrypted choice for `abstain` It is invalid but counted for quorum.

**Comment by samuveth** [comment]
@ChaituVR yes, we agreed that we will show a big warning in this case.

**Comment by samuveth** [comment]
Related issues:
https://github.com/snapshot-labs/snapshot-hub/issues/554
https://github.com/snapshot-labs/snapshot-hub/issues/523

**Comment by ChaituVR** [comment]
Can we close this?
