### ISSUE TITLE
[NEW FEATURE] - 

### ISSUE THREAD

**Issue by Mun1175** [snapshot-labs/snapshot#3236]
### Briefly describe the feature.

Voting Issue on Optimism

### Which problem is this feature trying to solve?

I can't vote on snapshot.org, i have had tokens since first airdrop of the protocol . I got tokens in my metamask wallet im trying to vote and i can't vote on any proposals, its showing that i have 0 OP token to vote. can sone one help me resolve this issue ?

### What is the expected solution?

idk

### How do you currently handle this problem?

waiting

**Comment by metrox-eth** [comment]
OP tokens needs to be delagated to yourself, once done you will be able to vote on future proposals not currents.
https://app.optimism.io/airdrop/delegates
Click on delegate to anyone
