### ISSUE TITLE
Remove choice when sharing a proposal with Shutter

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3237]
Currently even if you vote is encrypted for Shutter voting, the UI know what you vote for when you cast the vote and will propose to share it on Twitter, we should remove the choice from the sharing message to avoid confusion.

**Comment by samuveth** [comment]
Fixed https://github.com/snapshot-labs/snapshot/commit/c66c3a224f1ec73ee6215bc410f4078401e0f478
