### ISSUE TITLE
Show warning on proposal page for spaces with -1

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3250]
Currently we show a warning icon for space with -1 verification only on the space page. We should do also that on the proposal page. We can also disable the button to cast a vote for these spaces.

**Comment by samuveth** [comment]
Can you give some more context on why we would want to disable the vote button and what do we do in the case if the space has a custom domain?

**Comment by bonustrack** [comment]
@samuveth this is to prevent activity coming from malicious space. Another option would be to add a warning message that must be checked to be able to cast a vote. Similar than adding a custom token on Uniswap

**Comment by samuveth** [comment]
Uniswap does this for all tokens that are not verified, maybe we should consider doing that too. But I don't see how showing a message would prevent malicious activity like vote spamming on flagged spaces. @bonustrack
