### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by LamPhong2010** [snapshot-labs/snapshot#3257]
i locked STG for 24 months for voting rights. but when entering the vote, it does not show up. Suggest dev edit soon for the community to vote. thank you.

**Comment by metrox-eth** [comment]
You must hold / stake the token before the creation date of the proposal you will be able to vote on the next proposal

**Comment by LamPhong2010** [comment]
Thank you for your reply.  I have a question?  Why can't you vote, you
can't close it.  to open a new vote.  Some of my friends can't vote to
think the network is congested.  You should make adjustments in time.  not
easily misunderstood by investors.  Wish the project has a strong
community.  thanks team.

Vào CN, 23 thg 10, 2022 lúc 23:31 metrox-eth ***@***.***> đã
viết:

**Comment by metrox-eth** [comment]
Thanks for your feedback, we will make improvements soon.

**Comment by LamPhong2010** [comment]
thank you.  It would be great if I could get some tokens early to make the
mini game go viral for our community.  I can spread more people to know
about your project.  this is my wallet, thank you very much.


0x1EC8B38B49812cb57a23772Cb3f4dFd653e2232d

Vào Th 2, 24 thg 10, 2022 lúc 01:30 metrox-eth ***@***.***>
đã viết:
