### ISSUE TITLE
Why I can't vote?

### ISSUE THREAD

**Issue by yunustoheeb** [snapshot-labs/snapshot#3258]
### Discussed in https://github.com/snapshot-labs/snapshot/discussions/767

<div type='discussions-op-text'>
I have voting power because I staked 5 STG but I not still able to vote it stuck the button not click able   

<sup>Originally posted by **metrox-eth** September 29, 2021</sup>
Suggest answers below or vote for an answer.</div>

**Comment by metrox-eth** [comment]
You must hold / stake the token before the creation date of the proposal you will be able to vote on the next proposal
