### ISSUE TITLE
Voter choice shown "Invalid choice" in UI

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#3260]
### Briefly describe the bug.

Choices are defined invalid in some proposals

### How can we reproduce the bug?

1. Go to the [proposal in issue](https://snapshot.org/#/ens.eth/proposal/0x42605fa85d059459f7072aeaeea4cd14ada78e15d9aa1998fe99634a75f9f5a6)
2. View the Votes list
3. See error
![invalid choice](https://user-images.githubusercontent.com/31681895/197448464-81c5adb4-9567-49f5-8ea2-0f5354d1c1ef.png)

### What is the expected behaviour?

It seems only choices in ENS name are defined as "invalid choice" and thus can not be shown in the UI

The [graphql query to this vote](https://hub.snapshot.org/graphql?operationName=Votes&query=query%20Votes%20%7B%0A%20%20votes%20(%0A%20%20%20%20first%3A%201000%0A%20%20%20%20skip%3A%200%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20proposal%3A%20%220x42605fa85d059459f7072aeaeea4cd14ada78e15d9aa1998fe99634a75f9f5a6%22%0A%20%20%20%20%7D%0A%20%20%20%20orderBy%3A%20%22created%22%2C%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20)%20%7B%0A%20%20%20%20id%0A%20%20%20%20voter%0A%20%20%20%20created%0A%20%20%20%20proposal%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20choices%0A%20%20%20%20%7D%0A%20%20%20%20choice%0A%20%20%20%20space%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) is not influenced

**Comment by samuveth** [comment]
This is only happens on older ranked-choice proposals where we didn't enforce to select all ballots. The results seem to have been not recalculated since our change to ranked-choice voting and so they are still intact.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/51686767/197460945-61154570-f343-421f-ab6f-2c7797e6b8d8.png">
