### ISSUE TITLE
Improve UX when not able to vote with zero token balance

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3267]
Current UX is still not very clear why the user isn't able to vote, the external link from the info icon can easily be overlooked and even then the discussion doesn't have all the answers.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/51686767/197539114-8e6221e3-98d6-4726-97ea-0e34ffa6ed6f.png">

Solution:
I imagine a troubleshooting page, a little like the playground where the user will be able to click through 1-3 proposal related question and get the exact reason for why he is not able to vote directly in the snapshot ui.

Also instead of showing the info icon, we should show a prominent message inside the modal as this will be what the user is most likely trying to troubleshoot when voting power is zero.

**Comment by samuveth** [comment]
Solution for error and link to discussion visibility:
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/51686767/198137234-e5e911cc-81f0-42aa-bdb9-a49d65ad056f.png">

Also here is improved design for when voting power fails to load:
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/51686767/198136963-f5b93f6f-a028-419a-8083-99acd2b09485.png">

**Comment by bonustrack** [comment]
Looks good, I recommend not use a sentence with "it doesnt seem" but instead use "Oops, it seem you don't have any voting power", that make the sentence much easier to read. We could also add in the sentence "...any voting power at the block number 12345" to make it more clear the vp is based on specific time.

**Comment by bonustrack** [comment]
For the message when the request fail we could add a link to retry query vp
