### ISSUE TITLE
Too much space

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3287]
There is too much space here, did anything changed?
<img width="797" alt="image" src="https://user-images.githubusercontent.com/16245250/198280616-27e8b5a4-d9fa-44fc-a03a-5272d7300b5c.png">
The space should be same as in the homepage

**Comment by bonustrack** [comment]
Same issue on proposal page
<img width="522" alt="image" src="https://user-images.githubusercontent.com/16245250/198282478-407d2c93-87e4-47f0-a585-73b4f7ee98b4.png">

**Comment by bonustrack** [comment]
Create proposal page too, most likely many others page got this increased space, we should fix that.

**Comment by samuveth** [comment]
Yeah this slipped in with the space warning message it's fixed now https://github.com/snapshot-labs/snapshot/commit/c242a0e99baeba9bd568691888c8d6f268e91493
