### ISSUE TITLE
RADAR token is not tracked by Covalent

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3292]
For some reason Covalent don't track RADAR token, this make Treasury page not much relevant for Dappradar DAO. We should find a solution with Covalent or move to another service to track holding. I've noticed Covalent can also have slow response time.

**Comment by emanuel-sol** [comment]
The RADAR token is not returned from the token list [here](https://github.com/snapshot-labs/snapshot/blob/7e95dbbb65b7aa65073e08a3c0a157db8bbb896b/src/composables/useTreasury.ts#L6) so I believe it will not be displayed.
