### ISSUE TITLE
[BUG] - Choices auto-populated when not supposed

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#3301]
### Briefly describe the bug.

Choices auto-populated when not supposed

### How can we reproduce the bug?

@TheNathanVDH Reported choices are abnormally pre-filled with largest voter choices on weighted voting proposals that he never voted previously such as:
https://snapshot.org/#/banklessvault.eth/proposal/0x43d5c3f2f97967049a03ceaa84bb9b68de068542a38e97212ad8859416fcbbd7
https://snapshot.org/#/lyra.eth/proposal/0x612cf9ef83323fb89614f57895bd7f2ff73f26256af8aed89b8c31ef280a3bdb

I can't reproduce the issue with my wallet.

### What is the expected behaviour?

If the voter never voted choices are supposed to be empty. 

### Can you attach screenshots?

<img width="682" alt="Capture_decran_2022-10-31_a_14 29 10" src="https://user-images.githubusercontent.com/55286013/199042678-0adf38db-0b95-40cd-9c26-86a74f8d5f82.png">

### Can you provide your device specific details below?

1. Device Type - [Desktop]
2. Device OS - [MacOS]
3. OS Version - [ex. iOS 11, Windows 10]
4. Browser - [chrome]
6. Wallet - [metamask]

**Comment by samuveth** [comment]
Fixed https://github.com/snapshot-labs/snapshot/commit/5238a3be5e6ef2c3b9d994a9aef61dc738c681c3
