### ISSUE TITLE
[BUG] - Open playground in new tab

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3316]
### Briefly describe the bug.

In proposal page, open playground for strategies in new tab instead of same page

### How can we reproduce the bug?

https://snapshot.org/#/safe.eth/proposal/0x87c8091b5edc2cb489cc0f4231c8b675dbb1b11aa42c260c81ead9cf312f193f

Go to above proposal, and try to open playgrounds for all strategies.It is super hard to open one by one, instead opening it in new tab saves a lot of time to go through all strategies

### What is the expected behaviour?

should open in new tab

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/commit/7f23d7670c530490e3f7e7983e76e9155b41d159
