### ISSUE TITLE
[BUG] - Not able to see the images on snapshot.demo org site

### ISSUE THREAD

**Issue by katariachetan** [snapshot-labs/snapshot#3325]
### Briefly describe the bug.

I am not able to see any image 

### How can we reproduce the bug?

1. Go to 'https://demo.snapshot.org/#/'
2. Click on DAO 
3. You will not able to view the images

### What is the expected behaviour?

I should be able able to view images on snapshot.demo site

### Can you attach screenshots?

![image](https://user-images.githubusercontent.com/117351209/201859022-d20db358-2547-4e94-8c0a-85d4676727a3.png)

### Can you provide your device specific details below?

1. Device Type - Desktop
2. Device OS - Windows, iOS
3. OS Version - Windows 10
4. Browser - chrome
5. Browser Version - Version 106.0.5249.103
6. Wallet - metamask
7. Space - ImpossibleDAO, OrangePool
8. Any additional information we should know -

**Comment by ChaituVR** [comment]
@katariachetan It works for me, Maybe there was a network issue at that time. can try again?

**Comment by katariachetan** [comment]
@ChaituVR I tried to connect to internet using vpn & without using vpn. Attached the screenshot for the same. I am still seeing the same the issue. Could you please guide where I am going wrong?
![image](https://user-images.githubusercontent.com/117351209/201906211-0cd2f5bb-8fd0-4cbb-8b22-6f195719b513.png)

**Comment by katariachetan** [comment]
A friendly reminder!

**Comment by samuveth** [comment]
@katariachetan this could be an issue with one of your extensions.

**Comment by katariachetan** [comment]
Can you please help me to resolve it? For snapshot I am using the web not chrome plugin.

**Comment by katariachetan** [comment]
Thank you for the response. Can you please help me with browser extension is causing problem @samuveth ?

**Comment by katariachetan** [comment]
A friendly reminder!

**Comment by metrox-eth** [comment]
> Can you please help me to resolve it? For snapshot I am using the web not chrome plugin. Even I have allowed images on chrome
Since this is the first and only report of this issue, I guess there is something blocking from your side, the usual culprits are adblockers or other types of extensions, security softwares and firewall, you can try to disable all extensions and antivirus/ security software, if it doesn't solve the problem you can take a more methodic approach, try an other browser, an other device, an other internet service provider, so you narrow down the source of the issue.

**Comment by metrox-eth** [comment]
Anyway, when you fix the issue you may be disappointed, all you will see is blockies, avatar upload is not supported on demo site.
