### ISSUE TITLE
[NEW FEATURE] - Add proposal activity to profile page

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3340]
### Briefly describe the feature.

Add proposal activity to profile page

### Which problem is this feature trying to solve?

Would be great if we can add proposal activity (proposal creation) to profile page https://snapshot.org/#/profile/0x24F15402C6Bb870554489b2fd2049A85d75B982f 
Also timestamps of the activity 

### What is the expected solution?

- [ ] Display proposal creation activity on the profile page (similar to votes)
- [x] Display timestamps on each activity

**Comment by samuveth** [comment]
We need an activities table on the hub so we can query activities with a single query. This is because we have an infinite scroll for activities list and that wouldn't work well with two separate queries one for votes and one for proposals.

**Comment by ChaituVR** [comment]
Reopened this so we can keep track of this,
I think it would be hard to maintain a separate table. we should try to add a new query to get data from two tables 

Alternatively, I think we can have two separate sections for the proposals activity and votes activity with `Next` and `Previous` buttons instead of infinite scrolling

**Comment by samuveth** [comment]
@ChaituVR can you create an issue for this on the HUB. 🙏

**Comment by ChaituVR** [comment]
🤔 What else do we need on the hub to achieve this?

**Comment by samuveth** [comment]
@ChaituVR didn't see that you already created the issue. Sorry!
