### ISSUE TITLE
[BUG] - Scroll is broken in space page

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3351]
### Briefly describe the bug.

If vote modal is open and if click back button, scroll is missing and have to refresh the page to see scrol again

### How can we reproduce the bug?

1. Go to any proposal with voting power
2. Select a choice and Click on vote
3. Click browser back button
4. See error that we can't scroll anymore

### What is the expected behaviour?

Should be able to scroll through proposals 

### Can you attach screenshots?

https://user-images.githubusercontent.com/15967809/204069453-424090cb-8952-474b-8a7e-14affa50831f.mp4

https://user-images.githubusercontent.com/15967809/204068743-f81be11d-fb65-4de0-9cff-ac5a181ab76d.mp4

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/commit/e3733b6865507959c27260f3b088bc14d39b7b67
