### ISSUE TITLE
[BUG] - Wrong support link in the footer

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#3352]
### Briefly describe the bug.

Wrong support link in the footer

### How can we reproduce the bug?

1. Go to https://snapshot.org
2. Scroll down to footer
3. Click on Support

### What is the expected behaviour?

Link should be https://discord.gg/snapshot instead of https://discord.snapshot.org

### Can you provide your device specific details below?

1. Device Type - [ex. Desktop or Mobile]
2. Device OS - [ex. Android, MacOS, Windows, iOS]
4. OS Version - [ex. iOS 11, Windows 10]
5. Browser - [ex. chrome, safari]
6. Browser Version - [ex. 101]
7. Wallet - [metamask, portis, walletconnect]
8. Space - [ex. ENS, Gitcoin]
9. Any additional information we should know -

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/commit/8416b3e3a47764eb99f39b330139ef1a2b4467f7
