### ISSUE TITLE
Show voting form before votes are loaded

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3370]
Currently the voting form / voting section is only visible once the votes are loaded, this shouldnt be the case. The form should appear directly.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/16245250/204748752-5511d337-4c46-46b8-b818-99f04551ffa4.png">

**Comment by Quevara** [comment]
Can't wait

**Comment by samuveth** [comment]
The voting block is only visible after the votes are loaded because we populate the users vote if they have already votes. If we show the block the before it's loaded and the users already selected some choices it will reset back to what the user voted after it's loaded

**Comment by samuveth** [comment]
We could show the voting block while loading but disable it?
