### ISSUE TITLE
move to WalletConnect v2

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3385]
WalletConnect v1 will be sunset in Feb 23, we should move to v2
https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e

**Comment by samuveth** [comment]
App migration starts after 1. January 2023, until then dapps can not upgrade

**Comment by samuveth** [comment]
Migration should be done using the new universal provider:

https://github.com/WalletConnect/walletconnect-monorepo/tree/v2.0/providers/universal-provider
https://www.npmjs.com/package/@walletconnect/universal-provider

**Comment by bonustrack** [comment]
We should do this before end of March to sync with Anchorage support for WalletConnect.

**Comment by samuveth** [comment]
I got the information on the WC discord that many wallets still don't support V2. This means we should probably support both until that changes.

**Comment by bonustrack** [comment]
If we move to V2 before the wallet it wont work?

**Comment by ChaituVR** [comment]
This is done ✅
