### ISSUE TITLE
Enable space avatar update only for admins and owners

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3406]
Right now we allow anyone to edit space avatar (they can't save it)

![AAAAAAAAAAAB](https://user-images.githubusercontent.com/15967809/208050853-7807e57e-65b6-4a28-ba46-93a80ae88478.gif)

- [ ] Don't display the Edit option if user is not a admin/space owner
- [ ] Don't display Edit option to everyone if it demo.snapshot.org

**Comment by samuveth** [comment]
This will be part of the greater refactoring of the space settings page.

**Comment by zzuziak** [comment]
@samuveth would you be up for shaping a pitch for the settings redesign?

**Comment by samuveth** [comment]
@zzuziak Basically just need a designer 😆

**Comment by zzuziak** [comment]
Gotcha, not pinging on the design issues anymore :grin:

**Comment by hjjlxm** [comment]
Should the “upload avatar” button be disabled in demo Snapshot space settings and add a tip to notify users that custom avatar is not supported in demo version?

**Comment by samuveth** [comment]
Closing in favor of https://github.com/snapshot-labs/snapshot/issues/3571
