### ISSUE TITLE
never had this problem before, undefined warning when pasting address

### ISSUE THREAD

**Issue by futjrnaut** [snapshot-labs/snapshot#341]
![image](https://user-images.githubusercontent.com/58874935/116830588-50cdf700-ab79-11eb-8e55-ca299a6aed3e.png)

lemme know feelin pretty smoothbrained on this issue.

**Comment by ChaituVR** [comment]
Hi @futjrnaut it's not `Content` record now..  Follow below steps:

```
On the ENS page, click on ADD/EDIT RECORD.
Select TEXT and type the key "snapshot" in lowercase.
Paste the IPNS link in the field.
Click Save.
Scroll down and click Confirm.
Sign the transaction with your wallet.
```

More details on https://docs.snapshot.org/spaces/create

**Comment by ChaituVR** [comment]
Closing this for now, please feel free to re-open it if you are facing any issue, Thanks
