### ISSUE TITLE
[BUG] - Share link for twitter or lenster does not work

### ISSUE THREAD

**Issue by atharva3010** [snapshot-labs/snapshot#3419]
### Briefly describe the bug.

Clicking the "Share on Twitter" button does nothing.

### How can we reproduce the bug?

1. Submit a vote.
2. See this screen:
![image](https://user-images.githubusercontent.com/34229217/209392208-5aa0807a-e01f-4bf3-bbf1-725749b0e2ae.png)
3. Click the button labelled "Share on Twitter" or "Share on Twitter".
4. Nothing happens.

NOTE: This bug was reported by a user on the discord server's #general channel.

### What is the expected behaviour?

The expected behaviour, according to @ChaituVR, is that the share link opens in a new pop-up.

### Can you attach screenshots?

![image](https://user-images.githubusercontent.com/34229217/209392282-ef9e9236-9276-4571-b539-c910c4cc46ce.png)

### Can you provide your device specific details below?

1. Device Type - [ex. Desktop or Mobile]
2. Device OS - [ex. Android, MacOS, Windows, iOS]
3. OS Version - [ex. iOS 11, Windows 10]
4. Browser - [ex. chrome, safari]
5. Browser Version - [ex. 101]
6. Wallet - [metamask, portis, walletconnect]
7. Space - [ex. ENS, Gitcoin]
8. Any additional information we should know -

**Comment by atharva3010** [comment]
When I came across this bug on the chat, it was obvious, the problem is because of the pop-ups being disabled in the user's browsers. Since most modern browsers are now configured to actively watch for pop-ups and block them unless they are from trusted sources, it's best to route the user through an alternate route.
Possible solutions are:
1. Offer info to the user that the pop-ups are blocked on their device and ask them to enable pop-ups. The downside to this option is that it increases friction in the user experience.
2. Instead of displaying a browser pop-up, open the link in a new tab.
3. Just copy the share link to the user's clipboard and display a modal.

**Comment by samuveth** [comment]
Hi @atharva3010, we already do what you suggested in point one. We are using `window.open` with `'_blank'` which is considered [correct practice](https://stackoverflow.com/questions/2587677/avoid-browser-popup-blockers) when directly linked to a user action like a button click.

The users issue must be related to something else. I will respond to him on discord to investigate further.
