### ISSUE TITLE
[NEW FEATURE] - Minimum and maximum voting period

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3423]
### Briefly describe the feature.

Add a similar feature than SX to use min and max voting period to keep voting active until quorum is reached

### Which problem is this feature trying to solve?

More details: 
> We have a governance system that any voting needs to reach a quorum to proceed. If it’s not reached the voting will keep open until is reached.

Team Discussion: 
https://discord.com/channels/955773041898573854/1030772407226601522/1057997617692418058

Forum Link: 
https://discord.com/channels/707079246388133940/1057711880916975666

### What is the expected solution?

Add a min and max voting period similar to SX

**Comment by zzuziak** [comment]
@bonustrack shall we open it to the contributors?
