### ISSUE TITLE
[NEW FEATURE] - Include timestamp for each proposal in proposals page

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3426]
### Briefly describe the feature.

It is hard to guess when these proposals are posted unless we open each proposal

### Which problem is this feature trying to solve?

![Screenshot 2022-12-31 at 6 09 42 PM](https://user-images.githubusercontent.com/15967809/210137054-7a0ae751-1ff3-439c-85d0-3c5a41284231.png)

### What is the expected solution?

Include `created` timestamp or `end` timestamp somewhere in proposal card

**Comment by wa0x6e** [comment]
Proposing the following solution

![Screenshot 2023-04-13 at 3 06 37 PM](https://user-images.githubusercontent.com/495709/231740417-d06ccfad-9bbc-4f5b-9756-10b5716cebc4.jpg)

Adding a relative date, depending on the proposal status:

- When PENDING: 'Starting in xxx hours'
- When ACTIVE: 'Closing in xxx days'
- When CLOSED: 'Closed xxx weeks ago'

hours/days/weeks time unit will depend on the date itself, and just mentioned as an example.

- When hovering on the date, it will show a tooltip with the full ISO8601 formatted date.
- Relative date will requires an additional library such as dayjs

**Comment by samuveth** [comment]
@wa0x6e sounds good! Assigned the issue to you
