### ISSUE TITLE
[BUG] - Text formatting issue when creating new space on demo.snapshot.org

### ISSUE THREAD

**Issue by zzuziak** [snapshot-labs/snapshot#3438]
### Briefly describe the bug.

The ENS domain name is not formatted properly on the demo.snapshot.org, works properly in production

### How can we reproduce the bug?

1. Click on `+` on left sidebar to create a new space on https://demo.snapshot.org
2. Click `Get started`
3. Check if you ENS domain name is properly formatted

### What is the expected behaviour?

The ENS name should be human readable.

### Can you attach screenshots?

![image](https://user-images.githubusercontent.com/39556343/211402730-e7edd7df-c478-49fb-a842-bd9510d2f60e.png)

### Can you provide your device specific details below?

1. Device Type - Desktop
2. Device OS - Linux
3. OS Version - PopOS
4. Browser - Firefox

**Comment by ChaituVR** [comment]
@zzuziak I can't reproduce 🤔 Ens are human-readable for my address, Can share your address?

**Comment by zzuziak** [comment]
It's an error coming from ENS, thanks @ChaituVR for figuring it out!
