### ISSUE TITLE
[NEW FEATURE] - My voting power section in proposals page

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3439]
### Briefly describe the feature.

I should be able to see my voting power of a space (if i connect my wallet)

### Which problem is this feature trying to solve?

It is confusing many users, they were unsure if they have voting power to vote on future proposals

### What is the expected solution?

- [ ] Need design
- [ ] A separate my voting power section in the proposal page
- [ ] Use the `vp` query from the hub to get the latest voting power
- [ ] Use the latest block with 100 intervals like 1838300, 1838400, etc so we can use cache (Need change in hub to accept `block` param in `vp` query)

**Comment by vovesis** [comment]
I don't understand how often the pictures are taken? and when I can vote

**Comment by zzuziak** [comment]
Related to #1113 which touches the same problem but within the space page
