### ISSUE TITLE
Display all voting validations

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3452]
### Briefly describe the bug.

Right now we display only Anyone can vote validation and passport validation, but we should display all validations coming from https://score.snapshot.org/api/validations (example basic validation is missing) we should only hide passport-weighted

### How can we reproduce the bug?

1. Go to any space (example: https://snapshot.org/#/thanku.eth/settings) open voting validations
2. You will see "Anyone can vote" and "Gitcoin passport gated" 
![Untitled](https://user-images.githubusercontent.com/15967809/214127599-a5ccba93-5393-4f46-9d03-cd86ae8e7cfe.png)
This is hardcoded somewhere, It should actually show all the validations coming from https://score.snapshot.org/api/validations
4. For example `Basic` validation is missing
(Note: "Anyone can vote" is not the same as "Basic" validation, we should have both)
5. We will add more validations to this list, so all of them should be visible on UI, (except `passport-weighted`)

**Comment by zzuziak** [comment]
Also from what I understood from @bonustrack validations should be exactly the same for proposal creation and voting, so it needs a change in UI for both :pray:

**Comment by ChaituVR** [comment]
@zzuziak @bonustrack For "same" do you mean the same list of validations or the same interface?

**Comment by bonustrack** [comment]
@ChaituVR Same list

**Comment by samuveth** [comment]
@bonustrack @ChaituVR @zzuziak 

> Also from what I understood from @bonustrack validations should be exactly the same for proposal creation and voting, so it needs a change in UI for both 🙏

This doesn't seem to be the case, as we are maintaining two separate list:
- https://github.com/snapshot-labs/snapshot-strategies/tree/master/src/validations
- https://github.com/snapshot-labs/snapshot.js/tree/master/src/validations

**Comment by zzuziak** [comment]
I think the plan was to unify them into one and have the same list of validations both for voting and proposals. Correct me if I'm wrong @bonustrack.

Let's try to clarify all topics on that which should be addressed in the PR :pray:

**Comment by bonustrack** [comment]
That's correct. We should remove validations from Snapshot.js and use Score API to resolve validations using snapshot-strategies repositories. This will make Snapshot.js lighter

**Comment by samuveth** [comment]
@ChaituVR can you work on this? As you recently worked on vote validations you'd probably be the most familiar with it.

**Comment by samuveth** [comment]
Okay so I will just work on the showing all Validation from the endpoint and @ChaituVR will create another issue for the merge. ❤️

**Comment by ChaituVR** [comment]
Created an issue here for all other steps https://github.com/snapshot-labs/snapshot/issues/3466
