### ISSUE TITLE
Switch from eth_sign to personal_sign for login

### ISSUE THREAD

**Issue by snarflakes** [snapshot-labs/snapshot#3453]
### Briefly describe the feature.

using outdated account authentication signature with little info on signing

### Which problem is this feature trying to solve?

Improve trust to new users.

### What is the expected solution?

Switch signing from eth_sign to personal_sign type signature for improved readability.

### How do you currently handle this problem?

just trust signature request at this point

**Comment by samuveth** [comment]
Hi, which login are you referring to? We use EIP-712 TypedData for signing messages on snapshot, this includes improved readability already.

**Comment by snarflakes** [comment]
It was the edit profile signature, but i can check the others too. I can screenshot it too if need be. Thanks

**Comment by snarflakes** [comment]
![signing](https://user-images.githubusercontent.com/75555569/214454096-f4da9c92-5b0a-49c6-a51a-ecf98c1be1f7.jpg)

**Comment by snarflakes** [comment]
i guess they are just two different sign-in strategies...

![signing](https://user-images.githubusercontent.com/75555569/214454583-3d8faaff-9833-47bf-b04a-effbb6db2bc0.jpg)

**Comment by samuveth** [comment]
Okay, I see what you mean and I agree this should definitely be improved on our side. I will create an issue for it.
