### ISSUE TITLE
[BUG] - Can't see proposals of sub space on custom domain

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3455]
### Briefly describe the bug.

It works fine on snapshot.org but on custom domain

### How can we reproduce the bug?

Go to https://snapshot.org/#/morpho.eth , you will see the proposals from the subspace 
![Untitled 2](https://user-images.githubusercontent.com/15967809/214251696-d52d050a-6493-4383-9481-ac4f0e792d54.png)

But not on https://vote.morpho.xyz/#/

**Comment by samuveth** [comment]
@ChaituVR this is a bit of an architecture issue, it's a bit difficult showing proposals from another space on a subdomain currently. Do you have any suggestions how to solve it? We agreed with Fabien that redirecting to snapshot.org when opening a proposal from a sub-space isn't a good solution for custom domains.

**Comment by samuveth** [comment]
@ChaituVR I looked at it again and ended up finding an IMO acceptable solution.

**Comment by zzuziak** [comment]
@samuveth could you give more details on the solution you came up with? :pray: :blush:

**Comment by samuveth** [comment]
@zzuziak The PR is linked above with all the details. Basically I moved the space query into the proposal page, so that when a proposal from a sub-space is opened on a custom domain it will load the space after the proposal.
