### ISSUE TITLE
Support Binance Smart Chain wallet

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#346]
We should add support for Binance Smart Chain wallet in Lock.js so it's possible to use it on Snapshot.
https://github.com/snapshot-labs/lock

**Comment by samuveth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Binance wallet to Lock.js](https://trello.com/c/rfBgFjN2/73-add-binance-wallet-to-lockjs)
