### ISSUE TITLE
Validations Changes

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3466]
There are multiple things we need to do for validations

0. [x] [ui] Display all voting validations from the list https://github.com/snapshot-labs/snapshot/issues/3452
1. [x] [strategies] Move the title and description to validations instead of translations https://github.com/snapshot-labs/snapshot-strategies/pull/1046
2. [x] [ui] Use title and description instead of label and description in translations and also add a global `invalidVoterMessage` for all validations 
3. [x] [strategies] Create checklist and tests for voting validations similar to voting strategies
4. [x] [strategies] Migrate proposal validations from snapshot.js to snapshot-strategies (Code is a bit different in these repos) should have the same list for proposal and voting validations
5. [x] [hub] While creating a proposal - Should call the validation method for proposal validation (make sure old settings still work)
6. [x] [ui] Proposal Creation page - Should call the validation method for proposal validation (make sure old settings still work)
7. [x] [ui] Settings page - Display the same list for proposal validations and voting validations
8. [x] Remove legacy code from snapshot.js and hub or any other

**Comment by samuveth** [comment]
@ChaituVR, I've decided not to use the title and description from the validation object. I couldn't find a solution to use them for the input text and it didn't seem like a very clean solution overall.

**Comment by samuveth** [comment]
How is progress on merging old validations into strategies repo?

**Comment by samuveth** [comment]
@ChaituVR, You can use the PR #3558 for testing

**Comment by ChaituVR** [comment]
@samuveth Can close this if everything is ok from your side
