### ISSUE TITLE
[NEW FEATURE] - Share + Follow on Lens Protocol

### ISSUE THREAD

**Issue by fabriguespe** [snapshot-labs/snapshot#3471]
### Briefly describe the feature.

Add a share to Lens feature

### Which problem is this feature trying to solve?

Allowing people to share in web3 social their activity on Snapshot as well as following other users via their Lens profiles.

### What is the expected solution?

Here is more details with integration guidelines

https://docs.lens.xyz/docs/integrating-lens#share-to-lens

### Anything else you'd like to mention?

Video made by Nader 
https://www.youtube.com/watch?v=lUJs63xILR8

**Comment by samuveth** [comment]
@fabriguespe You can already share proposals and that you voted on a proposal to Lenster. I'm not sure I understand, can you elaborate on what else you would like to see.
