### ISSUE TITLE
[NEW FEATURE] - Allow ens controller to be space controller if snapshot text record doesn't exist

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3472]
### Briefly describe the feature.

Move away from iPNS to store settings

### Which problem is this feature trying to solve?

Original discussion: 
https://discord.com/channels/955773041898573854/1031838169282392144/1067181381479837786

Conditions to get controller of the space:
- If the `snapshot-controller` text record is set, the address value will be the controller
- If the `snapshot` text record is set and in IPNS format (`ipns://storage.snapshot.page/registry/<controller_address>/<space-id>`
), then `controller_address` will be the controller 
- If there are no `snapshot` or `snapshot-controller` text records, the Default ENS controller will be snapshot space controller

List of tasks:
- [x] [UI] Settings page check the above conditions to get the controller of the space
- [x] [UI] https://snapshot.org/#/setup/<SPACE_ID>?step=2 setting controller should set snapshot text record as an address
- [x] [Sequencer] Check the above list to get the controller of the space

**Comment by samuveth** [comment]
> [UI] https://snapshot.org/#/setup/<SPACE_ID>?step=2 setting controller should set snapshot text record as an address

@bonustrack just the address or like you said on discord like this `snapshot-controller=0x123`?

**Comment by bonustrack** [comment]
@ChaituVR There is also the case where the record is an IPFS url (technically it could also be a JSON from external API too)

@samuveth On Discord I mean that the text record param would be "snapshot-controller" and the value would be the address. But actually we could keep using the "snapshot" TEXT record for both case.

**Comment by samuveth** [comment]
@ChaituVR Ui is getting very close to completion. Can you make the sequencer work?
