### ISSUE TITLE
[NEW FEATURE] - Have more cooperation with Lens, thank you

### ISSUE THREAD

**Issue by Farshid962424** [snapshot-labs/snapshot#3491]
### Briefly describe the feature.

A person who participates in voting has a collection of his vote

### Which problem is this feature trying to solve?

Have a badge for someone who participates in very important voting

### What is the expected solution?

I said that I have given a comment, otherwise everything is great, thank you😍😎

### How do you currently handle this problem?

Everything is fine

### Anything else you'd like to mention?

Not hoping for more success

**Comment by samuveth** [comment]
Unclear what the request here is. Feel free to reopen with more details
