### ISSUE TITLE
[BUG] - Snapshot doesn't recognise an address as safe with Safe's walletconnect

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3518]
### Briefly describe the bug.

Can't vote with safe's walletconnect

### How can we reproduce the bug?

1. Go to snapshot.org
2. Connect wallet with safe's wallet connect, 
3. You will see "Join" button is not disabled
4. When we vote on a proposal, it sends a request to the sequencer, instead, it should send a request to relayer

### What is the expected behaviour?

It should send a request to the relayer when we vote. 

Atleast should display some error message, 
or alternative ways to detect safe or not:
- use safe's API
- In the worst case, detect if the address is a contract

**Comment by samuveth** [comment]
Fixed https://github.com/snapshot-labs/snapshot/commit/2e8b247e6aac3c2beb66f3cd717c2cd4c4f56f56
