### ISSUE TITLE
[BUG] - docs link for bug reports bypasses issue type choice and templates

### ISSUE THREAD

**Issue by sparr** [snapshot-labs/snapshot#3524]
### Briefly describe the bug.

snapshot-docs contribute.md links to snapshot/issues/new without /choose

### How can we reproduce the bug?

1. Go to https://github.com/snapshot-labs/snapshot-docs/blob/master/contribute.md
2. Click on https://github.com/balancer-labs/snapshot/issues/new
3. Observe blank issue creation form

### What is the expected behaviour?

Link goes to https://github.com/balancer-labs/snapshot/issues/new/choose for selecting a template

PS: Also, this file hasn't been updated since 2020, and is not accessible on the published docs site. It should probably just be archived or deleted.

**Comment by ChaituVR** [comment]
@zzuziak Can take care of this?
