### ISSUE TITLE
[BUG] - Can't connect wallet in brave browser

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3538]
### Briefly describe the bug.

Can't connect a wallet in brave browser

### How can we reproduce the bug?

1. Go to snapshot.org
2. Click on "Connect wallet"
3. select "Metamask"

See this error 
<img width="648" alt="Untitled 2" src="https://user-images.githubusercontent.com/15967809/222080019-e4049c3d-18d6-42e8-abed-c78a312f6c60.png">

### What is the expected behaviour?

Should be able to connect and vote

**Comment by samuveth** [comment]
Related to https://github.com/snapshot-labs/lock/issues/61

**Comment by samuveth** [comment]
I'm unable to replicate the issue at the moment. However, please feel free to reopen the issue if it persists.

I've also made [changes](https://github.com/snapshot-labs/lock/commit/cd35a108abacbbb3610694555c24fdcf085e0c4f) to add Brave as a injected connector to Lock package.

https://www.loom.com/share/4ce7802adb2b420aa395bd5f0167db6f

**Comment by ChaituVR** [comment]
Weirdly I can still reproduce, 

This issue was created because https://discord.com/channels/707079246388133940/1079727604615094354

**Comment by samuveth** [comment]
@ChaituVR can you provide more information. Like your Brave version, OS & version?

**Comment by samuveth** [comment]
Also could you make a video of the whole flow?

**Comment by ChaituVR** [comment]
Brave version: [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64)](https://brave.com/latest/)
OS: Mac OS Ventura (13.2.1)
Flow: https://user-images.githubusercontent.com/15967809/222885798-d6f9c682-621b-475d-9113-51063420c790.mp4

**Comment by samuveth** [comment]
@ChaituVR Thanks, can you open your Brave wallet and take a screenshot like this please. 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/51686767/222887559-c6c1875d-99af-426b-a3b3-34f39eeb40a3.png">

**Comment by samuveth** [comment]
Ah nevermind, with the latest version 1.48 I also get the same error.

**Comment by samuveth** [comment]
Created an [issue](https://github.com/brave/brave-browser/issues/28896) with Brave as it seems to only affect latest version.

**Comment by samuveth** [comment]
There is a fix for this coming from Brave. Should be live soon!

**Comment by samuveth** [comment]
Can no longer reproduce
