### ISSUE TITLE
[BUG] - Share on lenster button not working on windows 

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3540]
### Briefly describe the bug.

If we click on " Share on Lenster" button. it open windows share option

### How can we reproduce the bug?

1. Go to any proposal,
2. vote on it, on the vote success model, click on " Share on Lenster" button
3. On mac, it redirects to `https://lenster.xyz/?text=....`
4. But on windows it opens a "windows share modal" like below:
5. 
<img width="619" alt="Untitled 3" src="https://user-images.githubusercontent.com/15967809/222244497-b358c4bb-e298-4200-bccd-77f52f38a1ef.png">

### What is the expected behaviour?

It should work the same as on mac

**Comment by samuveth** [comment]
Hot fixed [here](https://github.com/snapshot-labs/snapshot/commit/2f9c384ab11a1a1856902fb1f85ea53024428e78)
