### ISSUE TITLE
[BUG] - Can't delete proposal body if proposal template is enabled 

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3542]
### Briefly describe the bug.

If a space have a proposal template, It is not allowing us to delete it, unless we type in some other body

### How can we reproduce the bug?

1. Go to https://snapshot.org/#/thanku.eth/create/0
2. Remove the template from the `Description (optional)` field
3. Click on "Continue" 
4. Click on "back"
5. You can see that template is back
6. Also instead of clicking "back" you can continue to post a proposal, the proposal will contain the text instead of empty `body`

### What is the expected behaviour?

If the user clears out the description field, the template should not be added back

### Can you attach screenshots?

![Mar-02-2023 02-20-33](https://user-images.githubusercontent.com/15967809/222262105-d05790b4-3d78-4c75-82c2-c7ac4295fd39.gif)

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/commit/a9bfc56d526f472643e0bac95cd63e5fdbac24df
