### ISSUE TITLE
tx not popping up in gnosis safe wallet connect tab and the following errors are visible

### ISSUE THREAD

**Issue by gabkov** [snapshot-labs/snapshot#3547]
<img width="1864" alt="image" src="https://user-images.githubusercontent.com/38463744/222677840-ae4f8d98-74d2-427d-a815-f898f0634624.png">

**Comment by samuveth** [comment]
Space creation with a Gnosis safe is currently only supported on Ethereum mainnet and snapshot.org

**Comment by gabkov** [comment]
> Space creation with a Gnosis safe is currently only supported on Ethereum mainnet and snapshot.org

any plans to add support for polygon?
