### ISSUE TITLE
[BUG] - Security Bug

### ISSUE THREAD

**Issue by youranonone1** [snapshot-labs/snapshot#3557]

**Comment by youranonone1** [comment]
Looks like you are not interested, i am closing the issue 

Thanks.

**Comment by samuveth** [comment]
@youranonone1 You can message `fabien#0001` on Discord

**Comment by youranonone1** [comment]
Done, You can dm him to check the  pending message  requests. 

Thanks.

**Comment by samuveth** [comment]
@youranonone1, thanks,he will be available and get to you later today.
