### ISSUE TITLE
[BUG] - Link to proposals from a space are broken

### ISSUE THREAD

**Issue by spalladino** [snapshot-labs/snapshot#3564]
### Briefly describe the bug.

Given a space without a custom domain, clicking on a proposal from its space's page goes to an invalid link and redirects to home.

### How can we reproduce the bug?

1. Go to https://snapshot.org/#/council.graphprotocol.eth/
2. Click on any proposal
3. Get redirected back home

### What is the expected behaviour?

Should redirect to the proposal. The problem seems to have been introduced in https://github.com/snapshot-labs/snapshot/commit/3f1be3f9d9d99f18a289b63ee42f294667273de9, which caused links now to be `https://snapshot.org/#/council.graphprotocol.eth/council.graphprotocol.eth/proposal/0x6dd02b4ab3a388628104b48a792b7db8dfe0cc1a93e8b7f5952fd4f7a1d2aa79` (note the duplicated space name).

**Comment by samuveth** [comment]
@bonustrack this is super weird, I can not reproduce this bug on any other space.
