### ISSUE TITLE
Add search bar for proposals

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3576]
We should add a search bar on the space page to search for proposals

**Comment by samuveth** [comment]
Needs design

**Comment by samuveth** [comment]
@j0hnfl0w, could you please draft and outline some ideas on how you would implement this feature? Once we have a consensus on the approach, we can proceed with the implementation. For the time being, let's focus on incorporating this feature solely for the space page.

**Comment by samuveth** [comment]
By the way you can use GPT for creating layouts pretty easy like this. Just describe the layout and ask it for a "ASCII representation` of it.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/51686767/228413573-f5f97be5-d74f-49e1-9a95-d7dd54ddcf2c.png">

**Comment by samuveth** [comment]
@j0hnfl0w looks good, and how are we going to conduct the search, does the gql query support search by name?

**Comment by j0hnfl0w** [comment]
Yeah we can search with title_contains query where field. So do we have a consensus on the approach?

**Comment by samuveth** [comment]
> Yeah we can search with title_contains query where field. So do we have a consensus on the approach?

@bonustrack anything to add?
