### ISSUE TITLE
Add delete button to danger section

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3580]
Requires https://github.com/snapshot-labs/snapshot-hub/issues/563

**Comment by ChaituVR** [comment]
@samuveth There is new action `delete-space` working on the sequencer now :) Try with test space or testnet and let me know if you have any question

**Comment by j0hnfl0w** [comment]
@ChaituVR i deleted my space j0hnfl0w.eth, and then i want to create space again with the same ENS, but there is an error "Oops space deleted contact admin"

**Comment by ChaituVR** [comment]
Yep, there is no easy way to get it back 🙈 maybe we should display a big notice before deleting a space, for this space send a message to Fabien to restore

**Comment by j0hnfl0w** [comment]
yeah i see this https://github.com/snapshot-labs/snapshot-sequencer/pull/34/files#diff-2287ca9720852dc187de1049fb533746832d76ce3eddb56e79241c382663e5d6R19
So if we soft-delete a space maybe we can "restore" it?

**Comment by j0hnfl0w** [comment]
@ChaituVR still, how to create any space after deletion? i want to use the same ENS but another space name

**Comment by samuveth** [comment]
@j0hnfl0w you can not create a space with the ENS from the old space. @ChaituVR do we have way to query deleted spaces, because now I can see the ENS of my deleted space on the space creation page.

**Comment by hjjlxm** [comment]
While it's tricky to restore a deleted space considering a range of factors, at present, I think we should stress on the UI that "You cannot create a new space **with the same ENS domain name from old spaces"**

Many users don't know that one ENS can only be used once in this situation, thinking it's just deleting the archived data and they can start a fresh one with the same ENS. Though it's well documented on the official doc:

![delete doc](https://user-images.githubusercontent.com/31681895/233447704-1e75c4af-6334-48f9-b18a-a96d25cade54.png)


But I suggest we also highlight the ENS point on the UI in case of misunderstanding from users, and may also improve on the error message accordingly. cc @samuveth @ChaituVR @j0hnfl0w 
![delete confirm modal](https://user-images.githubusercontent.com/31681895/233446629-709527a4-4e84-442a-a89b-48c2495c9c7a.png)


![error msg](https://user-images.githubusercontent.com/31681895/233447332-28dabe35-5573-41e2-b76b-681997eb10ee.png)
