### ISSUE TITLE
[BUG] - Should not open vote modal if proposal is closed

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3587]
### Briefly describe the bug.

While clicking on discord bot's notification, it open vote modal even if proposal is closed

### How can we reproduce the bug?

1. Go to https://snapshot.org/#/nation3.eth/proposal/0x11bf523d181288e7d7a4afdbee2ecdf01057f8c72848fd6a258916c6248bf2c0?choice=1
2. You should see vote below like here
3. <img width="478" alt="Untitled" src="https://user-images.githubusercontent.com/15967809/225385483-0b99f867-3cfb-4674-a61d-db9fd66326a5.png">

### What is the expected behaviour?

Should not display modal in this case

**Comment by samuveth** [comment]
Fixed https://github.com/snapshot-labs/snapshot/commit/02279c046a0fed2240319f76cf8e1b01d49473e2
