### ISSUE TITLE
feat: support search by vote with .lens

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3631]

**Comment by samuveth** [comment]
@j0hnfl0w I don't think we need apollo for that.

**Comment by j0hnfl0w** [comment]
@bonustrack @samuveth where we can find votes from .lens? Do we even resolve .lens profiles in search results?

**Comment by samuveth** [comment]
> @bonustrack @samuveth where we can find votes from .lens? Do we even resolve .lens profiles in search results?

No we don't, we will do a single API call like when resolving the .eth, if you can't find it in the lens protocol docs we can ask them on their discord.

**Comment by samuveth** [comment]
> I mean we want to search with .lens, but we don't show .lens, only `'eth', 'xyz', 'com', 'org', 'io', 'app', 'art'`

`.lense` is not ENS related

**Comment by j0hnfl0w** [comment]
I already found how to resolve in [lens docs](https://github.com/snapshot-labs/snapshot/issues/3631#issuecomment-1482544597)
