### ISSUE TITLE
Why I can't vote?

### ISSUE THREAD

**Issue by AhmetKrl01** [snapshot-labs/snapshot#3638]
Hello,

I staked 134 STG but I didn' vote proposal. On the https://stargate.finance/stake page, I can see 134 veSTG but when I vote on the snapshot page I see 0 veSTG.
![STG Stake](https://user-images.githubusercontent.com/128744575/227768745-de7c0bde-24af-4a0d-8ac4-a11b4a9c0196.png)
![Vote](https://user-images.githubusercontent.com/128744575/227768755-c04cb322-3a99-4352-bc02-a615ce22e15c.png)

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/discussions/767

**Comment by AhmetKrl01** [comment]
Because of my voting power is 0 , I didn't vote on snapshot. But normally I have voting power.
