### ISSUE TITLE
[BUG] - Votes search

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3641]
### Briefly describe the bug.

I found couple of minor issues/enhancements in votes search

### How can we reproduce the bug?

1. Go to any proposal, for example, https://snapshot.org/#/safe.eth/proposal/0xb4765551b4814b592d02ce67de05527ac1d2b88a8c814c4346ecc0c947c9b941

Issues:
1. [ ] I see GraphQL is being called twice, while we are always searching vote with the address result will be always one vote right? is there some reason for calling twice? Maybe we could use the `vote` query instead of the `votes` query?
Video: https://user-images.githubusercontent.com/15967809/227794020-658dda07-7a5f-4ff2-891b-a34891133909.mp4

2. [ ] While searching with an ENS name, is there any reason to call node three times, here we call the votes query once ( which is expected for the above case too ) 
<img width="1220" alt="Untitled" src="https://user-images.githubusercontent.com/15967809/227794267-b52be15f-684e-4583-8942-7b47310aa287.png">

3. [ ] Searching with address should not be case sensitive, for example, try address with all upper case, example try searching with `0XC4CA987CE6F0D2F9442A294AA85AD5D14D43153B` and then with `0xC4CA987Ce6f0d2F9442A294Aa85aD5D14d43153B` 
while searching with checksum and all lowercase are working but uppercase and mixed case are not working
![Mar-26-2023 23-27-49](https://user-images.githubusercontent.com/15967809/227794857-41b7225e-3f53-402e-980a-183d74d295bf.gif)

4. [ ] While typing any text with length `>= 3` can we add `.eth` at the end and search? I mean like when we type `shot` we should resolve with `shot. eth` and search API with the address, while this is cool, it can increase the number of calls to node and API 😄 should that be fine? if not we can ignore this, Any thoughts on this @bonustrack @samuveth @j0hnfl0w 
<img width="492" alt="Untitled 2" src="https://user-images.githubusercontent.com/15967809/227795309-625c0095-9696-4dff-bac1-1bb8454f7149.png">

**Comment by j0hnfl0w** [comment]
https://github.com/snapshot-labs/snapshot/issues/3631 we also need to search with .lens, so how we gonna append .eth  and .lens to search?

**Comment by ChaituVR** [comment]
Maybe we can search with both in the background but the search field will display the original keyword (`shot` for example, will search with both `.eth` and `.lens` in the background) In this case we can use `voter_in` in `votes` query 

if the user types `.eth` or `.lens` at end of the string we can check with only one

But this is just an idea, we can ignore this if we agree this can cause a lot of API calls

**Comment by samuveth** [comment]
Good points @ChaituVR, lets keep the ENS search simple for how and only resolve with full ens domain `.['eth', 'xyz', 'com', 'org', 'io', 'app', 'art']` or .lense

**Comment by j0hnfl0w** [comment]
- Reduced to one call when search by address, second call was from loadMoreVotes() from infinite scroll.
- We are resolving ens name with ```getProvider('1').resolveName(ens)``` from ```@snapshot-labs/snapshot.js/src/utils/provider``` and it makes these 3 calls don't know why. We call ```getProvider('1')resolveName(ens)``` only once.
- Searching with address now is not case sensitive - we can search mixed, uppercase, lowercase now.
- Searching for both .eth and .lens does not mean we a looking for one person vitalik.eth !== vitalik.lens so the search will return all vitaliks 😀.  To search with .lens we also need to show .lens handle for address otherwise there will be a case when we are searching with .lens and get results with .eth or just address.

**Comment by samuveth** [comment]
@j0hnfl0w we should not search/resolve anything if the input is not ending with a valid Tld `'eth', 'xyz', 'com', 'org', 'io', 'app', 'art' or '.lense'`

**Comment by j0hnfl0w** [comment]
Agreed we will just add .lens resolver

**Comment by j0hnfl0w** [comment]
Agreed we will just add .lens resolver
