### ISSUE TITLE
Improve DX with unplugin-auto-import

### ISSUE THREAD

**Issue by j0hnfl0w** [snapshot-labs/snapshot#3643]
We can get rid of importing from 'vue' and 'vue-router' with  [unplugin-auto-import](https://github.com/antfu/unplugin-auto-import), just like we do with unplugin-vue-components and unplugin-icons.

**Comment by samuveth** [comment]
Oh and also ref,computed ect. we can do this and composables with https://github.com/antfu/unplugin-auto-import
