### ISSUE TITLE
More E2E tests

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3668]

**Comment by samuveth** [comment]
@wa0x6e @j0hnfl0w do you think we should create or use a mock backend to expand our end-to-end testing capabilities?

**Comment by samuveth** [comment]
At the moment, we are using production spaces with distinct configurations for testing. However, I have concerns about the scalability and effciency of this approach in the long run
https://github.com/snapshot-labs/snapshot/blob/develop/cypress/e2e/create-proposal.spec.cy.js

**Comment by wa0x6e** [comment]
Current tests are relying on existing data on a tests server ? Or is that backend empty ?

**Comment by samuveth** [comment]
No, current tests that I linked are using the production HUB.

**Comment by wa0x6e** [comment]
You're testing proposal creation on the production hub ?

I don't find where you specify the hub url in your .env.test. Is the cypress test using the variables in .env also ?

**Comment by ChaituVR** [comment]
Agree! Ideally, test cases should use https://testnet.snapshot.org/

**Comment by samuveth** [comment]
> You're testing proposal creation on the production hub ?
> 
> I don't find where you specify the hub url in your .env.test. Is the cypress test using the variables in .env also ?

Yes, I understand, but that wasn't my main concern. At the moment, our E2E tests are set up minimally, and it just so happens that I have more hub spaces available for testing than testnet spaces. My primary question is whether we should create a local mock hub specifically for E2E testing purposes. This approach would enable us to test various scenarios without needing to configure separate spaces for each individual case.

**Comment by samuveth** [comment]
For the tests to run you currently have to set it to hub in .env

**Comment by wa0x6e** [comment]
Either way, the more important point IMO is to have a test hub with preloaded and known data.

The difficulty now is that you're the only one able to write test, because you have knowledge of the test data in the hub.

If I wanted to add a test to, for example, test the votes sorting order, I couldn't, as for that, I would have to seed the db with my expected data first, which is impossible now.

The local mock hub way you're referring to, is that a real hub with seeded data instead of live one on the internet, or just mocked network response ?

**Comment by samuveth** [comment]
> If I wanted to add a test to, for example, test the votes sorting order, I couldn't, as for that, I would have to seed the db with my expected data first, which is impossible now.

Indeed, this is a significant issue with the current implementation.

> The local mock hub way you're referring to, is that a real hub with seeded data instead of live one on the internet, or just mocked network response?

As for the local mock hub, I'm referring to an actual offline hub with pre-populated data, rather than simply mocking network responses. There are numerous test cases involving various space settings, and I believe that having an offline hub with seeded data is essential for effectively testing those scenarios. Correct me if I'm wrong, but I don't see how we could comprehensively test these cases without implementing a solution like this.

**Comment by wa0x6e** [comment]
Local hub with prepopulated data is my choice.

I guess we will also have to have a local score api, avatar, and all the
dependent services?

Would a container solution be more friendly?

**Comment by samuveth** [comment]
Ideally, we should begin with setting up the hub first no? If you believe that using a container would be beneficial, I trust your judgment

**Comment by wa0x6e** [comment]
I am not familiar enough with the whole stack to have a truly useful opinion.

My opinion is solely based on what I am seeing these past 2 weeks. 
Booting a working instance of this repo is dependent on all the backend instances.
Per my understanding, the hub, sequencer, score-api, ipfs gateway are all required  for a local instance of this repo to be working.

Those requirements are currently met, as the base .env uses online backend.

Are you intending to mock all these services as well, or just the hub ?

**Comment by samuveth** [comment]
Yes, good question. My experience with testing and mocking is limited, so I might not be the best person to make the call. We could potentially benefit more from focusing on component testing or end-to-end testing without making any requests.
