### ISSUE TITLE
Filter votes with reason

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3677]
In the votes modal, it would be beneficial to include a filter dropdown menu or a list beneath the search bar with selectable checkboxes. Please create the design mockups for us to review and approve prior to starting the implementation process.

For the "reason" filter, we may need to make adjustments to the API as well.

Additional filter options to consider include sorting by ascending voting power, descending voting power, and by choice. Are there any other filtering criteria you would like to include?

**Comment by j0hnfl0w** [comment]
![Frame 2](https://user-images.githubusercontent.com/97898172/230015479-6c53c9c7-78b7-4020-9d86-81e8955a72c8.png)
@samuveth @bonustrack

**Comment by j0hnfl0w** [comment]
used toggle cos i haven't found use of InputCheckbox component anywhere :D

**Comment by samuveth** [comment]
> yeah reason filter is missing, so we need to search on a text field reason = "Response from TreasureDAO shared here: https://forum.arbitrum.foundation/t/aip-1-arbitrum-improvement-proposal-framework/30/154?u=karelvuong" like fulltext search using the same text input for ENS/address or one more input? Or we need full-text search by ENS/address OR by reason?

No, we should just have a checkbox to only show votes with a reason.

**Comment by samuveth** [comment]
I believe it would be more efficient to combine the onlyWithReason, choices, and voting power (ascending and descending) options into a single dropdown menu.

**Comment by j0hnfl0w** [comment]
![Frame 3](https://user-images.githubusercontent.com/97898172/230570413-23215c47-62f0-47e7-82de-e70b4d8ac9f0.png)

**Comment by samuveth** [comment]
I'm not very sure about the "Voting power asc" part, but could work!

Any thoughts on the design? @bonustrack

**Comment by samuveth** [comment]
Since @bonustrack isn't responding, we will move forward without his input.
