### ISSUE TITLE
[BUG] - Broken keyboard navigation

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/snapshot#3707]
### Briefly describe the bug.

Not a serious bug, more of an UX issue: the keyboard navigation seems broken in some part of the site

### How can we reproduce the bug?

1. Go to the homepage
2. Use the keyboard `TAB` key to scroll through the links

- You will notice that some links are focused twice: this is because some `<button>` element are nested inside another `<button>` or `<a>` (both are not valid HTML5). This is the case for all links/buttons with a popover.
- You will also notice that sometime, the focus disappear, because the focused element does not have a focus style.
- The space links in the left sidebar are never focus-able with keyboard navigation, as they are neither `<button>` nor `<link>` element.
- The invalid html also seems to break the tab navigation inside the popover. `TAB` never go inside the popover, even though it should be supported, as described in the headlessui docs.

### What is the expected behaviour?

Navigating the page links with the keyboard should jump/focus from one link to the next, and not skip any links, nor focus the same link twice (because of nested `button`/`a`).

Keyboard navigation should also be able to navigate inside popover content.

One way to fix that will be to slap `tabindex="0|-1"` anywhere there's an issue, but the most appropriate fix will be to remove the nested `button`/`a` whenever possible, by maybe editing the <ButtonSidebar> to return a div/other element if asked via props (`as:`), instead of a button

### Can you provide your device specific details below?

This is reproducible from any desktop browser

**Comment by wa0x6e** [comment]
Should I go ahead with a PR ?

**Comment by samuveth** [comment]
@wa0x6e yes please
