### ISSUE TITLE
[BUG] - Intermittent issue with SafeSnap proposal creation when switching between Ethereum mainnet and Goerli

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3713]
### Briefly describe the bug.

Users are experiencing an intermittent issue with proposal creation with SafeSnap when switching between Ethereum mainnet and Goerli network in Metamask. It seems that proposal creation sometimes works when connected to Goerli, but not always. It also works on the mainnet when the user switches networks and reloads the page.

### How can we reproduce the bug?

1. Connect Metamask to Ethereum mainnet or Goerli network.
2. Attempt to create a proposal.
3. If the proposal creation fails, switch networks in Metamask.
4. Reload the page and start proposal creation from step one.

https://snapshot.org/#/outcomefinance.eth/proposal/0x35ed1d522e052f91019e2ae2369c8de27c016de77d841ae2197706c9bd2e3094

### What is the expected behaviour?

Users should be able to create proposals without issues, regardless of the network they are connected to.

**Comment by pemulis** [comment]
Just to add a note to this, I was able to create one new proposal when connected to Goerli but not when connected to mainnet, after switching and reloading. The `Publish` button is grayed out when connected to mainnet, after deleting locally cached application data, re-connecting to a mainnet wallet, and going through the new proposal flow.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/1646497/230439988-eff27a8e-13ab-4a12-848f-896e460b6b7c.png">

I haven't been able to create a new proposal consistently when connected to Goerli, and haven't been able to create a new proposal at all when connected to mainnet.

**Comment by libdefi** [comment]
Thank you for creating the Issue! I'm having the same issue and can't seem to hit “Publish".

**Comment by samuveth** [comment]
@libdefi Can you still reproduce the issue after refreshing the page?

**Comment by pemulis** [comment]
After clearing my browser data and restarting, I was able to create several proposals without any issues. I created proposals while connected to Ethereum mainnet and Goerli, with and without transactions, and using a variety of voting schemes.
