### ISSUE TITLE
[BUG] - Error fetching collectables, Transfer NFT list is empty

### ISSUE THREAD

**Issue by volkyeth** [snapshot-labs/snapshot#3723]
### Briefly describe the bug.

The list of NFTs from treasury is empty on "Transfer NFT" transactions

### How can we reproduce the bug?

1. Go to a space that has NFTs in its treasury (Gnosis Safe treasury)
2. Start creating a new proposal
3. Advance to the "Transactions" step
4. Add a "Transfer NFT" transaction

### What is the expected behaviour?

Asset list should be filled

Instead it's empty

### Can you attach screenshots?

![image](https://user-images.githubusercontent.com/847070/230736563-c4503a40-dfd5-46dc-8f79-ae6f02f8c32d.png)

The safe in the screenshot is https://app.safe.global/home?safe=eth:0x0658f4eD17289144717713ADfFC2539eF7c2EF8e
It has several NFTs in it

### Can you provide your device specific details below?

1. Device Type - Desktop
2. Device OS - MacOS
3. OS Version - Ventura 13.1
4. Browser - Chrome
5. Browser Version - 111
6. Wallet - Frame
7. Space - Gnars
8. Any additional information we should know:

dev console displays the error: `Error fetching collectables`
There's a failed (404) request to https://safe-transaction-mainnet.safe.global/api/v1/safes/0x0658f4eD17289144717713ADfFC2539eF7c2EF8e/collectibles/
(bc the endpoint is actually on api/v2, as per https://safe-transaction-mainnet.safe.global/)

**Comment by ChaituVR** [comment]
Correct, `collectibles` work on v2 and `balances` work on v1
we should find `collectibles` equivalent on v1

**Comment by ChaituVR** [comment]
Looks like there is no equivalent from [here](https://safe-transaction-mainnet.safe.global/), should use v2, will create a PR

**Comment by volkyeth** [comment]
Although the request goes through now (I can see the successful request to collectibles endpoint on the network tab), the transfer NFT list does not render:
![image](https://user-images.githubusercontent.com/847070/233326326-a09234d6-1f60-40c3-9107-7bb2cb041c9d.png)

There's this error on the console:
```
dex.98ad2d18.js:6 TypeError: Cannot read properties of null (reading 'address')
    at index.98ad2d18.js:855:85706
    at renderList (index.98ad2d18.js:6:71772)
    at index.98ad2d18.js:855:85612
    at Ce (index.98ad2d18.js:6:49070)
    at renderSlot (index.98ad2d18.js:6:72428)
    at index.98ad2d18.js:855:66899
    at Ce (index.98ad2d18.js:6:49070)
    at renderSlot (index.98ad2d18.js:6:72428)
    at Proxy.<anonymous> (index.98ad2d18.js:353:98021)
    at renderComponentRoot (index.98ad2d18.js:6:49537)
    (...)
```

**Comment by ChaituVR** [comment]
Hi @volkyeth Can share your space URL? If it is private info, can DM me on discord at `ChaituVR#7400`

**Comment by ChaituVR** [comment]
Thanks @volkyeth Fixed it here https://github.com/snapshot-labs/snapshot/pull/3802

**Comment by ChaituVR** [comment]
There is one more issue, it is not showing all collectables, will fix it soon
