### ISSUE TITLE
Proposal protection and prevention mechanism

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3724]
Objective: To develop a comprehensive protection and prevention mechanism for users that effectively identifies, reports, and manages potential problematic proposals on the platform.

## Flagging System:

1. Store flagged proposal IDs within the snapshot-spaces submodule in `proposals.json`.

## Warning System:

1. Display a warning modal with prominent danger warning signs for flagged proposals.
2. Require user confirmation before allowing access to view the flagged proposal.
3. Provide a brief explanation of why the proposal has been flagged and the potential risks involved.

## Types of Flags for Problematic Proposals:

1. Scam: Proposals that attempt to deceive users or steal funds.
2. Spam: Proposals containing excessive and irrelevant content aimed at self-promotion or disrupting the platform.
3. Offensive Content: Proposals that include hate speech, harassment, or any form of offensive language.
4. Duplicate Proposals: Proposals that are identical or strikingly similar to existing proposals, leading to resource waste and user confusion.

## Reporting System:

1. Introduce a "Report Proposal" button, which opens a form for users to report problematic proposals.
    - The form should include a dropdown menu for users to select the reason for reporting (e.g., scam, spam, offensive content, duplicate proposal).
    - Users should also be able to provide additional comments or details to support their report.
2. Create a user-friendly form that gathers essential information about the problematic proposal.
3. Notify Snapshot moderators via an internal-only Discord channel (#reports) when a proposal is reported by users or flagged by the external monitor. This notification should contain the user report and the specific reason for the flag.
4. Develop an external monitor that checks proposals for flagged words and reports them to the Discord channel.

**Comment by hjjlxm** [comment]
Supplement ideas
---
Abstain on the flagging and warning systems, this may lead to another type of attack on normal proposals.
### Prevention:
When the token price drops 10x, the cost of the proposal attack has become incredibly low. We may show a confirmation modal highlighting some key params like **proposal threshold** before the space admin sign the message when change settings.

### Reporting system:
Agree that Reporting can be done permissionlessly through filling a simple form: **type-reason** by any users.

Have other ideas about the notification: when the report is triggered, the alert should be sent to the space admin or moderator's email/any integrated communication tool so they're the first one who're aware of it and take needed action. Therefore we can make a place for the space members to set up their contact flow in settings.

Not sure how far Snapshot mods could do on notification of reported proposal. Snapshot has #report-scam channel which fits this situtation. Maybe we can integrate the message of reported proposal into this channel, or create another channel specifically for this kind of report for monitor purposes.

The report button may be added somewhere beside Share or hide in the three dot droplist.
![report](https://user-images.githubusercontent.com/31681895/230750886-d3829e5c-d8ce-47a6-9e2e-7792035a8b5d.png)

**Comment by samuveth** [comment]
@hjjlxm  Thank you for your input. I want to clarify that the flagging process is meant to be manual, initiated only after verifying reports from the #reports Discord channel. This manual review is done by us and reduces the chances of false flags or attacks on normal proposals. Additionally, we'll be using a more general channel called #reports instead of #report-scam to encompass all potential reasons for reporting, as listed.

**Comment by hjjlxm** [comment]
> @hjjlxm Thank you for your input. I want to clarify that the flagging process is meant to be manual, initiated only after verifying reports from the #reports Discord channel. This manual review is done by us and reduces the chances of false flags or attacks on normal proposals. Additionally, we'll be using a more general channel called #reports instead of #report-scam to encompass all potential reasons for reporting, as listed.

Got it, thanks for clarification. Flagging as a feature can be both applied to proposals or spaces which we're already doing now. While from the attack perspective, creating fake spaces costs more than creating malicious proposals, the latter could happen more frequently and in large amount than we deal with fake spaces. So doubt if we can handle it manually in time when there's flood attack. Maybe in long term we will provide spaces with advanced measures like approval by an moderator or admin before author submiting proposals.

**Comment by ChaituVR** [comment]
Nice idea, I think for now we can just add JSON with spam proposals that we can update manually,

Then I think we should use tally form and notion instead of custom solutions, and possibly should use Notion API to automatically add a warning something like "This proposal is reported spam many times, please be careful" 

Someone from the snapshot team should be able to update the notion once they review it. then we should show a different message

**Comment by hjjlxm** [comment]
As a sum for solutions we've got

![Scam prevention](https://user-images.githubusercontent.com/31681895/231082244-cc4fdaf9-6b07-45b1-98da-65fd690429fb.svg)

**Comment by samuveth** [comment]
The most pressing issues have been addressed or are coming [here](https://github.com/snapshot-labs/snapshot-sidekick)

Closing this issue and starting a pitch [here](https://www.notion.so/snapshotlabs/Better-Scam-Spam-Prevention-d2d107f8c5e5480ab19ad5b51761fbb1?pvs=4) with a link to this discussion.
