### ISSUE TITLE
Proposal flagging system (Part 1)

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3737]
Part of https://github.com/snapshot-labs/snapshot/issues/3724

1. Store flagged proposal IDs within the snapshot-spaces submodule in `proposals.json`
```json
{
  "0x21e21b3477bebf3525709631c38feb58476efaad39c9d5cbb43e976ed901e7b3": "scam",
  "0x21e21b3477bebf3525709631c38feb58476efaad39c9d5cbb43e976ed901e7b4": "offensive"
}
```

2. Display a confirmation modal for proposals flagged by the user. The confirmation modal should display text corresponding to the reason for flagging, allowing the user to review and approve before revealing the proposal details.

3. Hide the flagged proposal from both the timeline and proposals page.

### Open questions 
- [ ] 1. Integrators will receive flagged proposals through our API; could we introduce a query parameter to allow them to choose between filtered and non-filtered proposals?
- [ ] 2. Should we disable voting on flagged proposals?
- [ ] 3. Would it be beneficial to include a filter option on the proposals page, allowing users to view flagged proposals?

**Comment by samuveth** [comment]
### Issue:
Due to the increasing number of reports, which are estimated to be over 20 per day since yesterday, storing flagged proposals within the proposals.json file would quickly become unmanageable.

### Proposed Solution:

1. Develop a server (or integrate with HUB directly) that retrieves reported proposals from our Notion page and supplies them to our services. Direct usage of the Notion API in our services may not feasible due to the rate limit of 3 requests per second.
2. Add a new property to the proposal GraphQL query called "flagged." The value of this property will indicate the type of flag assigned to a proposal, such as scam, spam, offensive, or duplicate. Integrators can use this property to easily display a warning for flagged proposals.
3. Display a warning for flagged proposals on both the space proposals list and individual proposal pages. However, the deletion/hiding of proposals should be left to space admins and moderators.

### Additional Considerations:

1. Provide a way to inform space admins and moderators about flagged proposals so they can take action quickly.
2. To prevent abuse of the system, allow space admins and moderators to unflag a proposal if it was flagged erroneously.

**Comment by ChaituVR** [comment]
Quite tricky :sweat_smile:  ideally we should have a separate table in DB if this scam proposal thing go skyrocket

But we can't directly display a warning once someone reports, we should verify if it is spam or not OR we should check if the reports count of a proposal goes beyond a number

Maybe we can have this JSON on the hub instead of the UI if it increases the build size


@bonustrack What do you think? 
Would be nice if we have a place where we can communicate with space admins directly with emails/notifications when someone reports or other proposal activities

**Comment by samuveth** [comment]
I don't think it should be a file at all, because that would require a PR for each flag.

**Comment by samuveth** [comment]
We've implemented a [quick fix ](https://github.com/snapshot-labs/snapshot/commit/244d0891ffe62fde6e247bd5db3a1ffbfa645205) and will continue work on a longer term solution with a server and using Blockaid for automatic flagging

**Comment by hjjlxm** [comment]
Educating the spaces to raise their awareness of proposal threshold is one thing that we're going to do on articles.

Eventually, I think we'll have an **anti-spam system** to make it as effortless as possible for spaces to deal with this matter.

I partly agree with @ChaituVR 's proposals as below:

>-add a timeout/cool down of voting power (ex: hold voting power for 1 month to create a proposal
>-add blacklist of proposal authors

### Reasons
For voting, users are expected to be a holder of token cause they don't know when a new proposal will start; On the contrary, For proposal creation, anyone can launch a governance attack once they bought enough tokens on the market, which doesn't require him to be a holder of that token.

After investigation, most of the attacks are done by someone who utilized the flow of funds and leveraged the feature of ''snapshot'' mechanics on the proposal creation, which is somehow a vulnerable point we have.

To use this https://etherscan.io/address/0x2c8829427Ce20d57614c461f5b2E9ADa53A3dD96 as an example who spammed many spaces like Aave, Lido, Gitcoin, Paraswap... The key point is, these spaces already has somewhat decent threshold before the attack, but it cannot stop the spammer who can just sell out those thousands of tokens once finishing spamming. So **propopal threshold is not a real problem** in these cases.

It's all about raising the cost of attack while maintaining the governance process as inclusive as possible.

### Solution

I think it's about modifying our mechanics of checking VP on proposal creation.

I like the idea we introduce an anti-spam mode in proposal validation, which gives a set of time frames that spaces can choose to enforce the author to hold the token for a certain time before he can initiate a proposal, like 5 days, 15days or a month. 

> Check VP at a certain block from timeout (example check VP from a month ago)

By doing like this, we're replicating a lock-up mechanism like veCRV or veBAL. The difference is, we only give this option in spam mode that spaces themsleves can choose to turn it on or not. **The benefits are obvious**, we raised the cost of attack: the spammer cannot risk holding a bundle of tokens for a long time considerating the depreciation of token value. And it won't have much impact on the other authors: those who did good proposals often hold the tokens much longer than average users.

I believe this can largely reduce the amount of spam proposals for spaces that already have a normal threshold. Esp. those top 20 spaces, which is also the main target of attack.


And in case it won't work,

I think we'll have a **blacklist pool**, for those who ever launched malicious spaces or proposals, after verifing the reports, we can block them from creating proposals in the future.

**Comment by samuveth** [comment]
The most pressing issues have been addressed or are coming [here](https://github.com/snapshot-labs/snapshot-sidekick)

Closing this issue and starting a pitch [here](https://www.notion.so/snapshotlabs/Better-Scam-Spam-Prevention-d2d107f8c5e5480ab19ad5b51761fbb1?pvs=4) with a link to this discussion.
