### ISSUE TITLE
Choice covered by long decimals

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3744]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/51686767/231817889-0597be1f-58e9-49d4-8954-987b1aa88302.png">

**Comment by wa0x6e** [comment]
Whats' the most UI friendly solution here ? Using scientific notation such as 1E-13 ?

**Comment by samuveth** [comment]
Scientific notation may not suit all users, as it assumes familiarity. An alternative, user-friendly solution is preferable.

I suggest displaying a fixed number of decimal places (e.g., 4, 0.000) for long decimals in the UI, while providing a tooltip to show the full number when users hover or click on it.

**Comment by j0hnfl0w** [comment]
![image](https://user-images.githubusercontent.com/97898172/234350863-aef2b443-9553-41f0-99b9-8903e12b4dfe.png)
We can shorten it
