### ISSUE TITLE
[BUG] .eslintrc-auto-import.json keeps showing up

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3753]
Even though it's inside the .gitignore

Screen:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/51686767/232181505-0bdb86ec-53ce-49a0-949f-2aec8a8855a0.png">

**Comment by wa0x6e** [comment]
Why would you want to ignore it ? It's a required file from the .eslintrc config

**Comment by samuveth** [comment]
Because it's auto generated

**Comment by samuveth** [comment]
It was ignored before I added it back because I was trying to get the linter to work. I will be auto generated on build

**Comment by samuveth** [comment]
Now it's in the `.gitignore` but still not being ignored for some reason

**Comment by wa0x6e** [comment]
I don't think you can ignore an already committed file. You have to first remove the file in .gitignore, then delete the file from the repo, then re-add the file in .gitignore

**Comment by samuveth** [comment]
> I don't think you can ignore an already committed file. You have to first remove the file in .gitignore, then delete the file from the repo, then re-add the file in .gitignore

Okay will try that

**Comment by samuveth** [comment]
If it keeps showing up for you after pulling latest changes run `git rm --cached .eslintrc-auto-import.json`

**Comment by wa0x6e** [comment]
Running your command will delete the file, but will ask me to stage the deleted file

**Comment by samuveth** [comment]
Even if you pull the latest develop?

**Comment by wa0x6e** [comment]
By bad, working on latest develop, file is gone.

But Eslint is now complaining:

```
ESLint couldn't find the config ".eslintrc-auto-import.json" to extend from. Please check that the name of the config is correct.
```

**Comment by wa0x6e** [comment]
Ok, I just noticed I have to run a build in order to auto generate it
