### ISSUE TITLE
[NEW FEATURE] - Cache server for votes download 

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/snapshot#3756]
### Briefly describe the feature.

Add a cache server to save and serve the votes CSV reports

### Which problem is this feature trying to solve?

Currently, downloading a votes CSV report is time and resource consuming.

Hub API is limited, so votes are fetched in batch of 1000. On some proposals such as this one (https://snapshot.org/#/stgdao.eth/proposal/0xd78c441994d140edde34131051113479651c593ab83badebc537a347ba86b705), with 145k votes, the download action is sending 144 requests to the api, with each request taking ~2s, making the total download time ~5min.

This is overloading the hub, with unnecessary requests, as the results of those requests are exactly the same for everyone, since the download is enabled only on closed proposals, and does not have any filtering/sorting.

This is also resources consuming, as the file building is done client side, after loading the results of those 144 requests in memory.

### What is the expected solution?

As the file is always the same, it can be cached, so everyone can download it in seconds, instead of minutes.

Those CSV files can also be used by some tools, to analyze a proposal's votes etc ..., instead of just querying the hub api. It could be used as another layer of data source, for a proposals' votes.

As the file are static, they can also be cache by a CDN

### How do you currently handle this problem?

We could create another repo, with an node micro service, wich will:

- Poll regularly for closed proposals events
- On close event, trigger the task to generate the CSV file (logic already in useRreportDownload)
- Save the file on the cache server, and expose it to the public
- Add an api endpoint, accepting request to download the file. Will 301 redirect to the static file on found, trigger a generate file request if not generated yet, or just return an error.

On snapshot side, remove useReportDownload, and replace it with a button which trigger a GET request to the new service API, which will either return a 301 redirect to the static file, or an error code (in case the file is not generated yet)

**Comment by wa0x6e** [comment]
The current download mechanism does not have any stop event in place, so when downloading a big file, and you're navigating away to another page, the download continue in background.

Going back to the same page which started the download, the download icon is back to normal, without the progress, making it look like the download interrupted.

It the user think it's interrupted, he may click on the button again, triggering another parallel download.

This may allow a user to trigger the same download multiple time, since we do not save the download state across the app.

**Comment by samuveth** [comment]
@wa0x6e Your cache server solution for CSV downloads seems promising. Could you provide a rough estimate of the development time required for this feature?

**Comment by wa0x6e** [comment]
1 to 2 days

**Comment by bonustrack** [comment]
I approve this, this could fit into a new server that handle others things like SSR for proposals

**Comment by wa0x6e** [comment]
Will get on it as soon as the repo is created

**Comment by bonustrack** [comment]
@wa0x6e https://github.com/snapshot-labs/snapshot-sidekick
