### ISSUE TITLE
Hide title and description for flagged proposals

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3777]
Currently we show a warning icon with tooltip for flagged proposals
<img width="755" alt="image" src="https://user-images.githubusercontent.com/51686767/232983589-79ca7d48-051c-4997-9003-fef4061f1e6a.png">

To make it more obvious that a proposal was flagged we should hide title and description and show a message "This proposal might contain scams, offensive material, or be malicious in nature." with a checkbox "Show anyway"
<img width="738" alt="image" src="https://user-images.githubusercontent.com/51686767/232983771-9b152183-d69a-4ae8-8a3c-ac626e3f583c.png">

**Comment by bonustrack** [comment]
I would even hide the author of the proposal (which often is also impersonating a project) and the status

**Comment by j0hnfl0w** [comment]
Looks like twitter approach:
![image](https://user-images.githubusercontent.com/97898172/233005741-23f3ebd9-cf6a-4493-bfea-eeb8e27014d4.png)

**Comment by samuveth** [comment]
@j0hnfl0w what happens when you click learn more in twitter?

**Comment by j0hnfl0w** [comment]
> @j0hnfl0w what happens when you click learn more in twitter?

You go to some article in the docs that describes flagging mechanism, maybe we need it too.

**Comment by samuveth** [comment]
Alright, maybe we should add a flagged proposals section in the docs @zzuziak
