### ISSUE TITLE
[NEW FEATURE] - Strategy names should redirect to strategy documentation

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3778]
### Briefly describe the feature.

Right now clicking on strategy names in strategies modal in proposal page and strategies section in settings page does nothing, it should be redirected to strategy documentation

### Which problem is this feature trying to solve?

Try going to https://snapshot.org/#/ens.eth/settings
clicking on the strategy name should redirect to the strategy documentation
![Untitled](https://user-images.githubusercontent.com/15967809/232987845-3559d88a-5c2e-4250-bbd4-799d1cc78fef.png)

### What is the expected solution?

Should redirect to strategy page

**Comment by samuveth** [comment]
Instead of having the main link link to about page, we will add an info icon
