### ISSUE TITLE
[BUG] - Changing settings reverts old changes.

### ISSUE THREAD

**Issue by RatanRSur** [snapshot-labs/snapshot#3820]
### Briefly describe the bug.

Changing settings reverts old changes.

### How can we reproduce the bug?

When I change the settings on my space, some of the older changes I made are being reverted.

For example, I changed the voting strategies in one change and a plugin configuration in another. Now the voting strategy change is not reflected anymore.

### Can you provide your device specific details below?

1. Device Type - Deskstop
2. Device OS - MacOS
3. OS Version - 13.3.1
4. Browser - firefox (embedded safe app) 
5. Browser Version - 111.0.1
6. Wallet - safe
7. Space - AMKT

**Comment by RatanRSur** [comment]
Is it possible on your end to view the history of the AMKT space settings?

If you take a look there, you'll see that the voting power went from being 2 math strategies, to 2 erc20-balance-of strategies, back to 2 math strategies. That last change back to the 2 math strategies was not initiated by me.

**Comment by samuveth** [comment]
@RatanRSur what is the space id?
