### ISSUE TITLE
Implement a Method for Reporting Spaces

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3821]
Now that we've introduced proposal reports, it's time to create a similar mechanism for reporting spaces. I envision incorporating a three-dot menu in the sidebar for this purpose.

We will also create a separate tally form for this purpose.

**Comment by j0hnfl0w** [comment]
@samuveth three-dot menu can be here
![image](https://user-images.githubusercontent.com/97898172/234532610-e02af40f-753c-4028-ab64-1f3f6b708379.png)
