### ISSUE TITLE
Space settings to allow voting with alias

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3852]

**Comment by samuveth** [comment]
Hey there @aurelianoB! I noticed this item was moved to the "Todo" list without any description.

**Comment by bonustrack** [comment]
There is already an space parameter to allow voting with alias, the missing parts are:
- Have a way on space settings to enable voting / propose with alias
- Make default voting and propose works with alias if a space has the parameter enabled

**Comment by samuveth** [comment]
Duplicate of https://github.com/snapshot-labs/snapshot/issues/2844
