### ISSUE TITLE
Conceal flagged spaces similar to flagged proposals

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3860]
We should implement a similar approach when visiting a flagged space as we have for flagged proposals, in which the flagged space is initially hidden and only becomes visible upon clicking the "Show" button.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/51686767/235590737-a28aeb0f-5ebf-4cf4-931b-a7ce64bb5b47.png">

**Comment by aurelianoB** [comment]
I think the idea is to hide the space behind a warning in the space browsing section. We should still keep the alert message on top once the user enters the flagged space. Adding a mockup for reference. @samuveth let us know if this is what you're imagining.
![image](https://github.com/snapshot-labs/snapshot/assets/20560366/824b023e-90e6-4eb7-8e9b-28a661ce2b21)

**Comment by samuveth** [comment]
We currently do not show spaces that are flagged in space browsing section at all. And I think we want keep it this way.

What I am proposing is that instead of showing the red warning on top of the space page, we should hide the content of the space page and show a message with a "Show" button much like the way we do for flagged proposals. This message should appear at the base level of the space route and should be visible not matter what space route the users enters on; proposals, proposal, about etc.

**Comment by samuveth** [comment]
> Do you propose adding another element that will behave similarly to the Proposal page? Or should we replace it? Maybe the existing approach is good enough?

Yes, we should also remove the existing approach

**Comment by Todmy** [comment]
Want to clarify that I get you right.
1) remove the red warning on top of the page
2) remove the warning badge near the name on the sidebar
3) add a gray box with a warning similar to the proposals page

A couple of extra questions:
- should we store the user answer per space so don't show a warning if the user clicked "Show"? Or is the idea to show this each time user enters a suspicious page?
- Can be a case when space is marked suspicious and a proposal is marked suspicious? Should we show two warnings in those cases?

**Comment by samuveth** [comment]
Indeed, it is possible to store the warning at the root level of the space to avoid its reappearance each time a user navigates through the space. However, there is no necessity to preserve it in local storage. This warning should be specific to the space visited at that time. If a user moves to a different space that has also been flagged, the warning should appear again, as it is specific to each individual flagged space.

If properly implemented, displaying both warnings simultaneously should not be possible. However, sequencing the warnings should be. In this case, the space warning should be displayed first, followed by the proposal warning.
