### ISSUE TITLE
Replace explore endpoint with spaces query

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3863]
- [x] Make sure pagination is working same as before
Example: initially the user only see 12 spaces, and when he clicks "load more" user gets 12 more, and need to click "load more" again to see the next 12, etc
- [x] Seach field should be working same as before
- [x] Filter with category 
- [x] Filter with network
- [x] Should not display private spaces

Can use this deployment: https://sea-turtle-app-hdjod.ondigitalocean.app/graphql 

Test with these query:
```graphql
query Spaces {
  spaces(first:12, skip: 0, orderBy:"rank", orderDirection: desc, where: { private: false }){
    total
    spaces {
      id
      name
      verified
      rank
      private
    }
  }
}

```
Also
```GraphQL
query Spaces {
	spaces(first:10, skip: 0, orderBy:"rank", orderDirection: desc, where:{
	 private: false,
	 network:"5", 
	 category:"social"
  }){
    total
    spaces {
        id
        name
        verified
        rank
        private
        categories
        network
        proposalsCount
        followersCount
        activeProposals 
    }
  }
}
```

**Comment by samuveth** [comment]
@ChaituVR ranking works well! But when I add a `skip` like 12 then I don't get any response

**Comment by samuveth** [comment]
Do we have the totalCount field implemented yet? We need it not only for the overall total count of spaces but also for the total count of spaces matching each specific query.

**Comment by samuveth** [comment]
How do we do search with text?

**Comment by ChaituVR** [comment]
Very good points, I will rework a bit today

> Do we have a totalCount field implemented yet? We need it not only for the overall total count of spaces but also for the total count of spaces matching each specific query.

I was not expecting it, I thought it is just the total count 😅 can we add this only when we sort with rank for now? Else I think it would need more operations on DB
If anything else missing with metrics, add it here :)
https://github.com/snapshot-labs/snapshot-hub/issues/578

> Ranking works well! But when I add a skip like 12 then I don't get any response

Looks like a bug, will fix it

> How do we do a search by name?

I thought it is just the id `id_contains`, should search with a name too, maybe I will add a new input `search` that will match both the id or name

Thanks
