### ISSUE TITLE
[NEW FEATURE] - Profile page with ENS

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3867]
### Briefly describe the feature.

Right now profile page only resolve with address

### Which problem is this feature trying to solve?

We can resolve ENS name and get a profile of that address, 

### What is the expected solution?

Right now only profile page only resolves like this https://snapshot.org/#/profile/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7

It should resolve like this too `https://snapshot.org/#/profile/fabien.eth`the

**Comment by Seroxdesign** [comment]
@ChaituVR I'm interested in tackling this bounty, I've done a similar PR for Metagame, as well as DebtDAO:

https://github.com/MetaFam/TheGame/pull/1535

**Comment by Seroxdesign** [comment]
@ChaituVR is this still available?
