### ISSUE TITLE
Confirm modal for unverified token

### ISSUE THREAD

**Issue by j0hnfl0w** [snapshot-labs/snapshot#3874]

**Comment by samuveth** [comment]
Should we save a token that was added by the user inside the local storage so that users doesn't have to have that same token each time?

**Comment by j0hnfl0w** [comment]
Maybe its okay for user to confirm every time he tries to use "unverified" token?

**Comment by samuveth** [comment]
On uniswap if you add a token it will remember next time you visit

**Comment by j0hnfl0w** [comment]
User cannot add token that is not from safe, user can only tag some token "i dont care that it is unverified"
