### ISSUE TITLE
Get verified tokens list from UNISWAP

### ISSUE THREAD

**Issue by j0hnfl0w** [snapshot-labs/snapshot#3875]

**Comment by samuveth** [comment]
We should discuss which lists we want to use from https://tokenlists.org/

Currently we are using only `https://gateway.ipfs.io/ipns/tokens.uniswap.org` for the Treasury feature in `useTreasury`

**Comment by j0hnfl0w** [comment]
You think we need multiple lists?

**Comment by samuveth** [comment]
The inclusive list we have the less we will have manual work of adding new tokens.

**Comment by j0hnfl0w** [comment]
Yeah we will have uniswap and a custom one, cos for example there is no [SAFE token](https://etherscan.io/token/0x5aFE3855358E112B5647B952709E6165e1c1eEEe) in uniswap and there will be many more like this.
