### ISSUE TITLE
Apply for new tokens to be verified

### ISSUE THREAD

**Issue by j0hnfl0w** [snapshot-labs/snapshot#3877]

**Comment by samuveth** [comment]
I think this should be guarded so that only verified spaces should be able to apply for custom tokens to be added.

**Comment by j0hnfl0w** [comment]
Maybe the same flow as with domains.json ?

**Comment by j0hnfl0w** [comment]
We need to decide tally form or PR. I think that PR is more transparent for json token list, and we can create the [same instruction in our docs](https://docs.snapshot.org/user-guides/spaces/add-custom-domain) like add custom domain.
wdyt? @samuveth @zzuziak

**Comment by samuveth** [comment]
> So the entire process will be manual? 🤔 Can't we automate that in two steps:
> 
> * if space is verified, allow token verification
> * if token is on the Uniswap list, update the db record? (I assume we don't have a table to track that though)

1. Automating this could be our aim, but we also need a way to confirm if requests are genuinely from a verified space, and we need a way to save them on Sidekick. One concern I have with a manual process is that it would be impossible to verify that a PR for adding a token is really coming from a verified space.
2. If a token is on Uniswap, it's already verified because we combine our list with Uniswap's from the start.

I'm not sure what the best path would be. @aurelianoB any advice?

**Comment by j0hnfl0w** [comment]
If we want to accept verification requests only from verified spaces then we need to show them a custom/personal link or at least show our tally link to them only (this does not guarantee that this link will be used only by verified space)

**Comment by samuveth** [comment]
No custom link needed. We can just have a link to a docs page like we do for strategies https://docs.snapshot.org/developer-guides/create-a-strategy/create-1

In there we can state that only verified spaces can add custom tokens.

**Comment by aurelianoB** [comment]
> 1. Automating this could be our aim, but we also need a way to confirm if requests are genuinely from a verified space, and we need a way to save them on Sidekick. One concern I have with a manual process is that it would be impossible to verify that a PR for adding a token is really coming from a verified space.
> 2. If a token is on Uniswap, it's already verified because we combine our list with Uniswap's from the start.
> 
> I'm not sure what the best path would be. @aurelianoB any advice?

Sorry I missed this. One alternative could be to let space admin or moderator do the verification themselves via signing message as in other settings. This would be more dev work now potentially but less work of support later - wdyt?

**Comment by samuveth** [comment]
Yes, I would create an issue for it and add to end of cycle or cooldown. For now we should go with github PR and manual approval based on who is making the PR.

**Comment by zzuziak** [comment]
Can you please add a sample PR for the token verification so I can mirror it in the docs?

**Comment by j0hnfl0w** [comment]
first we need to merge this https://github.com/snapshot-labs/snapshot-sidekick/pull/24
then there will be example PR for adding token in token list
@ChaituVR ping

**Comment by zzuziak** [comment]
Perfect, thanks @j0hnfl0w 🙏

**Comment by samuveth** [comment]
@zzuziak do we have any progress on this?
