### ISSUE TITLE
Docs section about token verification

### ISSUE THREAD

**Issue by j0hnfl0w** [snapshot-labs/snapshot#3903]
Context: https://discord.com/channels/955773041898573854/1103270490958729276/1106551191502065724

For our token verification process we need to create a page in docs (and notice in safe plugin section).

We need to describe what are verified and unverified tokens, [what public tokens list we use.](https://tokenlists.org/token-list?url=https://gateway.ipfs.io/ipns/tokens.uniswap.org)

[Some inspiration from uniswap.](https://blog.uniswap.org/token-lists)

**Comment by zzuziak** [comment]
As a first step we need the verification process itself, so depends on #3877

**Comment by samuveth** [comment]
As discussed on the call. We won't be implementing a separate verification process. Instead, the act of opening a PR will serve as the verification mechanism. However, that we will only accept and merge PRs originating from established projects and the developers associated with them.

**Comment by samuveth** [comment]
We should probably add some guidance on how to add a token to the verified list. Best places for this would be Docs and Sidekick repository.

**Comment by zzuziak** [comment]
Draft for Docs:

## Token verification

### What are trusted tokens?
- Definition
- Uniswap token list


### Adding a verified token to your space
1. Overlap between treasury assets and the Uniswap list
2. Not visible in the dropdown? Check 👇 

### Adding a token to the verified list
1. Create a PR with your token details (@j0hnfl0w sample PR please 🙏 )
2. Await the review, may take up to 72 hours
3. Add token to your Space on Snapshot

Anything else to add?
