### ISSUE TITLE
Enforce proposal validation for spaces

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3936]
There isn't any proposal validation for ~8k space including 8 verified spaces, this make it easy for scammer to post proposals. We should enforce validation on space to avoid this.

**Comment by samuveth** [comment]
### What's needed
1. Enforce proposal validation (or only authors) on space setup
2. Enforce proposal validation (or only authors) in the settings for existing spaces
3. (optional) Block proposal creation for spaces that do not have validation settings
