### ISSUE TITLE
[NEW FEATURE] - Add ''create proposal'' record in Profile activity

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#3939]
### Briefly describe the feature.

Add ''create proposal'' record in Profile activity

### Which problem is this feature trying to solve?

Currently, the activity in [Profile](https://snapshot.org/#/profile/0xeF8305E140ac520225DAf050e2f71d5fBcC543e7) only shows one's voting record. 
We should find a way to add the proposal record as well, this also get us insights on the historical reputation of the proposer.
Of course, if we introduce this, we will also need a filter here.

![filter](https://github.com/snapshot-labs/snapshot/assets/31681895/3103fa78-5a47-414e-9352-237d41398f78)

### What is the expected solution?

Add the record of proposal history along with voting history.

**Comment by ChaituVR** [comment]
Similar to #3340
