### ISSUE TITLE
Add block-explorer link for non verified tokens in tx builder

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#4026]
Currently unverified tokens don't have a link to the block-explorer because of the missing network, instead we should use the network configured in the SafeSnap plugin for the tokens

**Comment by petpoyw** [comment]
hi  [Shape up](https://github.com/orgs/snapshot-labs/projects/11) [3](https://github.com/snapshot-labs/snapshot/issues/4026#event-764331ca-5480-5825-abd0-2f33a7c10b43)
