### ISSUE TITLE
Admins cannot flag scam proposals

### ISSUE THREAD

**Issue by zzuziak** [snapshot-labs/snapshot#4054]
### Briefly describe the feature.

Currently users can report proposals via a form, while Moderators and Space Admins should be also able to do directly from the UI.

### Which problem is this feature trying to solve?

Flagging the scam proposals on spaces.

### What is the expected solution?

Moderators, Admins and Space Controller should be able to flag the proposals directly from the UI.

### How do you currently handle this problem?

Proposals are flagged manually by the team.

**Comment by samuveth** [comment]
Closed https://github.com/snapshot-labs/snapshot/pull/4220
