### ISSUE TITLE
[BUG] - Safe wallet works only with Ethereum Mainnet

### ISSUE THREAD

**Issue by Todmy** [snapshot-labs/snapshot#4084]
### Briefly describe the bug.

Unable to connect to snapshot via Safe wallet (not Ethereum Mainnet) through WalletConnect v2

### How can we reproduce the bug?

1. Try to log in to Snapshot using Safe Wallet and WalletConnect. The Safe wallet should be different than Ethereum Mainnet network.
2. You will fail to login

### What is the expected behaviour?

Safe should work with different networks

### Can you provide your device specific details below?

1. Device Type - Desktop
2. Device OS - MacOS
3. OS Version - 13.3.1
4. Browser - Chrome
5. Browser Version - 114.0.5735.198
6. Wallet - walletconnect provider, Safe Wallet

**Comment by fftwaunj** [comment]
thank you for your work

**Comment by ChaituVR** [comment]
Fixed by https://github.com/snapshot-labs/snapshot/pull/4700
