### ISSUE TITLE
[BUG] - Infinite Scroll is broken in timeline

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#4126]
### Briefly describe the bug.

Infinite scroll is broken

### How can we reproduce the bug?

1. Go to https://snapshot.org/#/timeline?feed=all
2. Scroll down 
3. The infinite scroll will stop at some point after loading 3 batches of proposals

### What is the expected behaviour?

It should continue at least until 1000 proposals (skip limit)

### Can you attach screenshots?

![image](https://github.com/snapshot-labs/snapshot/assets/15967809/141ab8a5-a96d-4835-8299-9ff4ec2e793b)

**Comment by samuveth** [comment]
Fixed https://github.com/snapshot-labs/snapshot/commit/a4eecb4fbb8126d390e6dc4c4628dfa196f05463
