### ISSUE TITLE
[NEW FEATURE] - STAR Voting

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [snapshot-labs/snapshot#4172]
### Briefly describe the feature.

Add STAR Voting as an election type

### Which problem is this feature trying to solve?

We've already got approval and ranked choice here: https://docs.snapshot.org/user-guides/proposals/voting-types#voting-systems-types

I would love to see STAR Voting as an option - it's like ranked choice, but simpler and less buggy: https://www.equal.vote/star_vs_rcv

Essentially, all candidates are scored 0 (worst) through 5 (best), the scores are summed, and the two highest scoring candidates are the finalists. In the runoff, your ballot counts as one vote for the finalist you prefer.

Here's the specification: https://www.starvoting.org/technical_specifications

You can learn more at:
* https://starvoting.org/
* https://equal.vote/

### What is the expected solution?

STAR Voting is available as an election type!

**Comment by ArendPeter** [comment]
I would also like to see this feature

**Comment by ChaituVR** [comment]
Moved this to https://snapshot.canny.io/feature-requests/p/star-voting
