### ISSUE TITLE
Typo in safesnap plugin's Config.vue file

### ISSUE THREAD

**Issue by Niraj-Kamdar** [snapshot-labs/snapshot#420]
https://github.com/snapshot-labs/snapshot/blob/8cab76edf9a0574c9845496810dca8b518e3baa0/src/components/Plugin/SafeSnap/Config.vue#L149-L152

This function should be named `fetchCollectibles`. (Not a major issue but just like to point it out.)

**Comment by ChaituVR** [comment]
@carlosfebres
