### ISSUE TITLE
Karma validation missing title and description in the UI

### ISSUE THREAD

**Issue by zzuziak** [snapshot-labs/snapshot#4244]
### Briefly describe the bug.

Title & descr display issue

### How can we reproduce the bug?

1. Go to Space settings -> Proposal -> Validation -> Scroll down:

![Screenshot 2023-09-27 at 10 57 57](https://github.com/snapshot-labs/snapshot/assets/39556343/d96e32fd-416d-424c-a8e4-e91804dafbb4)

### What is the expected behaviour?

Should be populated with those values:

https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/validations/karma-eas-attestation/index.ts#L69-L71

### Can you attach screenshots?

![Screenshot 2023-09-27 at 10 57 57](https://github.com/snapshot-labs/snapshot/assets/39556343/65d2c559-3307-4893-88b8-3715ac89570a)

**Comment by Todmy** [comment]
fixed in #4245

**Comment by Todmy** [comment]
fixed and validated on a new version
