### ISSUE TITLE
Can't add aave-governance-power

### ISSUE THREAD

**Issue by zzuziak** [snapshot-labs/snapshot#4266]
### Briefly describe the bug.

Clicking `Add` in the modal doesn't work for this strategy

### How can we reproduce the bug?

1. Go to Space settings -> Strategies
2. Try to add aave-governance-power, use for example this [contract](https://etherscan.io/address/0xc2f5f3505910da80f0592a3cc023881c50b16505):
![telegram-cloud-photo-size-1-4958971207512861664-y](https://github.com/snapshot-labs/snapshot/assets/39556343/d64c65b5-c652-4154-a87f-4b00c621d7a6)

4. Click `Add`
5. No error displayed

### What is the expected behaviour?

Should add the strategy

### Can you attach screenshots?

Console:

![image](https://github.com/snapshot-labs/snapshot/assets/39556343/eb2bc922-10af-43c2-9451-478b0ed610ed)

From DYDX team:
![telegram-cloud-photo-size-1-4965433982242106517-y](https://github.com/snapshot-labs/snapshot/assets/39556343/3a70e950-5356-42e1-9b2a-a813e957efee)

**Comment by ChaituVR** [comment]
It is not fixed yet, the real issue is that it works only when we select an option in "Power type"

https://github.com/snapshot-labs/snapshot/assets/15967809/5b424db0-3065-4d1c-b998-8d155f98bc52

**Comment by ChaituVR** [comment]
Fixed in https://github.com/snapshot-labs/snapshot/pull/4272
