### ISSUE TITLE
[BUG] - Comment Box Plugin has No Docs and Does Not Work By Default

### ISSUE THREAD

**Issue by johnnyshankman** [snapshot-labs/snapshot#4275]
### Briefly describe the bug.

Cannot use the provided Comment Box plugin in its default state. All comments error. No documentation for fixing.

### How can we reproduce the bug?

1. Go to your DAO's space
2. Click on settings
3. Go Advanced -> Plugins
4. Install Comment Box
5. Make a new proposal, comment box returns an error every time anyone attempts to comment.

### What is the expected behaviour?

I should be able to leave comments or be given documentation on how to configure the plugin.

The documentation has nothing. https://docs.snapshot.org/user-guides/plugins/comment-box

### Can you attach screenshots?

![Screen Shot 2023-10-09 at 3 10 15 PM](https://github.com/snapshot-labs/snapshot/assets/6632701/6371dac0-6cd3-49e6-b068-10c6f9c2ade5)

### Can you provide your device specific details below?

1. Device Type - Macbook
2. Device OS - OSX
3. OS Version - OSX Latest
4. Browser - Chrome
5. Browser Version - ?
6. Wallet - Metamask
7. Space - SidewaysDAO

**Comment by wa0x6e** [comment]
Hi, comment box has been deprecated for some time, and has now been removed
