### ISSUE TITLE
Delegation not showing up on demo.snapshot

### ISSUE THREAD

**Issue by zzuziak** [snapshot-labs/snapshot#4277]
### Briefly describe the bug.

Delegates are not listed on the UI

### How can we reproduce the bug?

1. Go to 'https://demo.snapshot.org/#/delegate/mgv-test.eth'

No delegations are displayed even though the delegations exist:

![image](https://github.com/snapshot-labs/snapshot/assets/39556343/39da6556-1b2a-4945-9b19-38e9d5aa9787)

delegator: 0xf78E7a442ea032a4D30FBA984c16a73Af5C915a0
delagate: 0xAa01DeC5307CF17F20881A3286dcaA062578cea7

**Comment by samuveth** [comment]
@zzuziak can you share the subgraph query and the link that you are using in the screenshots?

**Comment by wa0x6e** [comment]
Testing on https://thegraph.com/hosted-service/subgraph/snapshot-labs/snapshot-goerli

with 

```{
  delegations(where: { space: "mgv-test.eth"}) {
    id
    delegator
    space
    delegate
  }
}```

Does not give me any results, so can not reproduce
