### ISSUE TITLE
[BUG] - Voting Power of Arbitrum DAO

### ISSUE THREAD

**Issue by shikkiy2** [snapshot-labs/snapshot#4336]
### Briefly describe the bug.

I dont have any voting power ...

### How can we reproduce the bug?

I have always participated in Arbitrum votes since 1. Sometimes I would sell some of the coins, my power would decrease, but I could vote. Now I have 130 ARB that I didn't touch, but for some reason it writes that I didn't hit the snapshot of 146,775,123 blocks, although I didn't touch my coins.
Oops, it seems you don't have any voting power at block 146,775,123.
Oops, it seems you don't have any voting power at block 146,767,723. 
....
![image](https://github.com/snapshot-labs/snapshot/assets/38682138/0158b572-421a-4f18-959b-5537820768c2)

### Can you provide your device specific details below?

1. Device Type - [ex. Desktop or Mobile]
2. Device OS - [ex. Android, MacOS, Windows, iOS]
3. OS Version - [ex. iOS 11, Windows 10]
4. Browser - [ex. chrome, safari]
5. Browser Version - [ex. 101]
6. Wallet - [metamask, portis, walletconnect]
7. Space - [ex. ENS, Gitcoin]
8. Any additional information we should know -

**Comment by ChaituVR** [comment]
Hi @shikkiy2 Could you please create a ticket at https://discord.snapshot.org/ 

Also share more information like the address you are trying to vote and proposals with difference
