### ISSUE TITLE
Format in editor not working

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#4349]
Wan and I were not able to make it work in editor 

https://github.com/snapshot-labs/snapshot/pull/4343#issuecomment-1805158604

For every repo, prettier will be automatically inside editor itself with eslint , but for this repo it is not working

**Comment by samuveth** [comment]
Use prettier as default editor for this repo

**Comment by samuveth** [comment]
Fixed should work now for you without prettier
