### ISSUE TITLE
fix: We shouldn't show error message in the end of a proposal

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#4485]
We should trigger the request in background without showing the error message, we can show the result directly. We should also have a way to not trigger calculate multiple time if few people request it in same time.

**Comment by samuveth** [comment]
You mean the results ase calculating message?

**Comment by ChaituVR** [comment]
Actually, with https://github.com/snapshot-labs/snapshot-sequencer/pull/273 we still show an error message at the end of proposal, we need a background task, either on sequencer of webhook to trigger score calculation on proposal end

**Comment by wa0x6e** [comment]
Should already be a webhook task to trigger the computation on proposal end, to sequencer.

This pr is in case the first computation fail

**Comment by ChaituVR** [comment]
> Should already be a webhook task to trigger the computation on proposal end, to sequencer.
> 
> This pr is in case the first computation fail

Correct 😮  i completely forgot about the `get` webhook we had
