### ISSUE TITLE
Strategy should have access to proposal and votes payload

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#449]
Requested by @andytcf

**Comment by andytcf** [comment]
[Context]: For one of Synthetix's governance spaces (snxgov.eth) the council members are able to be diluted per proposal. The smart contract that deals with this accepts two parameters 

```
  function getDilutedWeightForProposal(string memory proposalHash, address councilMember) public view returns (uint) {}
```

**Comment by andytcf** [comment]
Example implementation

```
  const dilutionPenalty = await multicall(
    _network,
    _provider,
    CouncilDilutionABI,
    _addresses.map((address: any) => [
      CouncilDilutionAddress,
      'getDilutedWeightForProposal',
      [proposalHash, address]
    ]),
    { blockTag }
  );
  ```

**Comment by ChaituVR** [comment]
what happens if any space has min score field `space.value.filters?.minScore` .. proposal payload won't be available at that time of proposal creation 🤔

**Comment by samuveth** [comment]
@ChaituVR can we close this?

**Comment by ChaituVR** [comment]
I think so, @andytcf you still need it?
