### ISSUE TITLE
Criate my vote..Why I can't vote?

### ISSUE THREAD

**Issue by rayhan97794** [snapshot-labs/snapshot#4494]
### Discussed in https://github.com/snapshot-labs/snapshot/discussions/767

<div type='discussions-op-text'>

<sup>Originally posted by **metrox-eth** September 29, 2021</sup>
Suggest answers below or vote for an answer.</div>

**Comment by ChaituVR** [comment]
Please create a ticket with more details at https://discord.snapshot.org
