### ISSUE TITLE
[BUG] - No success message on proposal update

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#4504]
### Briefly describe the bug.

should show a success message on proposal update

### How can we reproduce the bug?

1. Go to a pending proposal
2. Update it with new values
3. Submit and see that sequencer returns success but UI doesn't show any message

**Comment by wa0x6e** [comment]
Weird, in my case, sequencer return correct response, but UI show a notification "Something went wrong"

**Comment by ChaituVR** [comment]
Same for me too, I forgot to write "Something went wrong" 😄
