### ISSUE TITLE
[BUG] - `[Object object]` printed as tag value

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/snapshot#4539]
### Briefly describe the bug.

In proposal page, a space is not printed correctly, and shown as `[Object object]`

### How can we reproduce the bug?

1. Go to a proposal
2. View the source code
3. Search for `[Object`

### What is the expected behaviour?

Remove the space value, as it's not a valid html property

### Can you attach screenshots?

![Screenshot 2024-01-31 at 19 51 26](https://github.com/snapshot-labs/snapshot/assets/495709/38f16500-84e9-450d-9790-f5c109fceb79)

### Can you provide your device specific details below?

1. Device Type - [ex. Desktop or Mobile]
2. Device OS - [ex. Android, MacOS, Windows, iOS]
3. OS Version - [ex. iOS 11, Windows 10]
4. Browser - [ex. chrome, safari]
5. Browser Version - [ex. 101]
6. Wallet - [metamask, portis, walletconnect]
7. Space - [ex. ENS, Gitcoin]
8. Any additional information we should know -

**Comment by ChaituVR** [comment]
<img width="1030" alt="Untitled" src="https://github.com/snapshot-labs/snapshot/assets/15967809/38714fdd-3c18-4876-80fd-fa307a145f92">
Also in notify component, there are many like this

**Comment by SrinuPcsr111** [comment]
hi

**Comment by armandRobled** [comment]
Patche-robledo6

**Comment by Bettyrockergit** [comment]
[snapshot-master.zip](https://github.com/snapshot-labs/snapshot/files/15058346/snapshot-master.zip)

**Comment by Bettyrockergit** [comment]
(url)
