### ISSUE TITLE
[NEW FEATURE] - Display "Space About" in the space profile section

### ISSUE THREAD

**Issue by hjjlxm** [snapshot-labs/snapshot#4558]
### Briefly describe the feature.

Display the description of the space that lies in "About" in settings in the profile card

### Which problem is this feature trying to solve?

Motivation: To let the user know at a glance what the project is about.

### What is the expected solution?

Show the “About” information buried in settings to the profile card.

<img width="953" alt="card improvement" src="https://github.com/snapshot-labs/snapshot/assets/31681895/81848935-45b2-4d78-94bc-cf640abab74c">

**Comment by famauz12** [comment]
ok

**Comment by samuveth** [comment]
Closing this because we are focusing design work on v2 and there is an about page to show this already.
