### ISSUE TITLE
[NEW FEATURE] - Add Mantle Safe to Known Hosts

### ISSUE THREAD

**Issue by msvstj** [snapshot-labs/snapshot#4573]
### Briefly describe the feature.

Allow Mantle Safe as a known host to let safe users interact with snapshot through a safe app

### Which problem is this feature trying to solve?

When users try to add snapshot application as a safe app they receive message that host is not allowed:
```Uncaught Error: Unknown host: multisig.mantle.xyz```

**Network:** Mantle [Supported by Snapshot](https://snapshot.org/#/?q=mantle&filter=networks)
**Safe URL:** https://multisig.mantle.xyz/

### What is the expected solution?

Adding **Mantle Safe** to known hosts would let safe users interact with the **Snapshot** safe app and sign voting messages.
https://github.com/snapshot-labs/snapshot/blob/d6503bcd4a37879342be83ef5f0ec8e3f041ea67/src/helpers/constants.ts#L14-L18

Opened pull request: https://github.com/snapshot-labs/snapshot/pull/4574

### How do you currently handle this problem?

Users are able to withdraw funds to a separate (EOA) wallet and then perform voting signature functions outside the safe app, though it would include more steps in the whole process.

### Anything else you'd like to mention?

_**Tested Signing with Safe:**_
- Latest proposal: [testnet.snapshot](https://testnet.snapshot.org/#/testingsafe.eth/proposal/0xb867235402eff21f77d9d7dc534443531a4af8264276a656ee834609b5f944b3). 
- Vote successfully signed by a [safe account](https://multisig.mantle.xyz/transactions/messages?safe=mantle:0x6A26b1c20FC687b38af43e70c57bd113FbDf271C) using EIP-1271

**Comment by Mueenhaider** [comment]
💸
