### ISSUE TITLE
Add end to end testing (UI test)

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#459]
We should add E2E testing to make sure we don't break anything when we add new feature. The lib "cypress" seem to be the most popular one to do that. For a first integration we can start with a test to do a vote.

**Comment by samuveth** [comment]
We will need to use something like this to enable metamask in our tests https://github.com/Synthetixio/synpress

**Comment by harshmaur** [comment]
@bonustrack I think I will attempt this next. I have a pretty good handle over cypress.

**Comment by samuveth** [comment]
> @bonustrack I think I will attempt this next. I have a pretty good handle over cypress.

Awesome!

**Comment by mktcode** [comment]
I have been experimenting with hardhat and cypress a bit now. We could add hardhat to our dev dependencies and run the e2e tests in the hardhat runtime environment, connect to a mainnet fork, freely move test funds, deploy contracts... all that good hardhat dev stuff.

https://user-images.githubusercontent.com/6792578/173579330-916cc769-efff-46f1-8178-891cb011161c.mp4

Regarding metamask/synpress an alternative would be to add some sort of test connector, that takes a private key. That's what I did [here](https://github.com/mktcode/boost/blob/b4728b03a0d95cc044f2a57df088d5adc54fa1fc/ui/src/composables/useWeb3.ts#L23-L32).
