### ISSUE TITLE
style: improve copy for privacy settings

### ISSUE THREAD

**Issue by aurelianoB** [snapshot-labs/snapshot#4701]
On space settings/voting/privacy, first label in the dropdown below should read “No privacy” instead of “Any”

<img width="375" alt="image" src="https://github.com/snapshot-labs/snapshot/assets/20560366/70fa12d3-9de3-449f-bc23-726e49b4d0f4">

**Comment by Pegasusc4** [comment]
https://www.22winth.com/snapshot-labs/snapshot/issues/4701#issue-2272217053
