### ISSUE TITLE
Bug progress bar 

### ISSUE THREAD

**Issue by heliosburner** [snapshot-labs/snapshot#4719]
![wait what1](https://github.com/snapshot-labs/snapshot/assets/43415513/9128fcae-23df-4e30-a38c-3588a08b6edc)

The bug in question:
The progress bar shows 161k for yes , when there's 2 yes votes down there with 155k and 123k which when combined is 278k, not 161k.
Either a lag/update bug or a visual bug on either one of the yes votes or the progress bar. 
Found on the LIVE Aavegotchi proposals accidentally while testing something.

**Comment by heliosburner** [comment]
https://snapshot.org/#/aavegotchi.eth/proposal/0x42de81c62b8c315e395a8751bfe0097e76c2b9ecb84886410a56f13cf5d87c44

**Comment by ChaituVR** [comment]
Hi @heliosburner There can be some delay if the score calculation fails, but it won't be the case when proposal end, we display an error if score calculation fail

**Comment by heliosburner** [comment]
Hello @ChaituVR There's about 8 tokens to calculate so I was thinking this might results in 8 updates per vote instead of just one calculation. The final calculation update shoulde be accurate unless an error message appears? so it's fine if I delete it or shall we keep it up to see if the final score coincidences with all the votes?

**Comment by ChaituVR** [comment]
Hi @heliosburner, Sorry i overlooked it earlier, looks like there is no issue with the score calculation. but proposal is using quadratic voting, https://docs.snapshot.org/user-guides/proposals/voting-types#quadratic-voting

**Comment by heliosburner** [comment]
There's been calculation problems with quadratic voting in the past? They're useful in case an address contains over 500 people voting such as a DAO address. Temporarily the image shows there might be an issue, even if the final calculation will be correct.
If you looked on that page's source and saw no code issue with the score calculation then let me know so I may delete the proposal and mark this bug issue as fixed on Github.

**Comment by ChaituVR** [comment]
Hi @heliosburner I don't think there is a error in score calculation, looks like you are using quadratic voting and It is expected that it reduces some voting power from whales, look at implementation here https://docs.snapshot.org/user-guides/proposals/voting-types#quadratic-voting

I just checked other proposals in this space, they are all using weighted voting, maybe you selected quadratic voting wrongly?
