### ISSUE TITLE
Ranked Choice Voting Results Broken

### ISSUE THREAD

**Issue by hammadj** [snapshot-labs/snapshot#483]
**Describe the bug**
When creating a snapshot vote using Ranked Choice voting, the UI doesn't show the voting results.

**To Reproduce**
1. Go to https://snapshot.org/#/metafactory.eth/proposal/QmTu3kkkPWqif1W6iPeg1xa9jLnuMCFxpMHypEi97q4awA
2. Open Console

**Expected behavior**
Voting results should be correctly calculated and displayed on the vote page

**Screenshots**
![image](https://user-images.githubusercontent.com/7143583/125694492-4d3c5101-1b9d-48f0-b482-dd6fd7bcf4fc.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave

**Comment by samuveth** [comment]
@hammadj should work again. Thanks for reporting this issue!
