### ISSUE TITLE
[BUG] - Kaia chainId 8217 with 500 error

### ISSUE THREAD

**Issue by talken-devteam** [snapshot-labs/snapshot#4924]
### Briefly describe the bug.

https://rpc.snapshot.org/8217 returns 500 error

### How can we reproduce the bug?

1. Go to 'https://snapshot.org/#/kommunedao.eth'
3. Connect to Snapshot with MetaMask
4. switch MetaMask network between Ethereum Mainnet and Kaia
5. See error f12 devtools Console, Network
6. Maybe you need to change old Klaytn rpc to https://docs.kaia.io/ko/references/public-en/
https://rpc.snapshot.org/1 (Ethereum 200 OK)
https://rpc.snapshot.org/8217 (Kaia 500 Error)
![image](https://github.com/user-attachments/assets/2f56ad37-66ec-46c1-8cee-a7c73b934814)

### Can you provide your device specific details below?

1. Device Type - Desktop
3. OS Version - Windows 10
4. Browser - chrome
5. Wallet - metamask
7. Space - https://snapshot.org/#/kommunedao.eth

**Comment by talken-devteam** [comment]
on 'https://kommunedao.xyz/forum'
score.snapshot.org method get_vp api returns 500 error
![image](https://github.com/user-attachments/assets/57f8c1b5-9ff4-45a4-ba8d-2f4bbb1cb77c)

**Comment by ChaituVR** [comment]
Should be fixed now
