### ISSUE TITLE
Refactor favoriteSpaces store module into a Vue 3 composable

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#502]
We need to refactor this store module to change it to a Vue 3 composable instead: 
https://github.com/snapshot-labs/snapshot/blob/develop/src/store/modules/favoriteSpaces.ts

If you want to work on this bounty please comment with your experience in Vue 3 and crypto. Thanks!

**Comment by icebert04** [comment]
Hi @bonustrack, I renamed favoriteSpaces from Typescript to Vue. 

Before submitting my pull request, I like to verify a few things...
May I ask what's the nature of this...

`const mutations = {
  setFavorites(_state, favorites: Record<string, boolean>) {
    _state.favorites = favorites;
  }`

**Comment by bonustrack** [comment]
@icebert04 What do you mean? This is a Vuex mutation, it just add to the store module state the favorites spaces

**Comment by icebert04** [comment]
@bonustrack okay, got it. 
I am finishing things up with refactoring the store module.

I'll be submitting my work anytime today.

**Comment by icebert04** [comment]
Hello @bonustrack 

I'm finished refactoring the store module to Vue 3 Composable.

I submitted my work on Gitcoin with PR: https://github.com/icebert04/snapshot/commit/da0f27bb35109e577f4863af27e93d406cae0292
