### ISSUE TITLE
Strategy eth-balance seems broken

### ISSUE THREAD

**Issue by rlime61** [snapshot-labs/snapshot#504]
**Describe the bug**
"TypeError: Cannot read property 'scores' of undefined" is returned when trying to use eth-balance.

**To Reproduce**
1. Go to 'https://snapshot.org/#/playground/eth-balance'
2. Click on 'Execute' button in action panel
3. Scroll down to 'Strategy params'

**Expected behavior**
Balances should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/81242307/127002189-e03b7727-a721-4571-947f-a5c1be72389f.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 91.0.4472.164

**Comment by bonustrack** [comment]
@rlime61 There was an issue it should be fixed now, thanks for reporting it!

**Comment by rlime61** [comment]
Yes, it works. Thanks! @bonustrack
