### ISSUE TITLE
Add the ability to specify delegation address with a link

### ISSUE THREAD

**Issue by 0xRabas** [snapshot-labs/snapshot#508]
currently, https://snapshot.org/#/delegate/NAME/ will open the delegation page with the space filled in (in this case, with "NAME")

I suggest having the ability to have the address pre filled as well, such that https://snapshot.org/#/delegate/NAME/0xADDRESS 
will open the delegation page with the 0xADDRESS already filled in in the "To" field.

edit: Also maybe have the option to have only the address filled in, without the space name pre filled

**Comment by bonustrack** [comment]
@0xRabas Hey it works now https://snapshot.org/#/delegate/balancer/fabien.eth thanks to @jyothnsa!
