### ISSUE TITLE
Delegate votes aren't being counted

### ISSUE THREAD

**Issue by shazow** [snapshot-labs/snapshot#526]
**Describe the bug**

We've been operating a friendly DAO at https://snapshot.org/#/crisisdao.eth, and we wanted to use the delegate feature but it looks like delegate votes aren't being counted.

I confirmed in the subgraph that the delegation is registered properly with this query:
```graphql
{
  delegations(first: 1000, where: {space_in: ["crisisdao.eth"]}) {
    delegate
    delegator
    space
  }
}
```

![image](https://user-images.githubusercontent.com/6292/127895812-d9a547de-cbcb-47a1-82bd-f57cd7b8d9f1.png)

In this case, the delegate (`0xc93c7f71581dfeaab59bed908888dac5689f312a`) and delegator (`0xb3d89ce6002e17812adb8f7e5d7ec6cd7cb84c75`) each have 1.5M tokens, so combined the votes from the delegate should be 3M tokens.

And yet when I look at recent votes (started weeks after the delegation has been registered -- not a block number issue), votes by the delegator are still registering at only 1.5M (under the 3Box name "Sean Bonner"):

![image](https://user-images.githubusercontent.com/6292/127896254-8b6ce5c0-7863-4856-aedf-e01afdd13a89.png)

Are we doing something incorrectly (is the "space" identifier not formatted correctly)? Is the delegation feature not available to some kinds of DAOs?

**To Reproduce**
1. Make a snapshot space with a DAO with an ENS .eth address
2. Delegate token votes via https://snapshot.org/#/delegate/
3. Create a new vote
4. Vote as delegate

**Expected behavior**

Delegate should have the combined voting power of the delegator, but does not.

**Comment by shazow** [comment]
I also confirmed that the scores API endpoint returns the non-delegated voting count:

```console
$ curl 'https://score.snapshot.org/api/scores' \
  -H 'content-type: application/json' \
  --data-raw '{"params":{"space":"crisisdao.eth","network":"1","snapshot":12944869,"strategies":[{"name":"erc20-balance-of","params":{"symbol":"CRISIS","address":"0x992f9bb313368ac11977b62490a83eeee54d9e1f","decimals":18},"__typename":"Strategy"}],"addresses":["0xc93c7f71581dfeaab59bed908888dac5689f312a"]}}'
```
```json
{"jsonrpc":"2.0","result":{"state":"final","scores":[{"0xc93c7f71581dfeaab59bed908888dac5689f312a":1500000}]}}
```

Should be 3000000, I believe.

**Comment by bonustrack** [comment]
@shazow Hi, to get voting power from delegation you need to add the strategy "delegation". The params of the strategies should include the strategies that you want to use as delegation power. Here is an example: https://hub.snapshot.page/api/spaces/balancer

**Comment by shazow** [comment]
@bonustrack Aha, thank you! Didn't realize we missed a step.

**Comment by shazow** [comment]
Added a small note to the docs to this effect: https://github.com/snapshot-labs/snapshot-docs/pull/6
