### ISSUE TITLE
On your Documentations you need to update a typo.

### ISSUE THREAD

**Issue by ahmadou5** [snapshot-labs/snapshot#544]
**Describe the bug**
A typing error on your Documentation

**To Reproduce**

**Expected behavior**
A delegation voting strategy most be added to the snapshot space

**Screenshots**
![Screenshot_2021-08-09-01-27-22-048_com android chrome](https://user-images.githubusercontent.com/78315869/128650712-101dac33-26f3-47c9-a04c-8786cfd1d7c6.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Redmi 7A]
 - OS: [android]
 - Browser [chrome]
 - Version [10]

**Additional context**
It is just a little typo on your Documentation
![

**Comment by bonustrack** [comment]
We've just fixed that, thanks for the issue report!
