### ISSUE TITLE
Delegation doesn't work on Polygon

### ISSUE THREAD

**Issue by ya7ya** [snapshot-labs/snapshot#552]
**Describe the bug**
the Delegation contract isn't deployed on polygon and the delegate UI hardcodes the deployed contract on mainnet, users of polygon hosted spaces won't be able to use the delegate strategy

**To Reproduce**
1. switch to matic network
2. https://snapshot.page/#/delegate
3. fill in the delegation info

**Expected behavior**
users should be able to use delegation on polygon aswell.

**Screenshots**

<img width="158" alt="Screenshot 2021-08-10 at 17 33 46" src="https://user-images.githubusercontent.com/932163/128905378-9eb9b69c-7e5d-4562-976d-2b184daadd6b.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bonustrack** [comment]
@ya7ya Hey the delegation contract is here: https://github.com/gnosis/delegate-registry it was deployed on Ethereum mainnet and few of the testnets. We would be happy to pay a bounty to get it deployed on others networks. It use the singleton factory and should get the same address on all these networks. The address is `0x469788fE6E9E9681C6ebF3bF78e7Fd26Fc015446`.

**Comment by harshmaur** [comment]
Taking this up

**Comment by harshmaur** [comment]
The truffle deployment seems to pass successfuly, but the network explorer does not show it. Moreover https://blockscan.com/address/0x469788fE6E9E9681C6ebF3bF78e7Fd26Fc015446 This address seems to be already present in polygon mainnet but its not a contract it seems. 

```build_1  | 1_deploy_registry.js
build_1  | ====================
build_1  | EIP 2470 SingletonFactory already deployed at 0xce0042B868300000d44A59004Da54A005ffdcf9f
build_1  | Deployed DelegateRegistry at 0x469788fE6E9E9681C6ebF3bF78e7Fd26Fc015446
build_1  |    -------------------------------------
build_1  |    > Total cost:                   0 ETH
build_1  | 
build_1  | 
build_1  | Summary
build_1  | =======
build_1  | > Total deployments:   0
build_1  | > Final cost:          0 ETH
build_1  | 
build_1  | 
build_1  | Done in 25.70s.```

This is the log I get for deploying to both mainnet and testnet of polygon. 

In order to deploy I had to add the polygon network configurations to the delegate-registry repo and used the steps they mention in their readme to deploy.

**Comment by harshmaur** [comment]
Alright. It has been deployed now. It was the gas issue. The gas estimated was only the estimation for the first contract. It internally executes another contract via singleton factory which also needed more gas. So I manually 10xed the gas and the gas limit to get it deployed successfully on both BSC and Polygon network. 

You can find all the network explorers here. https://blockscan.com/address/0x469788fe6e9e9681c6ebf3bf78e7fd26fc015446

**Comment by harshmaur** [comment]
Additionally, I have also verified the contracts on both those networks. and tested the transactions on snapshot's delegate page. 

They all work as expected.

**Comment by harshmaur** [comment]
@ChaituVR you can confirm and close the issue when happy.

**Comment by harshmaur** [comment]
@bonustrack good to close this now?

**Comment by bonustrack** [comment]
Yep
