### ISSUE TITLE
SafeSnap: "to" param on "Raw Transaction" should be optional

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#557]
On the SafeSnap transaction builder currently when doing a "Raw Transaction" the parameter "to" is required, this make transaction like deploying a contract with SafeSnap not possible as deploying a contract don't require a "to" param, we should make this param optional instead. 

To test it, you can go here: https://snapshot.org/#/fabien.eth/create 
Click "Add transaction batch" then select type "Raw Transaction".

**Comment by NftTopBest** [comment]
while open this page in dev mode, it trigger the warn
![Screen Shot 2021-08-16 at 2 53 37 PM](https://user-images.githubusercontent.com/87322530/129523738-8fbbe437-43dd-465a-85fe-3b4990c207fe.png)
