### ISSUE TITLE
erc20-balance-of strategy error on OKExChain

### ISSUE THREAD

**Issue by kizenY** [snapshot-labs/snapshot#564]
**Describe the bug**
Can not get score on OKExChain with erc20-balance-of strategy.

**To Reproduce**
1. Go to 'https://snapshot.org/#/playground/erc20-balance-of'
2. Choose OKExChain,fill args with any token,for example
```  json
{
  "address": "0x382bb369d343125bfb2117af9c149795c6c65c50",
  "symbol": "SYI",
  "decimals": 18
}
```
3. Click play button
4. See error: TypeError: Cannot read property 'scores' of undefined.I notice a network request  post to `https://score.snapshot.org/api/score`, and return an `CALL_EXCEPTION`,the "to address" is `0x23Daae12B7f82b1f0A276cD4f49825DE940B6374` which is not deployed on OKExChain.

**Expected behavior**
Return the balance of the token.

**Comment by OKMoon-SLStars** [comment]
We have also encountered such a problem. Through the snapshot tool, we checked and found that all OKExChain tokens will have problems.

**Comment by ChaituVR** [comment]
@kizenY  @OKMoon-SLStars this seems to be working fine now, I didn't get any error 
![image](https://user-images.githubusercontent.com/15967809/130734842-256dca62-a192-4738-8847-ac7ffdfc545b.png)

**Comment by kizenY** [comment]
https://github.com/snapshot-labs/snapshot.js/pull/357

> @kizenY @OKMoon-SLStars this seems to be working fine now, I didn't get any error
> ![image](https://user-images.githubusercontent.com/15967809/130734842-256dca62-a192-4738-8847-ac7ffdfc545b.png)

Yes,fixed by https://github.com/snapshot-labs/snapshot.js/pull/357
