### ISSUE TITLE
Add a calendar view of proposals on Snapshot

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#576]
### Prize bounty
1,000 DAI

### Challenge description

Create a new page "Calendar" that will be visible on snapshot.org/#/calendar. The page would show a calendar view of the proposals from the space you've joined. 

The calendar can look similar to this: 
https://user-images.githubusercontent.com/16245250/130690441-b59a103c-4a12-46ac-81ad-141f94ba885e.png 
Each space can have a different color using space custom skin settings.

Here is a base component that you can use to create the calendar: 
https://github.com/snapshot-labs/snapshot/blob/develop/src/components/Ui/Calendar.vue 

The list of joined space can be found with the GraphQL API see here: 
https://docs.snapshot.org/graphql-api#follows.

The implementation should not add any new dependencies. 

You must have experience with Vue.js to do this bounty, and have a good sense of UX, if you are interessed please answer with code examples and UI links.

**Comment by harshmaur** [comment]
@bonustrack Question, the proposals would also span across the calendar as displayed in the image based on the start and end date of the proposal?

**Comment by harshmaur** [comment]
@bonustrack also I know you mentioned it shouldn't add new dependencies, but I found this https://github.com/richardtallent/vue-simple-calendar
