### ISSUE TITLE
Change avatar image from Jazzicon to Blockies

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#593]
We should change the solution for generated avatars placeholders. Now we use Jazzicon we should move to Blockies.

Before: 
![image](https://user-images.githubusercontent.com/16245250/131498724-66b10436-2808-415b-9f91-9843b076b088.png)
After:
![image](https://user-images.githubusercontent.com/16245250/131498789-edeb2879-6498-4f4a-afab-03a0f7ddb139.png)

**Comment by samuveth** [comment]
@bonustrack shouldn't we keep the jazzicon at least for the connected wallet? I think we should keep the same as Metamask for wallet addresses.

**Comment by samuveth** [comment]
@bonustrack Oh, didn't see that on mobile.

**Comment by longabi** [comment]
mobile is not avaliable
