### ISSUE TITLE
Add TokenPocket wallet support

### ISSUE THREAD

**Issue by chendatony31** [snapshot-labs/snapshot#597]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add TokenPocket wallet into the login panel

**Describe alternatives you've considered**

**Additional context**
TokenPocket wallet injected `ethereum` object as metamask do. which also have  `ethereum.isTokenPocket` to detect with in a TokenPocket dapp browser.

![image](https://user-images.githubusercontent.com/2173383/131986276-ec4478f2-ba10-4f4b-8edf-b7b18d7f5b4e.png)

**Comment by bonustrack** [comment]
@chendatony31 Thanks it should be available on our next release.

**Comment by bonustrack** [comment]
We can use this logo https://s2.coinmarketcap.com/static/img/coins/200x200/5947.png

**Comment by chendatony31** [comment]
Hi @bonustrack , please use these instead:
https://tp-statics.tokenpocket.pro/tokenpocket.png
https://tp-statics.tokenpocket.pro/tokenpocket-200-200.png

**Comment by bonustrack** [comment]
@chendatony31 Thanks do you have one with transparent background? It should fit better

**Comment by chendatony31** [comment]
How about this one? 
https://tp-statics.tokenpocket.pro/tokenpocket-380.png

**Comment by bonustrack** [comment]
@chendatony31 We did the change here: https://github.com/snapshot-labs/lock/pull/22 we've used the image from the website favicon here https://www.tokenpocket.pro/favicon.png hope that works well

**Comment by chendatony31** [comment]
Ok, thanks
