### ISSUE TITLE
Can't Vote on PolyVertex

### ISSUE THREAD

**Issue by crocarms** [snapshot-labs/snapshot#598]
Original TG Thread: https://t.me/snapshotlabs/5805

Original Discord Thread: https://discord.com/channels/707079246388133940/747049240022482974/880735141910167562

From user:

Describe bug 🐛 
Everything seems to be working fine until I press vote and the screen freezes. No votes are recorded and I need to refresh 

To reproduce 💜
Go to Governance
Click on active proposal
Select candidates
Click Vote
Page freezes and I can still move the cursor around but page is stuck.

Expected behaviour 🥳
Once candidates are selected and I press “Vote” I would expect the page to refresh and my votes to show in the summary.
Possibly a $1M airdrop 🤪 

Screenshots
See below

OS: Windows 10 Pro
Browser: Chrome
Version: 92.0.4515.159

![4D3F3936-C134-45E7-8E7A-DC5C8E12B46D](https://user-images.githubusercontent.com/89095885/131994323-293a7481-6697-4fdc-865b-c7ea62c82e6a.jpeg)

Link to vote: https://vote.polyvertex.finance/#/polyvertex.eth/proposal/QmPPDbWhvVzfdHcFMACYV5ANGktmRbL1bTAMZioZzoaUqZ

**Comment by crocarms** [comment]
Asked user to provide chrome extensions and console errors.

**Comment by ChaituVR** [comment]
@crocarms this issue still exist on your space? i see lot of vote on this proposal
