### ISSUE TITLE
Allow spaces to exist in more than one network

### ISSUE THREAD

**Issue by m1guelpf** [snapshot-labs/snapshot#606]
**Is your feature request related to a problem? Please describe.**
I want the holders of my token ($MIGUEL, a token that exists both in the Ethereum Mainnet and the Polygon Mainnet thanks to bridging) to be able to vote on proposals without first migrating their tokens to one of the two chains.

**Describe the solution you'd like**
Either allowing to select multiple network for your space or adding an optional network key to the `erc20-balanceof` strategy to handle lookups in a different chain.

**Describe alternatives you've considered**
The only workaround right now is to require owners to move all their tokens to the selected chain previous to the snapshot, which is not optimal due to current gas prices.

**Comment by ChaituVR** [comment]
Hi @m1guelpf  I think you are looking for `multichain` strategy https://snapshot.org/#/playground/multichain - with this you can get `erc20-balanceof` for both mainnet and polygon
