### ISSUE TITLE
Can't use important tailwind classes in @apply

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#622]
Steps to reproduce:
- add `!` to tailwind class inside `style.css`, f.e like this `@apply !text-xl;`

You should get an error from Vite like this.
![image](https://user-images.githubusercontent.com/51686767/133042247-333e0d7e-68ff-4752-b0cd-ded828d74ac2.png)

**Comment by harshmaur** [comment]
@samuveth check documentation https://tailwindcss.com/docs/functions-and-directives

You need to use it like this `@apply text-xl !important;`

**Comment by samuveth** [comment]
@harshmaur ok that kinda works!

**Comment by samuveth** [comment]
> @harshmaur ok that kinda works!

**Comment by samuveth** [comment]
> @samuveth check documentation https://tailwindcss.com/docs/functions-and-directives
> 
> You need to use it like this `@apply text-xl !important;`

That also doesn't work for me 
![image](https://user-images.githubusercontent.com/51686767/133191876-3218b198-8a1a-460c-b472-9e01f75b8555.png)

**Comment by harshmaur** [comment]
Hmm @samuveth Let me check

**Comment by harshmaur** [comment]
@samuveth try this https://github.com/tailwindlabs/discuss/issues/224

`@apply text-xl #{!important};`

**Comment by pranav-js** [comment]
@harshmaur  this doesn't work anymore, any alternative for scss?

**Comment by samuveth** [comment]
> @harshmaur this doesn't work anymore, any alternative for scss?

We should avoid having to use `!important`, we should make changes elsewhere if necessary

**Comment by SM2DevLLC** [comment]
Anyone else getting as `at-rule or selector expected` error when using `#{!important}` in their scss code? Any thoughts on how to ignore/fix the error?

**Comment by pranav-js** [comment]
@SM2DevLLC  you can't. that was deprecated by SCSS and doesn't work anymore.

**Comment by SM2DevLLC** [comment]
@pranav-js Oh ok. Is there a different way to do it then or how do you add important?

**Comment by pranav-js** [comment]
@SM2DevLLC  no there isn't. you can enable important:true flag in tailwind.config.js but it adds for every class causing a big pain. so basically you need to write without `@apply` to use !important

**Comment by jesspinklet** [comment]
> @SM2DevLLC you can't. that was deprecated by SCSS and doesn't work anymore.

Based on this I think this issue shouldn't be closed.
I'm facing the same `at-rule or selector expected` error

**Comment by rikusen0335** [comment]
I've confirmed that workaround is still working.

Using [sass](https://github.com/sass/dart-sass) (which is used in npm `npm i --save sass`) 1.56.1, I can use `#{!important}`

If this anyone helps.

**Comment by StanislavNemytov** [comment]
It's still not working 🤷🏼‍♂️
