### ISSUE TITLE
Delegate page not working

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#631]
Go to snapshot.org/#/delegate

See error in the console:
![image](https://user-images.githubusercontent.com/51686767/133224364-db66d627-43b7-4c96-bb4b-1df940032e05.png)

**Comment by harshmaur** [comment]
@samuveth It works fine locally and on production

**Comment by samuveth** [comment]
Yeah thanks, I was on wrong network with metamask.
