### ISSUE TITLE
Need Multicall contract on Optimistic network

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#634]
To add support to the [Optimistic network](https://optimism.io) we need a Multicall contract to be deployed on their network

There is already multicall deployed in Optimism, as mentioned in docs: `0x90f872b3d8f33f305e0250db6a2761b354f7710a`  the method is almost the same as MakerDAO's multicall but the names are different `multicall`  instead of `aggregate`

we need something like these :
https://github.com/makerdao/multicall
https://etherscan.io/address/0xeefba1e63905ef1d7acba5a8513c70307c1ce441#code

**Comment by harshmaur** [comment]
@ChaituVR so I just need to copy paste the contract and deploy it to Optimistic Network?

**Comment by harshmaur** [comment]
@ChaituVR should I use MultiCall2 or Multicall? 

As you can see they forked Optimistic network forked Multicall2

**Comment by harshmaur** [comment]
It doesnt look like Optimistic deployment would be done any soon due to issues with contract deployments on optimistic kovan

**Comment by ChaituVR** [comment]
I tried to deploy multicall to optimistic kovan but I am getting few errors:
ParserError: OVM: BLOCKHASH is not implemented in the OVM.

Same error for BALANCE, DIFFICULTY, and COINBASE
https://community.optimism.io/docs/protocol/evm-comparison.html

we can ignore others but balance is used by eth-balance strategy

**Comment by ChaituVR** [comment]
https://optimistic.etherscan.io/address/0x35A6Cdb2C9AD4a45112df4a04147EB07dFA01aB7#code
This one is working well
