### ISSUE TITLE
Add dark mode switcher

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#647]
We should add an icon (using icon id "sun" and "moon") on the left sidebar like this:
![image](https://user-images.githubusercontent.com/16245250/133855885-291f0e74-6548-465f-a131-d976c5cbb472.png)
For the dark mode we can use the colors from Loot DAO skin. By default we should show default OS setting of the user see example with Uniswap skin https://github.com/snapshot-labs/snapshot-spaces/blob/master/skins/uniswap.scss#L12 . The space having specific skin should keep their colors. Dark / light mode should be used only when there isn't any space skin. The value dark / light should be stored on localStorage.

**Comment by harshmaur** [comment]
Taking this up!
