### ISSUE TITLE
Add README on multichain and delegation strategies

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#657]
We should add a README on the strategies "multichain" and "delegation". There is often users asking about it.

Here is an example of a simple README for erc20-balance-of strategy:
https://snapshot.org/#/strategy/erc20-balance-of
https://github.com/snapshot-labs/snapshot-strategies/tree/master/src/strategies/erc20-balance-of

You can find examples of params here https://hub.snapshot.org/api/spaces if you search for "multichain" or "delegation"

The README should explain how to format the params of the strategies.

**Comment by bonustrack** [comment]
Assigned to NeonBlue#6271

**Comment by bonustrack** [comment]
@SingularSpace Can you do a PR on `snapshot-strategies` repo see example in the issue description

**Comment by SingularSpace** [comment]
@bonustrack PR is done.

**Comment by midgerate** [comment]
@SingularSpace can you put a link to the PR here so that the issue is linked to it?

**Comment by SingularSpace** [comment]
@midgerate [https://github.com/snapshot-labs/snapshot-strategies/pull/78](url)

**Comment by SingularSpace** [comment]
@midgerate PR is made in snapshot-strategies repository.
