### ISSUE TITLE
Add top delegates on delegate page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#659]
On the delegate page for space here: https://snapshot.org/#/delegate/balancer.eth

We should show the top delegate in a new section like this:
![image](https://user-images.githubusercontent.com/16245250/133920874-5d70312e-dea6-42b5-baaf-27f27960c6c2.png)

Delegations can be taken from here: https://thegraph.com/legacy-explorer/subgraph/snapshot-labs/snapshot
We should

 1: Take relations delegator / delegate
 2: Calculate delegator voting power using getScores and current space strategies
 3: Sort delegates by voting power

This section should not be visible on that page: https://snapshot.org/#/delegate

**Comment by midgerate** [comment]
Needs review - https://github.com/snapshot-labs/snapshot/pull/688

**Comment by bigint** [comment]
@bonustrack I think this is already in place now, is this still a thing?

**Comment by samuveth** [comment]
Yes it's been merged
