### ISSUE TITLE
Create clean list of categories for DAOs

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#662]
Can take example from:
Messari
Defillama
Defipulse
Coopahtroopa
And others

**Comment by midgerate** [comment]
DeFi
Smart Contract Platforms
Currencies
Stablecoins
Exchange Tokens
Web3
Privacy Coins
Interoperability 
Decentralised Exchanges
Lending
Deravatives
Asset Management
Data Management
File Storage
Gaming
NFTs
Layer2
Protocols
Chains
Insurance
Staking

**Comment by bonustrack** [comment]
@midgerate Did you made this list or where it come from? I think it miss the most common DAO categories like Grants, Service, Social.

**Comment by midgerate** [comment]
@bonustrack just wanted to make a running list so that once we have all the keywords, we can reorganise and prepare the final list. 

I got these categories from 
Messari
Defillama
Defipulse

**Comment by midgerate** [comment]
@bonustrack I think we need to classify as Main and Sub categories. I just updated my list above. Have a look. Maybe I am missing more categories.

**Comment by midgerate** [comment]
@bonustrack when you have time to review. Please do

**Comment by bonustrack** [comment]
I think the best is to start with a small list we can just take the ones from Cooper article here: 
https://coopahtroopa.mirror.xyz/_EDyn4cs9tDoOxNGZLfKL7JjLo5rGkkEfRa_a-6VEWw
Investment, Protocol, Social, Media, Grants, Collector, Service
![image](https://user-images.githubusercontent.com/16245250/135732229-213ca815-0e67-4916-8c69-d29d365e650d.png)

**Comment by samuveth** [comment]
> Investment, Protocol, Social, Media, Grants, Collector, Service

Looks good! But I think users might have difficulty knowing which category to pick, f.e "Aavegotchi" is a game, not sure why it's in Protocol

**Comment by midgerate** [comment]
Sounds good! What's the next step for this?
