### ISSUE TITLE
Use formatted numbers for members count

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#667]
For the list of members we should format the number and show "1,000" or "1k" instead of "1000". Here:
![image](https://user-images.githubusercontent.com/16245250/134059632-bdec27b8-012a-4408-9bb8-7a6c1f729c6f.png)

Ideally we should use `vue-i18n` to do the correct formating instead of `numeral`, if might give a way to keep a transalation message with plural and singular and give locale formating for example in French it would return "1 000"

**Comment by samuveth** [comment]
> hello want to ask, let's say the member is 1000000 and then we choose locale french, do you want it to show 1 000 000 or 1 m?

We should show like the voting power in the votes, `1k`, `1m`

**Comment by spiritbro1** [comment]
i see thank you for the explanation, but using vue-i18n right instead of
numeraljs?

**Comment by samuveth** [comment]
> i see thank you for the explanation, but using vue-i18n right instead of numeraljs?

I'm not sure how that would work, I would just us numeraljs

**Comment by samuveth** [comment]
> because in the description bonustrack said that we should use vue-i18n instead

Maybe you can confirm with Bonustrack, I'm not exactly sure what he intended to achieve.

**Comment by spiritbro1** [comment]
i see, thanks anyway
