### ISSUE TITLE
Network filters in home page doesn't work anymore

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#670]
**Describe the bug**
https://snapshot.org/#/?network=1 filters like these don't work anymore (when we click any network from networks page)

**To Reproduce**
1. Go to https://snapshot.org/#/networks
2. Click on any network

**Expected behavior**
It should display the spaces that use the network

**Comment by himanshu007-creator** [comment]
hi @ChaituVR , i would like to work on this issue, can you help out?!

**Comment by ChaituVR** [comment]
Depends on https://github.com/snapshot-labs/snapshot-hub/issues/124

**Comment by sarmatdev** [comment]
I apologize to those who wanted to take this task, but it has not been solved for 4 days and is not assigned to anyone😅

Here is my PR #693
