### ISSUE TITLE
Input border should be red on validation error in settings

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#675]
Should look like this:
![image](https://user-images.githubusercontent.com/51686767/134306520-79c66829-eb8f-4471-8200-7533db72f6f4.png)

Removing `!important` from:
```
.border,
.border-md,
.border-lg,
.border-b,
.border-t,
.border-r,
.border-l {
  border-color: var(--border-color) !important;
}
```
in style.css should fix this.

Needs to be checked if removing this will break anything else.

**Comment by midgerate** [comment]
@samuveth I am pretty sure it will break something else. Best to look at the git history and see why it was added in the first place. !important should be avoided all the time really.

**Comment by samuveth** [comment]
> @samuveth I am pretty sure it will break something else. Best to look at the git history and see why it was added in the first place. !important should be avoided all the time really. 

Yeah we should try removing it and fix whatever breaks another way.

**Comment by samuveth** [comment]
Closed via https://github.com/snapshot-labs/snapshot/pull/703
