### ISSUE TITLE
Add ENS avatars to profile using @davatar/react

### ISSUE THREAD

**Issue by GailWilson** [snapshot-labs/snapshot#678]
## Description
Add robust avatar image lookup support for ENS for wallet profile display using [@davatar/react](https://www.npmjs.com/package/@davatar/react) to seek to fulfill the spec outlined in [avatars.md](https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182)

**Problem:**

Snapshot currently shows a wallet's ENS name but not the ENS avatar photo (instead they show a [blockie](https://www.npmjs.com/package/ethereum-blockies)):

<img width="191" alt="Screen Shot 2021-09-22 at 11 49 49 AM" src="https://user-images.githubusercontent.com/2453344/134404546-142fcacc-4fbf-4e36-bc3d-8c687804ef67.png">

**Solution:**

Replace the `<Blockie ... />` component with a `<Davatar ... />` component and this will show the ENS profile photo if the wallet has one. Here's an example on UniSwap:

<img width="101" alt="Screen Shot 2021-09-22 at 11 49 32 AM" src="https://user-images.githubusercontent.com/2453344/134404603-3e70768f-9ee1-4dab-b0c1-1fbe69562628.png">

## Implementation Requirements
Dev docs found here for reference : [@davatar/react](https://www.npmjs.com/package/@davatar/react)

Steps:
- Add [@davatar/react](https://github.com/TBDAO/davatar-helpers/tree/master/packages/react) package
- Replace use of  `<Jazzicon ... />` or `<Blockie ... />` with `<Davatar ... />` component
- Set param `generatedAvatarType='jazzicon'` or `generatedAvatarType='blockies'` matching the app's previous component

How to test:
- Test changes with wallet addresses that have davatars set and make sure the davatar shows up replacing the jazzicon or blockie. Here are a couple to try (you can [set a davatar to your own wallet here](https://www.davatar.xyz/) too!):
        -- `0xE88F99aDC1aB6B1204C027e14c746DA9C3a66970`
        -- `0x9B6568d72A6f6269049Fac3998d1fadf1E6263cc`
- Test changes with wallet addresses that don't have a davatar set and make sure the blockie shows up as the default image.

Example PRs:
- [https://github.com/scaffold-eth/scaffold-eth/pull/438](https://github.com/scaffold-eth/scaffold-eth/pull/438)
- [https://github.com/Uniswap/interface/pull/2321](https://github.com/Uniswap/interface/pull/2321) (note: we do now support NFT-metadata reference type)

**Comment by bonustrack** [comment]
@GailWilson we dont use React

**Comment by GailWilson** [comment]
Yes, sorry about that.
