### ISSUE TITLE
Add support for ENS avatars

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#680]
Like described here https://github.com/snapshot-labs/snapshot/issues/678 we should use the ENS avatar if it's available. We should add this to our Avatar component, without adding any dependency

**Comment by midgerate** [comment]
I think I will take this up. @samuveth as I worked on Avatar component before.

**Comment by samuveth** [comment]
This issue is blocked until we figure out a way to request ENS avatar text records in one request.

**Comment by midgerate** [comment]
@samuveth batching fixes the issue.

**Comment by midgerate** [comment]
https://github.com/snapshot-labs/snapshot/pull/689#issuecomment-927475150

Too many unnecessary requests. Not needed right now.
