### ISSUE TITLE
Update to latest Vite.js version

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#682]
https://twitter.com/vite_js/status/1441020830994030594?s=19

**Comment by sarmatdev** [comment]
@bonustrack Hi! Did the update to version vite@2.6.0-beta.2, (beta.1 had a major [bug](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#260-beta2-2021-09-23)). `dev` and `build` scripts works good, with no issues.

Please assign me as contributor and I will upload my branch

**Comment by bonustrack** [comment]
@sarmatdev Great! Just did

**Comment by sarmatdev** [comment]
I can't upload my branch, error 403 in git

**Comment by sarmatdev** [comment]
#686

**Comment by samuveth** [comment]
https://github.com/snapshot-labs/snapshot/pull/686

**Comment by sarmatdev** [comment]
CONFIRM

**Comment by mktcode** [comment]
https://twitter.com/vite_js/status/1443220262166671363

**Comment by mktcode** [comment]
@bonustrack Sure. :) I'm primarily trying to figure out this one: https://github.com/snapshot-labs/snapshot/issues/818
I just can't go on with my life as long as these errors show up. :D Vite version unfortunately does not effect that.
