### ISSUE TITLE
Should not query follows if user is not logged

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#684]
I'm not logged but when i look on the console Network tab i can see there is a query sent to check my followings
![image](https://user-images.githubusercontent.com/16245250/134688163-8e9d6b5a-fd1b-42c1-880e-5f3143387986.png)
We shouldn't send such query.

**Comment by sarmatdev** [comment]
@bonustrack I've done this issue!

Please add me to the contributors list and I will upload this branch

**Comment by bonustrack** [comment]
@sarmatdev Can you fork and do a PR?

**Comment by sarmatdev** [comment]
> @sarmatdev Can you fork and do a PR?

#685 Done
