### ISSUE TITLE
Proposal redirection doesn't work anymore

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#690]
**Describe the bug**
Proposal redirection with proposal Id doesn't work any more

**To Reproduce**
1. Go to any spaces ex: https://snapshot.org/#/sushigov.eth/proposal/QmNT8bY7aJRFUMtfbFp9m7JHcUgEVCNZzWE67Crr9oAVrA
2. Go to any other proposal in another space Ex. https://snapshot.org/#/gitcoindao.eth/proposal/QmSRTDaRckWkWBBAHDXXyatMFLUZcFjSCkvHSBuC84fgbf
3. Replace gitcoindao proposal ID with sushigov.eth's proposal id 
4. https://snapshot.org/#/gitcoindao.eth/proposal/QmNT8bY7aJRFUMtfbFp9m7JHcUgEVCNZzWE67Crr9oAVrA
5. It should redirect to sushigov.eth space's proposal but redirecting to snapshot home page

**Expected behavior**
It should redirect to proposal id's space but redirecting to snapshot home page

Let me know if it is not a required feature anymore :)

**Comment by samuveth** [comment]
@ChaituVR this is expected behavior, we've recently changed this.

**Comment by ChaituVR** [comment]
Cool then :) 👍
