### ISSUE TITLE
Can't change language with custom domain

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#691]
There is no way to change language Or way to see the about section with custom domains
![image](https://user-images.githubusercontent.com/15967809/134776857-f6fc3e45-0044-4013-b76c-e89304cbc001.png)

Ex:
https://signal.aave.com/#/
https://vote.airswap.io/#/

**Comment by samuveth** [comment]
I'd rather put the language switcher in the top nav on custom domain
