### ISSUE TITLE
Error icon on terms field in settings page is not noticeable 

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#692]
Few users complain that they are unable to save their space settings, they are unable to notice there is an error icon on the terms field, especially when enter a URL without `http://` or `https://`

**To Reproduce**
1. Go to space settings 
2. In the Terms field enter a URL without `http://` or `https://` , ex: `snapshot.org`
3. Unable to click on Save button but the button is not disabled (visually)
 

**Expected behavior**
A clear message should be shown OR should auto-add `https` to URL. OR suggest a better solution

**Screenshots**
![image](https://user-images.githubusercontent.com/15967809/134777102-dfae90e1-72d9-4780-ac53-df2d135ad552.png)

**Comment by samuveth** [comment]
The input border should also be red on validation error. This is a bug and there is already an open issues for this.

**Comment by ChaituVR** [comment]
@samuveth with border, also an error message/example terms link/autofill `https://` can help when user is missing `https://` in URL

**Comment by ChaituVR** [comment]
Displaying error message now
