### ISSUE TITLE
Make playground url shareable 

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#697]
Make the playground url shareable with populated fields using base64 https://snapshot.org/#/playground/delegation?query=$base64object 

The query can use the same format as a strategy example see https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/api/examples.json

We shouldn't add a new dependency for base64, browser support it.

**Comment by sarmatdev** [comment]
@bonustrack I have a question about architecture.
What does `delegation` mean? As I understand it, this is a child route not tied to the name like https://snapshot.org/#/playground/`erc20-balance-of`, which opens access to the playground, the data for which it takes from the query parameter.

How should this page look like? Like https://snapshot.org/#/playground/erc20-balance-of or https://snapshot.org/#/strategy/erc20-balance-of ?

**Comment by RakeshUP** [comment]
I am starting to work on this. Can we have a Share button below the "Run/Play" button in actions that copies the URL to the clipboard? @bonustrack
