### ISSUE TITLE
Fix issues from npm audit

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#698]
We should fix issue from npm audit

https://github.com/snapshot-labs/snapshot/security/dependabot

![image](https://user-images.githubusercontent.com/16245250/134815019-6f4aecb7-04fe-4125-b374-36efce60924f.png)

**Comment by sarmatdev** [comment]
I would try to solve this issue, but I do not have access to the dependabot page

**Comment by midgerate** [comment]
@sarmatdev Isn't the screenshot above enough?

**Comment by dab1999** [comment]
0x4a0377BCc83343e7C1cd014AFAfEb3f41D08A964

**Comment by midgerate** [comment]
@sarmatdev are you still doing this?

**Comment by sarmatdev** [comment]
> @sarmatdev are you still doing this? 

I don't have access to the full security reports. Take this task if you want to solve it.

**Comment by midgerate** [comment]
@bonustrack axios comes from @portis/web3 and ansi-regex comes from eslint. 

portis/web3  and eslint are already the latest release possible. 

I do not see what we can do here?

**Comment by midgerate** [comment]
Another solution - disable portis/web3 till we have any updates from them.

**Comment by mktcode** [comment]
@sarmatdev you can enable security alerts in your fork. :)

**Comment by ChaituVR** [comment]
Created a PR here https://github.com/portis-project/web-sdk/pull/141 that can remove their unused dep that have this old version
