### ISSUE TITLE
Error notification message should be red, now transparent

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#699]
There is an issue with the style of the error message, it should be red but now it appear transparent:
![image](https://user-images.githubusercontent.com/16245250/134817649-ce5b671d-3b43-4b19-9a03-dc2af8397c3c.png)

Got this when i cancel a signature on Metamask when updating a space settings.

**Comment by bonustrack** [comment]
Also the success notification message box should not have border 
![image](https://user-images.githubusercontent.com/16245250/134817749-427cdf1e-4fd1-426c-95a4-deb55085bafe.png)

**Comment by sarmatdev** [comment]
@bonustrack Fix this — #702

**Comment by spiritbro1** [comment]
i think i saw similiar PR by @samuveth yesterday https://github.com/snapshot-labs/snapshot/pull/687

**Comment by samuveth** [comment]
Yeah @bonustrack already fixed https://github.com/snapshot-labs/snapshot/pull/687

**Comment by samuveth** [comment]
Fixed https://github.com/snapshot-labs/snapshot/pull/702
