### ISSUE TITLE
Add manifest.json to snapshot to make it compatible with Gnosis Safe apps

### ISSUE THREAD

**Issue by midgerate** [snapshot-labs/snapshot#706]
example https://github.com/gnosis/safe-apps-sdk/blob/master/packages/cra-template-safe-app/template/public/manifest.json

see https://docs.gnosis.io/safe/docs/sdks_safe_apps/

This might enable PWA in snapshot. But we do not want Add To Homepage popup. 

@bonustrack  - Please add user story.

**Comment by bonustrack** [comment]
This is our brand material with svg etc https://github.com/snapshot-labs/brand

**Comment by samuveth** [comment]
@bonustrack after reading the docs I don't think adding a "manifest" will be enough for snapshot to work as a Gnosis Safe App. All the example projects that I've look at have created a separate App just for their Safe App integration.

**Comment by midgerate** [comment]
@bonustrack I had a chat with @samuveth, we would also need to figure out how would transactions show up in gnosis safe since we only verify the signatures and not execute a transaction on-chain

**Comment by samuveth** [comment]
> @bonustrack I had a chat with @samuveth, we would also need to figure out how would transactions show up in gnosis safe since we only verify the signatures and not execute a transaction on-chain 

@midgerate yes, we will do that in another PR. My bad I forgot to update you on this
