### ISSUE TITLE
Design for comment system on proposal

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#788]
- The comments should be only with 1 level (no reply)
- Should follow current design
- Should not support markdown
- There should be a way to upvote or downvote

Here is an example of proposal: https://snapshot.org/#/gnosis.eth/proposal/QmNMRBnipvRfos9ze1MrKpFAsHqxhNrmxjrXzxJnhFif9b

@themce Proposal https://www.figma.com/file/vBHtWA3XchdUQDC9OFk2tq/Design-Exploration?node-id=340%3A2010

**Comment by imsys** [comment]
Could the comments at least support line-breaks?

When discussing proposals, each other showing their arguments, it can get quite long and become messy without line-breaks.

Thanks.

**Comment by zzuziak** [comment]
Hey @bonustrack, we can keep it as a base issue for the comments / discussion plugin and write a proper pitch for it. Could be potentially included in the next cycle after current pitches.
