### ISSUE TITLE
Playground sharable links are too long

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#808]
Playground sharable links are too long, need shorter URLs to share them easily (on discord there is a limit on size of message) , maybe should try base64 encoding

**Comment by samuveth** [comment]
@ChaituVR does this still persist?

**Comment by ChaituVR** [comment]
Yea yea, It is like a feature request, not a bug, big URLs are kind of not good to share. but not sure what could be the best way on the front end to shorten this

**Comment by mktcode** [comment]
I have no idea other than using a URL shortener.  Since we launch our own service for everything, why not our own short URL service? Might also be nice for proposal links.

The number of addresses seems to be the main factor. But I don't think we should put a limit on it.

**Comment by ChaituVR** [comment]
Yes Yes!! Nice idea. there is a plan to create a service for sharable links (which can generate meta tags for proposals/spaces and open app/website) but Fabien said it is not a priority, maybe once it is available we can handle this there😅

**Comment by zzuziak** [comment]
Closing this one after discussing with @bonustrack :pray:

**Comment by ChaituVR** [comment]
Any reason? @zzuziak
