### ISSUE TITLE
Add new voting system with 3 choices: For, Against and Abstain

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#810]
We should add a voting system where we enforce only 3 choices, "For", "Against" and "Abstain" following Compound Governor Bravo standard. When this voting system is selected we shouldn't be able to edit the choices. Snapshot hub should enforce that with this type of proposal there will be always the same 3 choices.

**Comment by midgerate** [comment]
Need the name of the Voting type.
