### ISSUE TITLE
Add space params "categories" on the settings page, with ability to select 0 to 2 categories

### ISSUE THREAD

**Issue by midgerate** [snapshot-labs/snapshot#816]

**Comment by midgerate** [comment]
We need a multi-select box design before this can be done.

**Comment by bonustrack** [comment]
Here is a better list of categories
![image](https://user-images.githubusercontent.com/16245250/140382824-39da37fd-572f-4bd4-9dae-7059e40e3f15.png)

**Comment by AlanNabiev** [comment]
@bonustrack if there were sources and a list of categories, then I could do something similar

**Comment by bonustrack** [comment]
@AlanNabiev You can use this list https://github.com/snapshot-labs/snapshot.js/blob/f4bec9c6ffc5862374a392855f2ebfeb80fbbcf2/src/schemas/space.json#L207-L214

**Comment by AlanNabiev** [comment]
@bonustrack and what about images?

**Comment by bonustrack** [comment]
Images could be spaces avatars using the same categories

**Comment by AlanNabiev** [comment]
@bonustrack I didn't find some icons. For example, sushi and some others, if you would direct me to their location or tell me where I can put the same icons that are not there, but they are needed, then I could complete the task

**Comment by AlanNabiev** [comment]
@bonustrack i moved everything to a new PR #1062
