### ISSUE TITLE
Snapshot's block links in Avalanche aren't working

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#824]
Issue:
The Snapshot block links in Avalanche aren't working because they end with block instead of blocks, like so https://cchain.explorer.avax.network/block/5254055

Solution:
Consider adding two more optional params in to network object, explorerBlockPath and explorerAddressPath ?

Alternatives:
If it's not worth making such params, plz suggest alternatives

**Comment by zzuziak** [comment]
@ChaituVR do you know what's the status here?
