### ISSUE TITLE
Reduce code or complexity

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#853]
Reduce code, remove code duplicate, simplify things, remove unused dependency, if you can reduce code or complexity without removing a feature, feel free to make a PR.

**Comment by aiinkiestism** [comment]
I'll work on this.

**Comment by aiinkiestism** [comment]
I've just tested the latest version of @vitejs/plugin-vue and @vue/compiler-sfc. 

package.json
```
---
  "@vitejs/plugin-vue": "^1.9.3",
  "@vue/compiler-sfc": "^3.2.20",
---
```

Two problems I mentioned in the last comment were still alive, so I think $ref and $computed will be of limited use and for the purpose of keeping code clean and consistent I'm not sure they are helpful right now, if my take is right.
