### ISSUE TITLE
No / Yes opposition in "Set outcome" safesnap modal 

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#863]
Something potentially confusing here, I feel that the "YES" button should be "unset" because it should be a choice and not a validation.

Switch the "YES" button to "unset"
<img width="196" alt="Capture d’écran 2021-10-09 à 19 21 47" src="https://user-images.githubusercontent.com/55286013/136659106-6eb92cce-b575-43aa-867d-0fb17fd54b33.png">

**Comment by zzuziak** [comment]
Hey @mktcode, what's the status of this issue?

**Comment by mktcode** [comment]
@metrox-eth Not sure what you mean. It makes sense for me. You could only use one button "Set outcome to <opposite>". I already did that on my branch. I think we don't need to change anything here.
