### ISSUE TITLE
GraphQL API - Query spaces based on their admin and author addresses

### ISSUE THREAD

**Issue by rcmenezes** [snapshot-labs/snapshot#871]
**Is your feature request related to a problem? Please describe.**
Kind of. I am building one app (https://backdrop.so) that leverages Snapshot data, but is focused on a profile/wallet. This means I'd love to be able to know if that profile is the admin or an author in a space, so that we can get that quality signal about their affiliation with a certain DAO. I'm pretty sure my app isn't the only one to need this, and this type of data will allow for better graphs of collaboration across web3 :)

**Describe the solution you'd like**
I think adding a field liked `admin` and `author` to the `SpaceWhere` type query would be sufficient. So, we would be able to pass that condition in the GraphQL query, e.g: `query { spaces(where: { admin: $address } ...`

**Describe alternatives you've considered**
I'm right now getting to profiles who belong to spaces by fetching votes that they've done in that space, but that doesn't cover cases where admins/authors don't vote and cases where votes didn't happen yet.

**Comment by mktcode** [comment]
@rcmenezes This is what you mean? https://github.com/snapshot-labs/snapshot-hub/pull/160
