### ISSUE TITLE
Should have a way to test strategy when a strategy is added to space settings

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#882]
**Is your feature request related to a problem? Please describe.**
Should have a way to test strategy when a strategy is added to space settings, to make sure everything is working as expected

**Comment by mktcode** [comment]
We could add a link to the playground.

![image](https://user-images.githubusercontent.com/6792578/173575087-158de17e-f8d0-4e28-9c73-9b15936075c0.png)

**Comment by samuveth** [comment]
Instead of just "Playground" maybe "Test in playground"?
