### ISSUE TITLE
Proposal Broke in the Middle of a Vote

### ISSUE THREAD

**Issue by mudgen** [snapshot-labs/snapshot#900]
**Describe the bug**
A proposal broke in the middle of a vote.   The proposal is here: https://snapshot.org/#/quickvote.eth/proposal/QmWjFUMkcfjVk96iEaFqvUKFePCvyVLKhmuCK4Js1DZyuZ

If gives Javascript errors in the console in Chrome and Firefox.  The voting results are missing in the webpage.

Please help me fix this. We are in the middle of a vote.

The Strategy calls the `balanceOf` function in this contract on Polygon: https://polygonscan.com/address/0xc8c99157007e366d2ea9bdae13dc57d5844c64e9#code

Here is a link to a screenshot of the errors in Chrome: https://media.discordapp.net/attachments/747049240022482974/898649982935105546/snapshotwebpageerrors.png?width=554&height=737

**Comment by samuveth** [comment]
@mudgen are you still experiencing this issue?

**Comment by mudgen** [comment]
@samuveth Thanks for checking with me.   I am using a temporary workaround for now.   The strategy for the proposal was changed to use paging to avoid the read-only gas limit:
```
{
  "limit": 2,
  "symbol": "QUICK",
  "strategy": {
    "name": "erc20-balance-of",
    "params": {
      "symbol": "QUICK",
      "address": "0xc8C99157007E366d2eA9BdAE13DC57D5844C64E9",
      "decimals": 18
    }
  }
}
```

However this workaround may break if we get a lot of votes because it will make a lot of requests to the server.

It seems that the underlying problem may be that the RPC connection is using a read-only gas limit.   Snapshot uses Moralis for nodes so I posted on their forum asking them to significantly increase or remove their read-only gas limit.  See here: https://forum.moralis.io/t/read-only-gas-limit-is-too-low-probably/3447/2

I would really appreciate if you could follow up with them to help get it done.  

Here's to getting shit done! 🥂
