### ISSUE TITLE
Auto-detect owned ENS domains and update TEXT record from UI when creating new space.

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#917]
To make the process of creating a new space more seamless, we want to eradicate the necessity to move over to https://app.ens.domains and do as much as possible inside of the snapshot UI.

The ENS Subgraph can be used to easily retrieve the domain names owned by an account.
https://thegraph.com/hosted-service/subgraph/ensdomains/ens?query=Example%20query (hosted service should be fine for this)

![image](https://user-images.githubusercontent.com/6792578/138126826-f44501d7-0aac-4cf0-8827-b88a28c241e3.png)
(account must be lowercase)

For settings the TEXT record from the UI:

https://www.npmjs.com/package/@ensdomains/ensjs

> `async setText(key: String, recordValue: String) => Promise<EthersTxObject>`
Sets the text record for a given key for the current ENS name.

(Outside the scope of this issue: Ideally at some point we can even support registration of new ENS domains through snapshot.)

**Comment by sudeepb02** [comment]
Hi, I would like to take up this issue. I have checked out the code for `@ensdomains/ensjs` npm package on a local test repository and got it to work. Given this is my first issue for the repo, I'll go through the code and ask any doubts here.

**Comment by bonustrack** [comment]
Sound good! Ideally we should use the function sendTransaction from Snapshot.js to uodate the text record, ENS.js is a bit heavy.
