### ISSUE TITLE
Strategy space count is wrong

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#922]
**Describe the bug**
If we go to any strategy it will show the strategy count
![image](https://user-images.githubusercontent.com/15967809/138283065-cbe5ba0d-380c-42e3-868c-613cebf85dc4.png)

But if go to https://hub.snapshot.org/api/spaces, we see `anti-whale` is used by three spaces only, same with pod-leader used by only one space (strategy is used 3 times in one space) but the count displayed on UI is 3 spaces 

So it actually calculates the number of time strategies is used but not the number of spaces

**Comment by rootial** [comment]
this is fixed in the pr above. we can close it now.
