### ISSUE TITLE
Extend Snapshot.page from 1:1 voting to Quadratic Voting

### ISSUE THREAD

**Issue by owocki** [snapshot-labs/snapshot#94]
### Actual behavior
1:1 voting

### Expected behavior
Implement quadratic voting on snapshot.page

WHY: Quadratic Voting ( https://en.wikipedia.org/wiki/Quadratic_voting ) is a mathematically elegant way to make sure that decisions are made in a more democratic way.  It mutes the influence of whales. It optimizes for the voting power of the "poor and many" over the "rich and many".

In order to implement QV on Snapshot.page, i think all we need to do to do an entirely trivial QV implementation is:
1. For each new proposal, the user can select '1:1 voting' or "QV voting".
2. If the proposal is in QV mode, votes on that proposal should count quadratically instead of 1to1.  (the math is easy; just take the sqrt of the vote instead of the vote, and add that to the total - you can see an example here https://wtfisqf.com/ - esp in the linked javascript library )

A less naive implementation (lets call it Milestone 2) would be to introduce some sort of sybil resistence to the system.  We’d have to integrate with something that can provide Sybil resistance as an minimal identity layer...  Let's cross that bridge when we get to it, but some early promising routes
1. BrightID integration (make each voter be a verified BrightID user), and use that as sybil resistence.
2. Integrate with Gitcoin (make each voter authenticate with their Gitcoin account), and use that as sybil resistence.

**Comment by bonustrack** [comment]
Awesome! 

For the milestone 1 i recommend to use a "strategy". Strategies are functions that calculate result of a proposal on the UI. The default strategy is to take the balance of an ERC20 for each voters. We can duplicate the `erc20-balance-of` strategy maybe call it `erc20-balance-of-qv` and apply a sqrt() of the results at the end of the function. Learn more here about strategies here: https://docs.snapshot.page/strategies

**Comment by Greg-Johns** [comment]
I added radio buttons for view type options to the interface, would need to coordinate more to make sure end point support this feature.

**Comment by CrisBRM** [comment]
Quadratic voting in non Sybil resistant environments actually amplifies the voting power of bad actors tenfold. Be careful.

**Comment by lpfloyd** [comment]
Hence why BrightID my friend. Gitcoin has done an insane amount of work to improve the sybil resistance of their protocol since round 1.

**Comment by owocki** [comment]
@bonustrack would you be ok if i bountied this out to get it built? i think we cna use brightid for the anti sybil layer

**Comment by jonathan-s** [comment]
Would also be interested in seeing this built.

**Comment by Magicking** [comment]
Would this strategy https://github.com/snapshot-labs/snapshot.js/blob/master/src/strategies/erc20-balance-of-cv/index.ts be Milestone 1?
