### ISSUE TITLE
Get support for EIP-712 across all connectors

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#950]
Here are the connectors that does not support EIP-712, or does not support array type

**Does not support typed data**
- Trezor https://github.com/trezor/trezor-firmware/issues/1272
- Gnosis Safe https://github.com/gnosis/safe-apps-sdk/issues/204

**Does not support typed data array type**
- WalletConnect https://github.com/WalletConnect/walletconnect-monorepo/issues/546
- Portis https://github.com/portis-project/web-sdk/issues/140
- Coinbase wallet https://github.com/walletlink/walletlink/issues/196

Brave

**Comment by bonustrack** [comment]
Coinbase wallet typed data with array seem to work now, updated on Snapshot to default to typed data https://github.com/snapshot-labs/snapshot/commit/525748fcbbed24274e9128e35e62cd522ab4d2ea

**Comment by samuveth** [comment]
> Coinbase wallet typed data with array seem to work now, updated on Snapshot to default to typed data [525748f](https://github.com/snapshot-labs/snapshot/commit/525748fcbbed24274e9128e35e62cd522ab4d2ea), Portis and WalletConnect with Argent is still not working for me with array typed data.

@bonustrack I can not vote with Coinbase wallet anymore after your change. I have the latest version of Coinbase wallet installed and I'm on snapshot `0.1.4#db6121e` version. Why was there never a PR for this change btw?

**Comment by bonustrack** [comment]
@samuveth Are you on iOS?

**Comment by samuveth** [comment]
> @samuveth Are you on iOS?

No

**Comment by bonustrack** [comment]
That's super weird, I can reproduce the same issue now, while I'm sure it was working before, I can see my vote here with my Coinbase wallet address:
https://snapshot.org/#/fabien.eth/proposal/0x670f328d7cda120e9056ab19836592878fbc36fd0c3504ec9eebeeb9f780e691
https://cloudflare-ipfs.com/ipfs/QmZUYAfzZxKoeaAebvQRF3fcZcaVXZEwLrHHHAyJw2aU3t

**Comment by volkyeth** [comment]
btw, Trezor added support for EIP-712. Now the only missing piece is Metamask support for it: https://github.com/MetaMask/eth-trezor-keyring/pull/117

**Comment by midgerate** [comment]
Took Inventory of what's missing and working

By v3 I just refer to typed data working. 
Typed array support was included in v4. 

**Walletconnect** 
Trust - v4 Works 
Rainbow - v4 Works
Metamask - v3 works, v4 Stuck After Signing in metamask
Argent - v3 and v4 gives wrong signature error
Gnosis - v3 and v4 does not working

**Gnosis Safe App** - v3 and v4 does not work

**Trezor with Metamask** - TBD

**Coinbase** - TBD

**Portis** - v3 works, v4 gives error

**Comment by midgerate** [comment]
Remove fortmatic from UI 
Update Code to use EIP712 for coinbase.

**Comment by midgerate** [comment]
Not working right now

Gnosis
WalletConnect (Metamask)
Coinbase Wallet

**Comment by samuveth** [comment]
WalletConnect PR was merged and released https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/1.8.0

**Comment by samuveth** [comment]
Only missing Coinbase wallet and Gnosis safe

https://github.com/coinbase/coinbase-wallet-sdk/issues/508
https://github.com/safe-global/safe-react/issues/4027#issuecomment-1202622001

**Comment by samuveth** [comment]
Waiting for https://github.com/safe-global/safe-apps-sdk/issues/363
