### ISSUE TITLE
Rename "quadratic voting" vote type as sybil-protection isn't implemented

### ISSUE THREAD

**Issue by TimDaub** [snapshot-labs/snapshot#951]
"Quadratic voting" as it's being defined by academic papers and e.g. on Wikipedia has a particular quality to it as it's supposed to address the tyranny of the majority. The voting mechanism described in Radical Markets and elsewhere makes an implicit assumption that each identity gets to vote once with a fixed number of voting credits.

However, from what I'm understanding when testing snapshot's implementation (this one: https://github.com/snapshot-labs/snapshot/blob/25907c5da4b77462eb65814bd960e525640da3df/src/helpers/voting/quadratic.ts), then the snapshot system itself isn't capable of protecting against identity fraud during votes.

E.g. if a snapshot vote is created with the vote type being quadratic, but e.g. arbitrarily distributed ERC20 token balances are used as a strategy, then the vote shouldn't indeed be called a "quadratic vote".

It's because then, any ERC20 holder is free to distribute their tokens to as many Ethereum addresses that they want before the "snapshot", meaning that big ERC20 holders can have an even higher impact on the vote through creating "Sybils" ("cheating").

I think it is hence important to signal to all users that indeed the snapshot vote type "quadratic" isn't a "quadratic vote", but rather a vote tally algorithm that - for each voting issue, takes the square root of the voting result and assumes it as the outcome.

The similarity to a "quadratic vote" is that the same mathematical function is used in the tally. The name "quadratic vote" is already taken by the idea proposed by Weyl and Lalley in Radical Markets (e.g. see here: https://en.wikipedia.org/w/index.php?title=Quadratic_voting&oldid=1049808681). A quadratic vote makes no fragile assumptions about identities. It guarantees that each person can only vote once and hence is a solution to the tyranny of the majority. Square rooting the vote tally isn't a solution to the tyranny of the majority. 

Square rooting the vote tally can also have benefits in voting as e.g. it limits the impact of honest whales. But without Sybil protection and the assumption that 1 address = 1 identity, it's fragile and "unsafe" according to the [safety property](https://en.wikipedia.org/wiki/Safety_property) in distributed systems.

I suggest renaming the vote type to e.g. "vote tally square root".

**Comment by bonustrack** [comment]
@TimDaub Agree on this, the quadratic voting on Snapshot should not be used with just token holding, there should be some sybil resistance with it. This is something you can implement with voting strategies, sybil resistance mechanisms are very opinionated, we have strategies using NFT, BrightID, Colony reputation, we also working with Orange protocol with others mechanism learn more here https://twitter.com/OrangeProtocol/status/1453298869077430274

**Comment by samuveth** [comment]
There are a growing number of solutions POH, BrightID, WorldCoin, soulbound NFT's. It would be nice to see this as a more dominant feature on Snapshot.

**Comment by zzuziak** [comment]
Hey @samuveth would you be up for scoping the solution for this issue?

**Comment by samuveth** [comment]
This is basically solved by voting validation.
