### ISSUE TITLE
Improve Proposal Page on Snapshot

### ISSUE THREAD

**Issue by midgerate** [snapshot-labs/snapshot#952]
List of things that have bad UX on the proposal page. 

1. New Proposal should be a button. 
2. Better use of space in the proposal list. 
3. Missing description of the space. 
4. Better use of space below the space block
5. One mobile - Space block is completely missing. 
6. From the proposal card, it would be nice to have information like (# Votes, # Abstain, # Quorum)

**Comment by zzuziak** [comment]
@Sekhmet might be useful as insights for SX :pray:
