### ISSUE TITLE
Suggest ENS domain for logged users

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#954]
On the setup page here https://snapshot.org/#/setup
We should check if the logged user has ENS domains, if he has we should show max 5 suggestions like this:
![image](https://user-images.githubusercontent.com/16245250/138929698-3f6ecba8-61ba-47e7-bb49-c7d16cb45b70.png)
When we click on the suggested domain it should populate the field. The existing spaces should not appear as suggested.

**Comment by sarmatdev** [comment]
@samuveth This issue had no updates for about 10 days. May I hang out with this task?

**Comment by ChaituVR** [comment]
@KennethAshley Any update on this?

**Comment by WUXINYIMiffy** [comment]
I can take this.

**Comment by sarmatdev** [comment]
Done this in #1029
