### ISSUE TITLE
Basic voting type broken

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#979]
There is an issue, you can't cast a vote with basic type atm see:
https://snapshot.org/#/fabien.eth/proposal/0xc8c6e3f4108e5e16a0464f2b919d7d6c6a5da2a47e9058b7546404b552231b0c

Also when creating a proposal the translation doesnt work: 
![image](https://user-images.githubusercontent.com/16245250/139530731-10bc9b2c-8beb-4ac8-9450-2b62a242b9d8.png)

**Comment by ChaituVR** [comment]
Maybe we should merge this https://github.com/snapshot-labs/snapshot/pull/870 🤔

**Comment by samuveth** [comment]
@bonustrack Basis voting wasn't merged yet on the frontend 😆

**Comment by samuveth** [comment]
Fixed https://github.com/snapshot-labs/snapshot/pull/870
