### ISSUE TITLE
Better lazyloading for long lists of votes

### ISSUE THREAD

**Issue by mktcode** [snapshot-labs/snapshot#980]
https://snapshot.org/#/uniswap/proposal/QmP3H8WGLiWTP2WumKyrq8yA1xz1XbwkT8brdGYePuAcES

![votes-lazyloading](https://user-images.githubusercontent.com/6792578/139532013-35f51d5f-b68d-4bf7-b2a0-cb9d0d05655b.gif)

After clicking "See more" all other votes are loaded. This should be split into chunks.
A loading state / spinner animation is also missing

**Comment by bonustrack** [comment]
Fixed in #1024
