### ISSUE TITLE
Send Email when proposal has started

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#987]
Send Email 

Spec needed -- 
How do we get their email? 
Email Template?
Mailgun? 

For Later
- Digest of proposals created and option for the user to choose the frequency (as they happen, daily, weekly, monthly)
- Option for the user to choose what kinds of items they should be sent email with (New Proposals, Vote on proposal, etc)

**Comment by bigint** [comment]
I'd say it is better to handle on hub

**Possibilities**

- We can use nodemailer with aws ses SMTP with a custom template (suggested)
- We can use postmark if we need to handle it from the frontend (not suggested)
- Mailgun is good, but managing is bit hard

/cc @bonustrack

**Comment by zzuziak** [comment]
Hi @bonustrack, is this issue still relevant?

**Comment by wa0x6e** [comment]
WIP from https://github.com/snapshot-labs/snapshot/pull/3754
