### ISSUE TITLE
Fix WalletConnect typedData issue

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#988]

**Comment by midgerate** [comment]
Waiting for https://github.com/MetaMask/metamask-mobile/pull/3350 to be merged

**Comment by samuveth** [comment]
Can this be closed @midgerate

**Comment by midgerate** [comment]
Metamask is still an issue. So lets keep it open @samuveth

**Comment by samuveth** [comment]
Don't we have this https://github.com/snapshot-labs/snapshot/pull/1008 for that

**Comment by midgerate** [comment]
Yeah but that's a PR for testing. WE also have an issue that tracks all the EIP712 issues. #950

**Comment by bonustrack** [comment]
Closing this issue, should be fixed already.
