### ISSUE TITLE
Register ENS domain from Snapshot page

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#989]
### Plan:
- Go to the [Setup page](https://snapshot.org/#/setup)
- Enter space name / Select populated ENS name (#954)
- Below two steps are covered in (https://github.com/snapshot-labs/snapshot/issues/1132)
- If space exists - Redirect to space on click of submit button 
- If space doesn't exist:
    - Check if the name is registered
    - If the name belongs to the user - Redirect to space on click of submit button 
    - If the name is already registered by someone else - Show not available message
    - If the name is available:
        - Change button text to "Register" and on click redirect to register page with the name input

### Register Page:

- Check the network of the wallet and if not on mainnet ask the user to change the network
- If the name is already registered by someone else - Show not available message
- If the name is not registered :
    - Check name is a subdomain? If no,
        - Ask for a number of years and show est. cost + gas
            
            Refer [ens-app\src\api\price.js](https://github.com/ensdomains/ens-app/blob/dev/src/api/price.js)
            
        - STEP 1: Request to register (Commit)
            
            ```jsx
            // https://ropsten.etherscan.io/address/0x283Af0B28c62C092C9727F1Ee09c02CA627EB7F5
            // [ 'function commit(bytes32 commitment)' ]
            https://ropsten.etherscan.io/tx/0xa89ae00cbea63aa3b1a798bc575b6940baad6310899748a67b9063ac34f78b42
            ```
            
        - STEP 2: Wait for one minute
            
            After the above transaction is successful
            
            **Wait for 1 minute (minCommitmentAge method) and will be valid till 7 Days (maxCommitmentAge method)**
            
        - STEP 3: Complete registration
            
            Register with config method
            
            ```jsx
            // 0x283Af0B28c62C092C9727F1Ee09c02CA627EB7F5
            [
              'function registerWithConfig(string name, address owner, uint256 duration, bytes32 secret, address resolver, address addr) payable'     
            ]
            ```
            
            [https://ropsten.etherscan.io/tx/0xbc0e8c320943bbc666e56f7a34d91e2d7fed109a5cfe033ce8040988d8d15bf9](https://ropsten.etherscan.io/tx/0xbc0e8c320943bbc666e56f7a34d91e2d7fed109a5cfe033ce8040988d8d15bf9)
            
        - Set `snapshot` text record
            
            ```jsx
            Find resolver from 0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e by passing the node
            mainnet: 0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41
            ropston: 0x42D63ae25990889E35F215bC95884039Ba354115
            
            call setText function
            [ 'function setText(bytes32 node, string key, string value)' ]
            
            ```
            
    - If the name is subdomain:
        - Set sub-node record
            
            ```jsx
            0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e
            [
              'function setSubnodeRecord(bytes32 node, bytes32 label, address owner, address resolver, uint64 ttl)'
            ]
            https://ropsten.etherscan.io/tx/0xc8ccd2a49b62f13044edf133e19bf031cb626f7366b1c82bd3e3cc9aaf1a67a1
            ```
            
        - Set `snapshot` text record - same as above
    - If all the above steps are successful - Redirect to the settings page

**Comment by bonustrack** [comment]
Related to https://github.com/snapshot-labs/snapshot/issues/954

**Comment by samuveth** [comment]
Oh sorry I miss read this issue, thought it was done

**Comment by zzuziak** [comment]
Hi @midgerate what's the status of this issue? 🙏

**Comment by samuveth** [comment]
@midgerate is no longer working on this.
