### ISSUE TITLE
Blind voting

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#996]
Create a space setting "blind": true / false. By default we assume it's false but once it's enabled we should show results and votes choice only once the logged user voted.

**Comment by sarmatdev** [comment]
As I understand this task — we need to hide votes results if the "blind" setting is true, but the task also requires that votes choice be hidden. If we are hiding the votes choice, how the user will vote?🤔

**Comment by mktcode** [comment]
I guess hiding only refers to existing results, to not bias a vote, right?

**Comment by samuveth** [comment]
@ChaituVR @sarmatdev have you started work on UI for this?

**Comment by ChaituVR** [comment]
> @ChaituVR @sarmatdev have you started work on UI for this?

Nope :) not assigned to me

**Comment by mktcode** [comment]
Is an option "hide until ended" maybe interesting too?
What about per proposal setting?

I'd maybe just add a dropdown to the proposal create form:

Show results:
- always
- when user has voted
- when proposal has ended

**Comment by mktcode** [comment]
Just got another request for this feature on discord. If I see correctly, the necessary changes in hub and snapshot.js are already implemented so we only need a nice little toggle on the settings page, right? I can do that later.
